\set ON_ERROR_STOP on
begin;
create temporary table appointment_test_ids(name text primary key,id uuid);
grant all on appointment_test_ids to authenticated,service_role;
create function pg_temp.id(text) returns uuid language sql as $$select id from appointment_test_ids where name=$1$$;
create function pg_temp.ok(condition boolean,label text) returns void language plpgsql as $$begin if condition is not true then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end$$;
create function pg_temp.denied(statement text,expected_error text,label text) returns void language plpgsql as $$declare message text; begin begin execute statement; exception when others then message:=sqlerrm; end; perform pg_temp.ok(message is not null and message like '%'||expected_error||'%',label); end$$;
insert into appointment_test_ids values('admin','11111111-1111-4111-8111-111111111111'),('applicant','22222222-2222-4222-8222-222222222222'),('other','33333333-3333-4333-8333-333333333333');
insert into auth.users(id,email,raw_user_meta_data) select id,name||'@appointments.test.invalid',jsonb_build_object('account_type',case name when 'admin' then 'client' else 'individual' end,'display_name','Synthetic '||name) from appointment_test_ids;
insert into public.admin_roles(profile_id,role_id) select pg_temp.id('admin'),id from public.roles where name='Super Admin';
insert into public.verification_requests(profile_id) values(pg_temp.id('applicant')) returning id as verification \gset
insert into appointment_test_ids values('verification',:'verification');
set local role service_role;
select pg_temp.denied($q$select public.gw_create_appointment(pg_temp.id('applicant'),now()+interval '1 day',now()+interval '25 hours')$q$,'forbidden','normal applicant cannot create staff slots');
select pg_temp.denied($q$select public.gw_create_appointment(pg_temp.id('admin'),now()-interval '1 day',now()+interval '1 hour')$q$,'invalid_slot_time','administrator cannot create a past slot');
select pg_temp.denied($q$select public.gw_create_appointment(pg_temp.id('admin'),now()+interval '1 day',now()+interval '2 days')$q$,'invalid_slot_time','slot duration limited to eight hours');
select pg_temp.denied($q$select public.gw_create_appointment(pg_temp.id('admin'),now()+interval '1 day',now()+interval '25 hours',pg_temp.id('other'))$q$,'invalid_staff','ordinary accounts cannot be assigned as interview staff');
insert into appointment_test_ids select 'slot',(public.gw_create_appointment(pg_temp.id('admin'),now()+interval '1 day',now()+interval '25 hours',pg_temp.id('admin'),'Applicant instructions','PRIVATE INTERVIEW NOTES')->>'id')::uuid;
select pg_temp.denied($q$select public.gw_create_appointment(pg_temp.id('admin'),now()+interval '24 hours 30 minutes',now()+interval '26 hours',pg_temp.id('admin'))$q$,'staff_time_conflict','overlapping staff slots are rejected');
insert into appointment_test_ids select 'adjacent',(public.gw_create_appointment(pg_temp.id('admin'),now()+interval '25 hours',now()+interval '26 hours',pg_temp.id('admin'))->>'id')::uuid;
select pg_temp.ok((select count(*)=2 from public.appointments),'adjacent staff slots are allowed');
select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('slot'),1,'block');
select pg_temp.denied($q$select public.gw_book_appointment(pg_temp.id('applicant'),pg_temp.id('slot'),pg_temp.id('verification'))$q$,'slot_unavailable','blocked slot cannot be booked');
select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('slot'),2,'open');
select public.gw_book_appointment(pg_temp.id('applicant'),pg_temp.id('slot'),pg_temp.id('verification'));
select pg_temp.ok((select version=4 and status='booked' from public.appointments where id=pg_temp.id('slot')),'booking increments calendar version');
select pg_temp.denied($q$select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('slot'),3,'cancel')$q$,'stale_appointment','stale administrative edit cannot cancel a new booking');
select pg_temp.denied($q$select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('slot'),4,'block')$q$,'slot_not_available','booked slot cannot be silently blocked');
select pg_temp.denied($q$select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('slot'),4,'complete')$q$,'interview_not_started','future interview cannot be marked complete');
select pg_temp.denied($q$select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('slot'),4,'reschedule',now()+interval '25 hours',now()+interval '26 hours')$q$,'staff_time_conflict','reschedule checks staff conflicts');
select pg_temp.ok((select starts_at=now()+interval '1 day' and version=4 from public.appointments where id=pg_temp.id('slot')),'failed reschedule preserves time and version');
select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('slot'),4,'reschedule',now()+interval '2 days',now()+interval '49 hours');
select pg_temp.ok(exists(select 1 from public.notifications where profile_id=pg_temp.id('applicant') and data->>'event'='appointment_updated' and (data->>'starts_at')::timestamptz=now()+interval '2 days'),'rescheduling notifies applicant with committed time');
select pg_temp.ok(exists(select 1 from public.audit_logs where entity_type='appointments' and entity_id=pg_temp.id('slot')::text and actor_id=pg_temp.id('admin') and new_data->>'version'='5'),'rescheduling audit records actual administrator');
select pg_temp.ok(not exists(select 1 from public.notifications where body like '%PRIVATE%' or data::text like '%PRIVATE%'),'appointment notifications never include staff notes');
select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('slot'),5,'notes',staff_notes=>'PRIVATE CHANGED');
select pg_temp.ok((select count(*)=2 from public.notifications where profile_id=pg_temp.id('applicant')),'internal-only note change does not notify applicant');
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.id('applicant')::text,true);
select pg_temp.ok((select count(*)=1 from public.appointments where status='booked'),'applicant can read own booking');
select pg_temp.denied($q$select internal_notes from public.appointments$q$,'permission denied','applicant cannot select internal appointment notes');
select pg_temp.denied($q$select public.gw_create_appointment(auth.uid(),now()+interval '3 days',now()+interval '73 hours')$q$,'permission denied','scheduling RPC cannot be invoked with a forged actor from public API');
select set_config('request.jwt.claim.sub',pg_temp.id('other')::text,true);
select pg_temp.ok((select count(*)=0 from public.appointments where status='booked'),'unrelated applicant cannot read booked slot');
set local role service_role;
select pg_temp.denied($q$select public.gw_cancel_appointment(pg_temp.id('other'),pg_temp.id('slot'),6)$q$,'forbidden','another applicant cannot cancel a booking');
select public.gw_cancel_appointment(pg_temp.id('applicant'),pg_temp.id('slot'),6);
select pg_temp.ok((select status='interview_required' from public.verification_requests where id=pg_temp.id('verification')),'cancellation permits choosing a replacement interview');
select pg_temp.ok((select status='cancelled' and request_id=pg_temp.id('verification') from public.appointments where id=pg_temp.id('slot')),'cancelled appointment remains in applicant history');
select public.gw_book_appointment(pg_temp.id('applicant'),pg_temp.id('adjacent'),pg_temp.id('verification'));
-- Move only synthetic data into the past to exercise attendance without waiting a day.
update public.appointments set starts_at=now()-interval '1 hour',ends_at=now()+interval '1 hour' where id=pg_temp.id('adjacent');
select pg_temp.denied($q$select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('adjacent'),3,'complete')$q$,'attendance_required','interview requires recorded attendance');
select pg_temp.denied($q$select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('adjacent'),3,'no_show')$q$,'interview_not_finished','absence cannot be recorded before appointment ends');
select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('adjacent'),3,'attend');
select pg_temp.ok((select attendance='attended' and attendance_recorded_at is not null from public.appointments where id=pg_temp.id('adjacent')),'staff attendance is recorded with a timestamp');
select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('adjacent'),4,'complete');
select pg_temp.ok((select status='pending' from public.verification_requests where id=pg_temp.id('verification')) and (select verification_status='pending' from public.individual_profiles where profile_id=pg_temp.id('applicant')),'interview completion awaits separate human verification decision');
select pg_temp.denied($q$select public.gw_manage_appointment(pg_temp.id('admin'),pg_temp.id('adjacent'),5,'open')$q$,'appointment_closed','completed interview cannot be reopened as an empty slot');
select public.gw_verify(pg_temp.id('admin'),pg_temp.id('verification'),'verified');
select pg_temp.ok((select verification_status='verified' from public.individual_profiles where profile_id=pg_temp.id('applicant')),'human verification follows attended completed interview');
reset role;
rollback;
