import {isLocale,type Locale} from "@/lib/i18n";
export const adminModules=["Overview","Users","Individuals","Teams","Clients","Verification","Appointments","Work Requests","Offers","Projects","Messages","Message Moderation","Transactions","Payments","Payouts","Disputes","Appeals","Reviews","Notifications","Blog","Static Pages","Media","Categories","Skills","Languages","Email Outbox","Email Templates","AI Settings","Payment Settings","System Settings","Security Logs","Audit Logs","Roles"] as const;
export type AdminModule=(typeof adminModules)[number];
type AdminCopy={title:string;navigation:string;workspace:string;labels:Record<AdminModule,string>};
const labels:Record<Locale,readonly string[]>={
 en:adminModules,
 ar:["نظرة عامة","المستخدمون","الأفراد","الفرق","العملاء","التحقق","المواعيد","طلبات العمل","العروض","المشاريع","الرسائل","مراجعة الرسائل","المعاملات","المدفوعات","صرف المستحقات","النزاعات","الاستئنافات","التقييمات","الإشعارات","المقالات","الصفحات الثابتة","الوسائط","التصنيفات","المهارات","اللغات","متابعة البريد","قوالب البريد","إعدادات الذكاء الاصطناعي","إعدادات الدفع","إعدادات النظام","سجل الأمان","سجل التدقيق","الأدوار والصلاحيات"],
 tr:["Genel bakış","Kullanıcılar","Bireyler","Ekipler","Müşteriler","Doğrulama","Randevular","İş talepleri","Teklifler","Projeler","Mesajlar","Mesaj inceleme","İşlemler","Ödemeler","Kazanç ödemeleri","Uyuşmazlıklar","İtirazlar","Değerlendirmeler","Bildirimler","Yazılar","Sabit sayfalar","Medya","Kategoriler","Beceriler","Diller","E-posta kuyruğu","E-posta şablonları","Yapay zekâ ayarları","Ödeme ayarları","Sistem ayarları","Güvenlik kayıtları","Denetim kayıtları","Roller ve izinler"],
 es:["Resumen","Usuarios","Profesionales","Equipos","Clientes","Verificación","Citas","Solicitudes de trabajo","Ofertas","Proyectos","Mensajes","Moderación de mensajes","Transacciones","Pagos","Abonos","Disputas","Apelaciones","Reseñas","Notificaciones","Artículos","Páginas estáticas","Medios","Categorías","Habilidades","Idiomas","Cola de correo","Plantillas de correo","Ajustes de IA","Ajustes de pago","Ajustes del sistema","Registros de seguridad","Registros de auditoría","Roles y permisos"],
 fr:["Vue d'ensemble","Utilisateurs","Professionnels","Équipes","Clients","Vérification","Rendez-vous","Demandes de travail","Offres","Projets","Messages","Modération des messages","Transactions","Paiements","Versements","Litiges","Recours","Avis","Notifications","Articles","Pages statiques","Médias","Catégories","Compétences","Langues","File des courriels","Modèles de courriels","Paramètres IA","Paramètres de paiement","Paramètres système","Journaux de sécurité","Journaux d'audit","Rôles et permissions"],
 de:["Übersicht","Benutzer","Fachkräfte","Teams","Kunden","Verifizierung","Termine","Arbeitsanfragen","Angebote","Projekte","Nachrichten","Nachrichtenmoderation","Transaktionen","Zahlungen","Auszahlungen","Streitfälle","Einsprüche","Bewertungen","Benachrichtigungen","Artikel","Statische Seiten","Medien","Kategorien","Fähigkeiten","Sprachen","E-Mail-Warteschlange","E-Mail-Vorlagen","KI-Einstellungen","Zahlungseinstellungen","Systemeinstellungen","Sicherheitsprotokolle","Auditprotokolle","Rollen und Berechtigungen"]
};
const chrome:Record<Locale,{title:string;navigation:string;workspace:string}>={en:{title:"GazaWorks administration",navigation:"Administration menu",workspace:"My workspace"},ar:{title:"إدارة GazaWorks",navigation:"قائمة الإدارة",workspace:"مساحة عملي"},tr:{title:"GazaWorks yönetimi",navigation:"Yönetim menüsü",workspace:"Çalışma alanım"},es:{title:"Administración de GazaWorks",navigation:"Menú de administración",workspace:"Mi espacio de trabajo"},fr:{title:"Administration GazaWorks",navigation:"Menu d'administration",workspace:"Mon espace de travail"},de:{title:"GazaWorks-Verwaltung",navigation:"Verwaltungsmenü",workspace:"Mein Arbeitsbereich"}};
export function adminCopy(locale:string):AdminCopy{
 const language=isLocale(locale)?locale:"en";
 return {...chrome[language],labels:Object.fromEntries(adminModules.map((key,index)=>[key,labels[language][index]])) as Record<AdminModule,string>};
}
