import {isLocale,type Locale} from "@/lib/i18n";

const en={
  loadError:"Could not load these records.",saveError:"Could not save. Check the fields and your permissions.",saved:"Saved.",refresh:"Refresh",loading:"Loading…",empty:"No records available.",live:"Records",activate:"Activate",suspend:"Suspend",ban:"Ban",feature:"Feature",enable:"Enable",disable:"Disable",
  createCategory:"Create category",createSkill:"Create skill",slug:"URL identifier",language:"Language",status:"Status",draft:"Draft",published:"Published",title:"Title",body:"Content",excerpt:"Summary",savePage:"Save page",saveArticle:"Save article",pageHeading:"Create or translate a page",articleHeading:"Create or translate an article",
  roleHeading:"Create an administrator role",name:"Name",description:"Description",permissions:"Permission keys, separated by commas",createRole:"Create role",workerAward:"Professional entitlement (minor currency units)",clientRefund:"Client refund (minor currency units)",reasoning:"Decision reasoning",issueDecision:"Record decision",finalAppeal:"Final appeal decision",finalizeAppeal:"Finalize appeal",
  create:"Create",created:"Created successfully.",settingsHeading:"System setting",key:"Setting key",json:"JSON value",saveSettings:"Save setting",languagesHeading:"Interface languages",languagesHint:"Arabic uses right-to-left layout. English remains the fallback language.",saveLanguages:"Save languages",englishRequired:"Keep English enabled as the fallback language.",invalidJson:"Enter a valid JSON value.",unavailableModule:"This administration module is unavailable.",hidden:"Hide",removed:"Remove",open:"Open",assigned:"Assign to me",resolved:"Resolve",dismissed:"Dismiss",
};
type Copy={[K in keyof typeof en]:string};
const translations:Record<Locale,Copy>={
  en,
  ar:{
    loadError:"تعذّر تحميل السجلات.",saveError:"تعذّر الحفظ. راجع الحقول وصلاحياتك.",saved:"تم الحفظ.",refresh:"تحديث",loading:"جارٍ التحميل…",empty:"لا توجد سجلات.",live:"السجلات",activate:"تفعيل",suspend:"تعليق",ban:"حظر",feature:"إبراز",enable:"تفعيل",disable:"تعطيل",
    createCategory:"إنشاء تصنيف",createSkill:"إنشاء مهارة",slug:"معرّف الرابط",language:"اللغة",status:"الحالة",draft:"مسودة",published:"منشور",title:"العنوان",body:"المحتوى",excerpt:"الملخص",savePage:"حفظ الصفحة",saveArticle:"حفظ المقال",pageHeading:"إنشاء صفحة أو ترجمتها",articleHeading:"إنشاء مقال أو ترجمته",
    roleHeading:"إنشاء دور إداري",name:"الاسم",description:"الوصف",permissions:"مفاتيح الصلاحيات، مفصولة بفواصل",createRole:"إنشاء الدور",workerAward:"استحقاق المحترف (بالوحدة الصغرى للعملة)",clientRefund:"المبلغ المعاد للعميل (بالوحدة الصغرى للعملة)",reasoning:"أسباب القرار",issueDecision:"تسجيل القرار",finalAppeal:"قرار الاستئناف النهائي",finalizeAppeal:"حسم الاستئناف",
    create:"إنشاء",created:"تم الإنشاء بنجاح.",settingsHeading:"إعداد النظام",key:"مفتاح الإعداد",json:"القيمة بصيغة JSON",saveSettings:"حفظ الإعداد",languagesHeading:"لغات الواجهة",languagesHint:"العربية تستخدم اتجاهًا من اليمين إلى اليسار. تبقى الإنجليزية اللغة البديلة.",saveLanguages:"حفظ اللغات",englishRequired:"يجب إبقاء الإنجليزية مفعّلة كلغة بديلة.",invalidJson:"أدخل قيمة JSON صحيحة.",unavailableModule:"هذا القسم الإداري غير متاح.",hidden:"إخفاء",removed:"إزالة",open:"فتح",assigned:"إسناد إليّ",resolved:"حل",dismissed:"استبعاد",
  },
  tr:{
    loadError:"Kayıtlar yüklenemedi.",saveError:"Kaydedilemedi. Alanları ve yetkilerinizi kontrol edin.",saved:"Kaydedildi.",refresh:"Yenile",loading:"Yükleniyor…",empty:"Kayıt yok.",live:"Kayıtlar",activate:"Etkinleştir",suspend:"Askıya al",ban:"Engelle",feature:"Öne çıkar",enable:"Etkinleştir",disable:"Devre dışı bırak",
    createCategory:"Kategori oluştur",createSkill:"Beceri oluştur",slug:"URL tanımlayıcısı",language:"Dil",status:"Durum",draft:"Taslak",published:"Yayımlandı",title:"Başlık",body:"İçerik",excerpt:"Özet",savePage:"Sayfayı kaydet",saveArticle:"Makaleyi kaydet",pageHeading:"Sayfa oluştur veya çevir",articleHeading:"Makale oluştur veya çevir",
    roleHeading:"Yönetici rolü oluştur",name:"Ad",description:"Açıklama",permissions:"Virgülle ayrılmış yetki anahtarları",createRole:"Rol oluştur",workerAward:"Profesyonelin alacağı (para biriminin alt birimi)",clientRefund:"Müşteri iadesi (para biriminin alt birimi)",reasoning:"Kararın gerekçesi",issueDecision:"Kararı kaydet",finalAppeal:"Nihai itiraz kararı",finalizeAppeal:"İtirazı sonuçlandır",
    create:"Oluştur",created:"Başarıyla oluşturuldu.",settingsHeading:"Sistem ayarı",key:"Ayar anahtarı",json:"JSON değeri",saveSettings:"Ayarı kaydet",languagesHeading:"Arayüz dilleri",languagesHint:"Arapça sağdan sola gösterilir. İngilizce yedek dil olarak kalır.",saveLanguages:"Dilleri kaydet",englishRequired:"İngilizceyi yedek dil olarak etkin tutun.",invalidJson:"Geçerli bir JSON değeri girin.",unavailableModule:"Bu yönetim modülü kullanılamıyor.",hidden:"Gizle",removed:"Kaldır",open:"Aç",assigned:"Bana ata",resolved:"Çöz",dismissed:"Kapat",
  },
  es:{
    loadError:"No se pudieron cargar los registros.",saveError:"No se pudo guardar. Revise los campos y sus permisos.",saved:"Guardado.",refresh:"Actualizar",loading:"Cargando…",empty:"No hay registros.",live:"Registros",activate:"Activar",suspend:"Suspender",ban:"Bloquear",feature:"Destacar",enable:"Habilitar",disable:"Deshabilitar",
    createCategory:"Crear categoría",createSkill:"Crear habilidad",slug:"Identificador de URL",language:"Idioma",status:"Estado",draft:"Borrador",published:"Publicado",title:"Título",body:"Contenido",excerpt:"Resumen",savePage:"Guardar página",saveArticle:"Guardar artículo",pageHeading:"Crear o traducir una página",articleHeading:"Crear o traducir un artículo",
    roleHeading:"Crear un rol de administrador",name:"Nombre",description:"Descripción",permissions:"Claves de permisos separadas por comas",createRole:"Crear rol",workerAward:"Importe del profesional (unidad monetaria menor)",clientRefund:"Reembolso del cliente (unidad monetaria menor)",reasoning:"Motivos de la decisión",issueDecision:"Registrar decisión",finalAppeal:"Decisión final de apelación",finalizeAppeal:"Resolver apelación",
    create:"Crear",created:"Creado correctamente.",settingsHeading:"Ajuste del sistema",key:"Clave del ajuste",json:"Valor JSON",saveSettings:"Guardar ajuste",languagesHeading:"Idiomas de la interfaz",languagesHint:"El árabe se muestra de derecha a izquierda. El inglés permanece como idioma alternativo.",saveLanguages:"Guardar idiomas",englishRequired:"Mantenga el inglés habilitado como idioma alternativo.",invalidJson:"Introduzca un valor JSON válido.",unavailableModule:"Este módulo administrativo no está disponible.",hidden:"Ocultar",removed:"Eliminar",open:"Abrir",assigned:"Asignarme",resolved:"Resolver",dismissed:"Descartar",
  },
  fr:{
    loadError:"Impossible de charger les enregistrements.",saveError:"Impossible d’enregistrer. Vérifiez les champs et vos droits.",saved:"Enregistré.",refresh:"Actualiser",loading:"Chargement…",empty:"Aucun enregistrement.",live:"Enregistrements",activate:"Activer",suspend:"Suspendre",ban:"Bloquer",feature:"Mettre en avant",enable:"Activer",disable:"Désactiver",
    createCategory:"Créer une catégorie",createSkill:"Créer une compétence",slug:"Identifiant de l’URL",language:"Langue",status:"État",draft:"Brouillon",published:"Publié",title:"Titre",body:"Contenu",excerpt:"Résumé",savePage:"Enregistrer la page",saveArticle:"Enregistrer l’article",pageHeading:"Créer ou traduire une page",articleHeading:"Créer ou traduire un article",
    roleHeading:"Créer un rôle d’administration",name:"Nom",description:"Description",permissions:"Clés de droits séparées par des virgules",createRole:"Créer le rôle",workerAward:"Montant du professionnel (unité monétaire mineure)",clientRefund:"Remboursement du client (unité monétaire mineure)",reasoning:"Motifs de la décision",issueDecision:"Enregistrer la décision",finalAppeal:"Décision finale du recours",finalizeAppeal:"Clore le recours",
    create:"Créer",created:"Création réussie.",settingsHeading:"Paramètre système",key:"Clé du paramètre",json:"Valeur JSON",saveSettings:"Enregistrer le paramètre",languagesHeading:"Langues de l’interface",languagesHint:"L’arabe s’affiche de droite à gauche. L’anglais reste la langue de repli.",saveLanguages:"Enregistrer les langues",englishRequired:"Gardez l’anglais activé comme langue de repli.",invalidJson:"Saisissez une valeur JSON valide.",unavailableModule:"Ce module d’administration est indisponible.",hidden:"Masquer",removed:"Retirer",open:"Ouvrir",assigned:"M’attribuer",resolved:"Résoudre",dismissed:"Ignorer",
  },
  de:{
    loadError:"Datensätze konnten nicht geladen werden.",saveError:"Speichern fehlgeschlagen. Prüfen Sie die Felder und Ihre Berechtigungen.",saved:"Gespeichert.",refresh:"Aktualisieren",loading:"Wird geladen…",empty:"Keine Datensätze vorhanden.",live:"Datensätze",activate:"Aktivieren",suspend:"Sperren",ban:"Dauerhaft sperren",feature:"Hervorheben",enable:"Aktivieren",disable:"Deaktivieren",
    createCategory:"Kategorie erstellen",createSkill:"Fähigkeit erstellen",slug:"URL-Kennung",language:"Sprache",status:"Status",draft:"Entwurf",published:"Veröffentlicht",title:"Titel",body:"Inhalt",excerpt:"Zusammenfassung",savePage:"Seite speichern",saveArticle:"Artikel speichern",pageHeading:"Seite erstellen oder übersetzen",articleHeading:"Artikel erstellen oder übersetzen",
    roleHeading:"Verwaltungsrolle erstellen",name:"Name",description:"Beschreibung",permissions:"Berechtigungsschlüssel, durch Kommas getrennt",createRole:"Rolle erstellen",workerAward:"Anspruch der Fachkraft (kleinste Währungseinheit)",clientRefund:"Kundenerstattung (kleinste Währungseinheit)",reasoning:"Begründung der Entscheidung",issueDecision:"Entscheidung speichern",finalAppeal:"Endgültige Einspruchsentscheidung",finalizeAppeal:"Einspruch abschließen",
    create:"Erstellen",created:"Erfolgreich erstellt.",settingsHeading:"Systemeinstellung",key:"Einstellungsschlüssel",json:"JSON-Wert",saveSettings:"Einstellung speichern",languagesHeading:"Sprachen der Oberfläche",languagesHint:"Arabisch wird von rechts nach links angezeigt. Englisch bleibt die Ersatzsprache.",saveLanguages:"Sprachen speichern",englishRequired:"Englisch muss als Ersatzsprache aktiviert bleiben.",invalidJson:"Geben Sie einen gültigen JSON-Wert ein.",unavailableModule:"Dieses Verwaltungsmodul ist nicht verfügbar.",hidden:"Ausblenden",removed:"Entfernen",open:"Öffnen",assigned:"Mir zuweisen",resolved:"Lösen",dismissed:"Verwerfen",
  },
};
export function adminEditorCopy(locale:string){return translations[isLocale(locale)?locale:"en"]}
