import {isLocale,type Locale} from "@/lib/i18n";
const languages:Locale[]=["ar","en","tr","es","fr","de"];
const words:Record<string,string[]>={
 details:["عرض التفاصيل","View details","Ayrıntıları göster","Ver detalles","Voir les détails","Details anzeigen"],
 interviewRequiredHint:["اعتماد التحقق يتطلب مقابلة مكتملة وتسجيل حضور صاحب الحساب. افتح المواعيد وسجّل الحضور ثم أكمل المقابلة أولًا.","Verification requires a completed interview with attendance recorded. Open Appointments, record attendance and complete the interview first.","Doğrulama için katılımı kaydedilmiş tamamlanmış bir görüşme gerekir. Önce Randevular bölümünde katılımı kaydedip görüşmeyi tamamlayın.","La verificación requiere una entrevista completada con asistencia registrada. Registre la asistencia y complete la entrevista en Citas.","La vérification exige un entretien terminé avec présence enregistrée. Enregistrez la présence et terminez l’entretien dans Rendez-vous.","Die Verifizierung erfordert ein abgeschlossenes Gespräch mit erfasster Anwesenheit. Erfassen Sie die Anwesenheit und schließen Sie den Termin zuerst ab."],
 verificationNotAllowed:["لا يمكن اعتماد هذا الطلب: قد يكون حُذف أو يخص حسابك الشخصي.","This request cannot be approved: it may have been deleted or belong to your own account.","Bu talep onaylanamaz: silinmiş veya kendi hesabınıza ait olabilir.","No se puede aprobar: la solicitud puede haberse eliminado o pertenecer a su cuenta.","Impossible d’approuver : la demande a été supprimée ou concerne votre propre compte.","Nicht genehmigbar: Der Antrag wurde gelöscht oder gehört zu Ihrem eigenen Konto."],
 sessionExpired:["انتهت الجلسة. سجّل الدخول مجددًا.","Session expired. Sign in again.","Oturum sona erdi. Tekrar giriş yapın.","La sesión caducó. Inicie sesión de nuevo.","Session expirée. Reconnectez-vous.","Sitzung abgelaufen. Melden Sie sich erneut an."],
 permissionDenied:["حسابك لا يملك صلاحية تنفيذ هذا الإجراء.","Your account does not have permission for this action.","Hesabınız bu işlem için yetkili değil.","Su cuenta no tiene permiso para esta acción.","Votre compte n’a pas l’autorisation requise.","Ihr Konto ist für diese Aktion nicht berechtigt."],
 invalidFields:["راجع الحقول المطلوبة وصيغة البيانات قبل الحفظ.","Check required fields and their format before saving.","Kaydetmeden önce zorunlu alanları ve biçimleri kontrol edin.","Revise los campos obligatorios y su formato antes de guardar.","Vérifiez les champs obligatoires et leur format avant d’enregistrer.","Prüfen Sie die Pflichtfelder und ihr Format vor dem Speichern."],
 appointmentsLink:["فتح المواعيد","Open appointments","Randevuları aç","Abrir citas","Ouvrir les rendez-vous","Termine öffnen"],
 allPermissions:["كامل الصلاحيات","All permissions","Tüm izinler","Todos los permisos","Toutes les autorisations","Alle Berechtigungen"],
 permission_key:["الصلاحية","Permission","İzin","Permiso","Autorisation","Berechtigung"],
 ai_config:["إعدادات الذكاء الاصطناعي","AI settings","Yapay zekâ ayarları","Ajustes de IA","Paramètres IA","KI-Einstellungen"],
 feature_flags:["ميزات المنصة","Platform features","Platform özellikleri","Funciones de plataforma","Fonctionnalités","Plattformfunktionen"],
 payment_methods:["طرق الدفع","Payment methods","Ödeme yöntemleri","Métodos de pago","Moyens de paiement","Zahlungsmethoden"],
 commission:["عمولة المنصة","Platform commission","Platform komisyonu","Comisión de plataforma","Commission","Plattformprovision"],
 amount_minor:["المبلغ","Amount","Tutar","Importe","Montant","Betrag"],
 price_minor:["السعر","Price","Fiyat","Precio","Prix","Preis"],
 budget_min_minor:["الحد الأدنى للميزانية","Minimum budget","Minimum bütçe","Presupuesto mínimo","Budget minimum","Mindestbudget"],
 budget_max_minor:["الحد الأعلى للميزانية","Maximum budget","Maksimum bütçe","Presupuesto máximo","Budget maximum","Höchstbudget"],
 worker_award_minor:["استحقاق المحترف","Professional entitlement","Uzman hakkı","Importe del profesional","Droits du professionnel","Anspruch des Fachkräften"],
 client_refund_minor:["المبلغ المعاد للعميل","Client refund","Müşteri iadesi","Reembolso del cliente","Remboursement client","Kundenerstattung"],
 team_name:["اسم الفريق","Team name","Ekip adı","Nombre del equipo","Nom de l’équipe","Teamname"],
 subject:["الموضوع","Subject","Konu","Asunto","Objet","Betreff"],
 body_text:["نص الرسالة","Message text","Mesaj metni","Texto del mensaje","Texte du message","Nachrichtentext"],
 action:["الإجراء","Action","İşlem","Acción","Action","Aktion"],
 event:["الحدث","Event","Olay","Evento","Événement","Ereignis"],
 risk:["مستوى الخطورة","Risk level","Risk düzeyi","Nivel de riesgo","Niveau de risque","Risikostufe"],
 metadata:["تفاصيل إضافية","Additional details","Ek bilgiler","Detalles adicionales","Détails supplémentaires","Weitere Details"],
 old_data:["البيانات السابقة","Previous values","Önceki değerler","Valores anteriores","Valeurs précédentes","Vorherige Werte"],
 new_data:["البيانات الجديدة","New values","Yeni değerler","Valores nuevos","Nouvelles valeurs","Neue Werte"],
 entity_type:["نوع السجل","Record type","Kayıt türü","Tipo de registro","Type d’enregistrement","Datensatztyp"],
 notes:["ملاحظات","Notes","Notlar","Notas","Notes","Notizen"],
 user_notes:["ملاحظات المستخدم","User notes","Kullanıcı notları","Notas del usuario","Notes utilisateur","Benutzernotizen"],
 category_translations:["التصنيف باللغات","Category translations","Kategori çevirileri","Traducciones de categoría","Traductions de catégorie","Kategorieübersetzungen"],
 skill_translations:["المهارة باللغات","Skill translations","Beceri çevirileri","Traducciones de habilidad","Traductions de compétence","Fähigkeitsübersetzungen"],
 delivery_days:["مدة التسليم بالأيام","Delivery days","Teslimat günleri","Días de entrega","Délai en jours","Lieferzeit in Tagen"],
 deadline:["موعد التسليم","Deadline","Son tarih","Fecha límite","Échéance","Frist"],
 proposal:["تفاصيل العرض","Proposal","Teklif","Propuesta","Proposition","Angebot"],
 scope:["نطاق العمل","Scope","Kapsam","Alcance","Périmètre","Umfang"],
 attachment_url:["المرفق","Attachment","Ek","Adjunto","Pièce jointe","Anhang"],
 display_name:["الاسم","Name","Ad","Nombre","Nom","Name"],
 full_name:["الاسم الكامل","Full name","Tam ad","Nombre completo","Nom complet","Vollständiger Name"],
 account_type:["نوع الحساب","Account type","Hesap türü","Tipo de cuenta","Type de compte","Kontotyp"],
 account_status:["حالة الحساب","Account status","Hesap durumu","Estado de cuenta","État du compte","Kontostatus"],
 status:["الحالة","Status","Durum","Estado","Statut","Status"],
 created_at:["تاريخ الإنشاء","Created","Oluşturulma","Creación","Création","Erstellt"],
 submitted_at:["تاريخ التقديم","Submitted","Gönderilme","Enviado","Soumis","Eingereicht"],
 updated_at:["آخر تحديث","Last updated","Son güncelleme","Última actualización","Dernière mise à jour","Zuletzt aktualisiert"],
 decided_at:["تاريخ القرار","Decision date","Karar tarihi","Fecha de decisión","Date de décision","Entscheidungsdatum"],
 profiles:["صاحب الحساب","Account holder","Hesap sahibi","Titular","Titulaire","Kontoinhaber"],
 individual_profiles:["الملف المهني","Professional profile","Mesleki profil","Perfil profesional","Profil professionnel","Berufsprofil"],
 team_profiles:["بيانات الفريق","Team details","Ekip bilgileri","Datos del equipo","Détails de l’équipe","Teamdetails"],
 client_profiles:["بيانات العميل","Client details","Müşteri bilgileri","Datos del cliente","Détails du client","Kundendetails"],
 professional_title:["المسمى المهني","Professional title","Meslek","Título profesional","Titre professionnel","Berufsbezeichnung"],
 verification_status:["حالة التوثيق","Verification status","Doğrulama durumu","Estado de verificación","Statut de vérification","Verifizierungsstatus"],
 internal_notes:["ملاحظات داخلية","Internal notes","Dahili notlar","Notas internas","Notes internes","Interne Notizen"],
 decision_reason:["سبب القرار","Decision reason","Karar nedeni","Motivo de decisión","Motif de décision","Entscheidungsgrund"],
 appointments:["المواعيد","Appointments","Randevular","Citas","Rendez-vous","Termine"],
 starts_at:["بداية الموعد","Start","Başlangıç","Inicio","Début","Beginn"],
 ends_at:["نهاية الموعد","End","Bitiş","Fin","Fin","Ende"],
 title:["العنوان","Title","Başlık","Título","Titre","Titel"],
 description:["الوصف","Description","Açıklama","Descripción","Description","Beschreibung"],
 name:["الاسم","Name","Ad","Nombre","Nom","Name"],
 body:["المحتوى","Content","İçerik","Contenido","Contenu","Inhalt"],
 reason:["السبب","Reason","Neden","Motivo","Motif","Grund"],
 reasoning:["أسباب القرار","Decision reasoning","Karar gerekçesi","Justificación","Justification","Begründung"],
 locale:["اللغة","Language","Dil","Idioma","Langue","Sprache"],
 onboarding_complete:["اكتمال البيانات","Profile complete","Profil tamamlandı","Perfil completo","Profil complet","Profil vollständig"],
 company_name:["اسم الشركة","Company","Şirket","Empresa","Entreprise","Unternehmen"],
 country_code:["الدولة","Country","Ülke","País","Pays","Land"],
 currency:["العملة","Currency","Para birimi","Moneda","Devise","Währung"],
 permissions:["الصلاحيات","Permissions","İzinler","Permisos","Autorisations","Berechtigungen"],
 role_permissions:["صلاحيات الدور","Role permissions","Rol izinleri","Permisos del rol","Autorisations du rôle","Rollenberechtigungen"],
 value:["الإعدادات","Settings","Ayarlar","Configuración","Paramètres","Einstellungen"],
 key:["الإعداد","Setting","Ayar","Ajuste","Paramètre","Einstellung"],
 active:["مفعّل","Active","Etkin","Activo","Actif","Aktiv"],
 enabled:["مفعّل","Enabled","Etkin","Habilitado","Activé","Aktiviert"],
 public:["متاح للعامة","Public","Herkese açık","Público","Public","Öffentlich"],
 yes:["نعم","Yes","Evet","Sí","Oui","Ja"],
 no:["لا","No","Hayır","No","Non","Nein"],
 missing:["غير متوفر","Not provided","Belirtilmedi","No indicado","Non renseigné","Nicht angegeben"],
 record:["تفاصيل السجل","Record details","Kayıt bilgileri","Detalles del registro","Détails de l’enregistrement","Datensatzdetails"],
 individual:["فرد","Individual","Bireysel","Individual","Individuel","Einzelperson"],
 team:["فريق","Team","Ekip","Equipo","Équipe","Team"],
 client:["عميل","Client","Müşteri","Cliente","Client","Kunde"],
 suspended:["معلّق","Suspended","Askıya alındı","Suspendido","Suspendu","Gesperrt"],
 banned:["محظور","Banned","Engellendi","Bloqueado","Bloqué","Verboten"],
 requested:["طلب توثيق جديد","Verification requested","Doğrulama istendi","Verificación solicitada","Vérification demandée","Verifizierung beantragt"],
 under_review:["قيد المراجعة","Under review","İnceleniyor","En revisión","En cours d’examen","In Prüfung"],
 verified:["موثّق","Verified","Doğrulandı","Verificado","Vérifié","Verifiziert"],
 rejected:["مرفوض","Rejected","Reddedildi","Rechazado","Rejeté","Abgelehnt"],
 draft:["مسودة","Draft","Taslak","Borrador","Brouillon","Entwurf"],
 interview_required:["المقابلة مطلوبة","Interview required","Görüşme gerekli","Entrevista requerida","Entretien requis","Gespräch erforderlich"],
 changes_requested:["تعديلات مطلوبة","Changes requested","Değişiklik istendi","Cambios solicitados","Modifications demandées","Änderungen erforderlich"],
 addField:["إضافة حقل","Add field","Alan ekle","Añadir campo","Ajouter un champ","Feld hinzufügen"],
 fieldName:["اسم الحقل","Field name","Alan adı","Nombre del campo","Nom du champ","Feldname"],
 add:["إضافة","Add","Ekle","Añadir","Ajouter","Hinzufügen"],
 fieldType:["نوع القيمة","Value type","Değer türü","Tipo de valor","Type de valeur","Werttyp"],
 text:["نص","Text","Metin","Texto","Texte","Text"],
 number:["رقم","Number","Sayı","Número","Nombre","Zahl"],
 boolean:["تفعيل أو تعطيل","On or off","Açık veya kapalı","Activar o desactivar","Activer ou désactiver","Ein oder aus"],
 group:["مجموعة حقول","Field group","Alan grubu","Grupo de campos","Groupe de champs","Feldgruppe"],
 list:["قائمة","List","Liste","Lista","Liste","Liste"]
};
export function adminRecordLabel(locale:string,key:string){const index=languages.indexOf(isLocale(locale)?locale:"en");return words[key]?.[index]??key.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ").replaceAll("."," · ");}
