import {isLocale,type Locale} from "@/lib/i18n";

const en={
 title:"Verification appointments",intro:"Choose an in-person interview after submitting your verification request. GazaWorks staff review your documents and interview before deciding on verification.",
 statusTitle:"Verification status",request:"Request verification",requestSent:"Verification requested.",requestFailed:"Complete your profile and upload the required documents before requesting verification.",none:"No request submitted.",
 available:"Available interviews",myBookings:"My appointments",emptySlots:"No available slots. Please check again later.",emptyHistory:"No appointments booked yet.",book:"Book",booked:"Interview booked.",
 cancel:"Cancel appointment",confirmCancel:"Cancel this appointment? You can choose another available slot afterwards.",cancelled:"Appointment cancelled. You may book another slot.",loading:"Loading…",refresh:"Refresh",loadFailed:"Could not load appointments. Please try again.",
 save:"Save",saved:"Saved.",failed:"Could not save the change. Refresh and try again.",create:"Create slot",starts:"Starts",ends:"Ends",staff:"Assigned staff",unassigned:"Unassigned",assign:"Save staff assignment",reschedule:"Reschedule",
 internalNotes:"Internal staff notes",instructions:"Instructions visible to the applicant",saveNotes:"Save notes",block:"Block slot",open:"Make available",attend:"Mark attendance",complete:"Complete interview",noShow:"Mark absent",
 all:"All statuses",next:"Next",previous:"Previous",timeZone:"Input time zone",gazaTime:"Times shown in Gaza time (Asia/Gaza).",applicant:"Applicant",attendanceLabel:"Attendance",manage:"Manage appointment",decision:"Decision / requested changes",
 reviewOnly:"Completing an interview sends it for review. Verification requires a separate human decision.",
 conflict:"This staff member already has a slot at that time.",stale:"This appointment changed. Refresh before making another change.",invalidTime:"Choose a future start and a later end, with a maximum duration of 8 hours.",invalidStaff:"Choose an active verification staff member.",attendanceRequired:"Record attendance before completing the interview.",notStarted:"The interview has not started yet.",notFinished:"Wait until the appointment ends before marking an absence.",closed:"This appointment is closed.",forbidden:"You do not have permission for this action.",unavailable:"This slot is no longer available. Refresh to choose another."
};
type Copy=Record<keyof typeof en,string>;
const copy:Record<Locale,Copy>={en,
 ar:{
 title:"مواعيد التحقق",intro:"اختر مقابلة حضورية بعد إرسال طلب التحقق. يراجع فريق GazaWorks مستنداتك والمقابلة قبل اتخاذ قرار التحقق.",statusTitle:"حالة التحقق",request:"طلب التحقق",requestSent:"تم إرسال طلب التحقق.",requestFailed:"أكمل ملفك وارفع المستندات المطلوبة قبل طلب التحقق.",none:"لم يتم إرسال طلب بعد.",
 available:"المقابلات المتاحة",myBookings:"مواعيدي",emptySlots:"لا توجد مواعيد متاحة. تحقق مرة أخرى لاحقًا.",emptyHistory:"لم تحجز أي موعد بعد.",book:"حجز",booked:"تم حجز المقابلة.",cancel:"إلغاء الموعد",confirmCancel:"هل تريد إلغاء هذا الموعد؟ يمكنك اختيار موعد آخر متاح بعد الإلغاء.",cancelled:"تم إلغاء الموعد. يمكنك حجز موعد آخر.",loading:"جارٍ التحميل…",refresh:"تحديث",loadFailed:"تعذّر تحميل المواعيد. حاول مجددًا.",
 save:"حفظ",saved:"تم الحفظ.",failed:"تعذّر حفظ التغيير. حدّث الصفحة وحاول مجددًا.",create:"إنشاء موعد",starts:"البداية",ends:"النهاية",staff:"الموظف المسؤول",unassigned:"دون تعيين",assign:"حفظ تعيين الموظف",reschedule:"إعادة الجدولة",internalNotes:"ملاحظات داخلية للموظفين",instructions:"تعليمات تظهر لصاحب الطلب",saveNotes:"حفظ الملاحظات",block:"حجب الموعد",open:"إتاحة الموعد",attend:"تسجيل الحضور",complete:"إكمال المقابلة",noShow:"تسجيل الغياب",
 all:"كل الحالات",next:"التالي",previous:"السابق",timeZone:"المنطقة الزمنية للإدخال",gazaTime:"تُعرض المواعيد بتوقيت غزة (Asia/Gaza).",applicant:"صاحب الطلب",attendanceLabel:"الحضور",manage:"إدارة الموعد",decision:"القرار / التعديلات المطلوبة",reviewOnly:"إكمال المقابلة يحوّل الطلب للمراجعة. التحقق يحتاج قرارًا بشريًا منفصلًا.",
 conflict:"لدى هذا الموظف موعد آخر يتعارض مع الوقت المحدد.",stale:"تغيّر هذا الموعد. حدّث البيانات قبل إجراء تعديل جديد.",invalidTime:"اختر بداية مستقبلية ونهاية بعدها، بمدة لا تتجاوز 8 ساعات.",invalidStaff:"اختر موظف تحقق نشطًا.",attendanceRequired:"سجّل الحضور قبل إكمال المقابلة.",notStarted:"لم يبدأ وقت المقابلة بعد.",notFinished:"انتظر انتهاء الموعد قبل تسجيل الغياب.",closed:"هذا الموعد مغلق.",forbidden:"لا تملك صلاحية تنفيذ هذا الإجراء.",unavailable:"هذا الموعد لم يعد متاحًا. حدّث البيانات لاختيار غيره."
 },
 tr:{
 title:"Doğrulama randevuları",intro:"Doğrulama talebinizi gönderdikten sonra yüz yüze görüşme seçin. GazaWorks ekibi karar vermeden önce belgelerinizi ve görüşmenizi değerlendirir.",statusTitle:"Doğrulama durumu",request:"Doğrulama talep et",requestSent:"Doğrulama talebi gönderildi.",requestFailed:"Talep göndermeden önce profilinizi tamamlayın ve gerekli belgeleri yükleyin.",none:"Henüz talep gönderilmedi.",available:"Uygun görüşmeler",myBookings:"Randevularım",emptySlots:"Uygun randevu yok. Daha sonra tekrar kontrol edin.",emptyHistory:"Henüz randevu almadınız.",book:"Randevu al",booked:"Görüşme randevusu alındı.",cancel:"Randevuyu iptal et",confirmCancel:"Bu randevuyu iptal etmek istiyor musunuz? Sonrasında uygun başka bir saat seçebilirsiniz.",cancelled:"Randevu iptal edildi. Başka bir randevu alabilirsiniz.",loading:"Yükleniyor…",refresh:"Yenile",loadFailed:"Randevular yüklenemedi. Tekrar deneyin.",
 save:"Kaydet",saved:"Kaydedildi.",failed:"Değişiklik kaydedilemedi. Yenileyip tekrar deneyin.",create:"Randevu saati oluştur",starts:"Başlangıç",ends:"Bitiş",staff:"Atanan görevli",unassigned:"Atanmamış",assign:"Görevli atamasını kaydet",reschedule:"Yeniden planla",internalNotes:"Dahili görevli notları",instructions:"Başvuru sahibine gösterilen talimatlar",saveNotes:"Notları kaydet",block:"Saati kapat",open:"Uygun hale getir",attend:"Katılımı kaydet",complete:"Görüşmeyi tamamla",noShow:"Gelmedi olarak işaretle",
 all:"Tüm durumlar",next:"Sonraki",previous:"Önceki",timeZone:"Giriş saat dilimi",gazaTime:"Saatler Gazze saat diliminde gösterilir (Asia/Gaza).",applicant:"Başvuru sahibi",attendanceLabel:"Katılım",manage:"Randevuyu yönet",decision:"Karar / istenen değişiklikler",reviewOnly:"Görüşme tamamlandığında incelemeye gönderilir. Doğrulama için ayrı bir insan kararı gerekir.",
 conflict:"Bu görevlinin o saatte başka bir randevusu var.",stale:"Bu randevu değişti. İşlem yapmadan önce yenileyin.",invalidTime:"Gelecekte bir başlangıç ve daha sonra bir bitiş seçin; süre en fazla 8 saattir.",invalidStaff:"Aktif bir doğrulama görevlisi seçin.",attendanceRequired:"Görüşmeyi tamamlamadan önce katılımı kaydedin.",notStarted:"Görüşme saati henüz başlamadı.",notFinished:"Gelmedi olarak işaretlemek için randevunun bitmesini bekleyin.",closed:"Bu randevu kapandı.",forbidden:"Bu işlem için yetkiniz yok.",unavailable:"Bu saat artık uygun değil. Başka bir saat seçmek için yenileyin."
 },
 es:{
 title:"Citas de verificación",intro:"Elige una entrevista presencial después de enviar tu solicitud. El equipo de GazaWorks revisará tus documentos y la entrevista antes de decidir sobre la verificación.",statusTitle:"Estado de verificación",request:"Solicitar verificación",requestSent:"Solicitud enviada.",requestFailed:"Completa tu perfil y sube los documentos necesarios antes de solicitar la verificación.",none:"Aún no has enviado una solicitud.",available:"Entrevistas disponibles",myBookings:"Mis citas",emptySlots:"No hay horarios disponibles. Vuelve a consultar más tarde.",emptyHistory:"Aún no has reservado ninguna cita.",book:"Reservar",booked:"Entrevista reservada.",cancel:"Cancelar cita",confirmCancel:"¿Cancelar esta cita? Después podrás elegir otro horario disponible.",cancelled:"Cita cancelada. Puedes reservar otra.",loading:"Cargando…",refresh:"Actualizar",loadFailed:"No se pudieron cargar las citas. Inténtalo de nuevo.",
 save:"Guardar",saved:"Guardado.",failed:"No se pudo guardar el cambio. Actualiza e inténtalo de nuevo.",create:"Crear horario",starts:"Inicio",ends:"Fin",staff:"Personal asignado",unassigned:"Sin asignar",assign:"Guardar asignación",reschedule:"Reprogramar",internalNotes:"Notas internas del personal",instructions:"Instrucciones visibles para el solicitante",saveNotes:"Guardar notas",block:"Bloquear horario",open:"Habilitar horario",attend:"Registrar asistencia",complete:"Completar entrevista",noShow:"Marcar ausencia",
 all:"Todos los estados",next:"Siguiente",previous:"Anterior",timeZone:"Zona horaria de entrada",gazaTime:"Los horarios se muestran en la zona horaria de Gaza (Asia/Gaza).",applicant:"Solicitante",attendanceLabel:"Asistencia",manage:"Gestionar cita",decision:"Decisión / cambios solicitados",reviewOnly:"Completar una entrevista la envía a revisión. La verificación requiere una decisión humana independiente.",
 conflict:"Esta persona ya tiene un horario que coincide.",stale:"Esta cita ha cambiado. Actualiza antes de realizar otro cambio.",invalidTime:"Elige un inicio futuro y un fin posterior, con una duración máxima de 8 horas.",invalidStaff:"Elige un miembro activo del equipo de verificación.",attendanceRequired:"Registra la asistencia antes de completar la entrevista.",notStarted:"La entrevista aún no ha comenzado.",notFinished:"Espera al final de la cita para marcar una ausencia.",closed:"Esta cita está cerrada.",forbidden:"No tienes permiso para esta acción.",unavailable:"Este horario ya no está disponible. Actualiza para elegir otro."
 },
 fr:{
 title:"Rendez-vous de vérification",intro:"Choisissez un entretien en personne après avoir envoyé votre demande. L'équipe GazaWorks examine vos documents et votre entretien avant de décider de la vérification.",statusTitle:"Statut de vérification",request:"Demander la vérification",requestSent:"Demande envoyée.",requestFailed:"Complétez votre profil et téléversez les documents requis avant de demander la vérification.",none:"Aucune demande envoyée.",available:"Entretiens disponibles",myBookings:"Mes rendez-vous",emptySlots:"Aucun créneau disponible. Veuillez réessayer plus tard.",emptyHistory:"Aucun rendez-vous réservé.",book:"Réserver",booked:"Entretien réservé.",cancel:"Annuler le rendez-vous",confirmCancel:"Annuler ce rendez-vous ? Vous pourrez ensuite choisir un autre créneau disponible.",cancelled:"Rendez-vous annulé. Vous pouvez en réserver un autre.",loading:"Chargement…",refresh:"Actualiser",loadFailed:"Impossible de charger les rendez-vous. Réessayez.",
 save:"Enregistrer",saved:"Enregistré.",failed:"Impossible d'enregistrer la modification. Actualisez et réessayez.",create:"Créer un créneau",starts:"Début",ends:"Fin",staff:"Personnel affecté",unassigned:"Non affecté",assign:"Enregistrer l'affectation",reschedule:"Reprogrammer",internalNotes:"Notes internes du personnel",instructions:"Instructions visibles par le demandeur",saveNotes:"Enregistrer les notes",block:"Bloquer le créneau",open:"Rendre disponible",attend:"Enregistrer la présence",complete:"Terminer l'entretien",noShow:"Signaler une absence",
 all:"Tous les statuts",next:"Suivant",previous:"Précédent",timeZone:"Fuseau horaire de saisie",gazaTime:"Les horaires sont affichés à l'heure de Gaza (Asia/Gaza).",applicant:"Demandeur",attendanceLabel:"Présence",manage:"Gérer le rendez-vous",decision:"Décision / modifications demandées",reviewOnly:"Terminer un entretien l'envoie pour examen. La vérification exige une décision humaine distincte.",
 conflict:"Ce membre du personnel a déjà un créneau à cet horaire.",stale:"Ce rendez-vous a changé. Actualisez avant toute nouvelle modification.",invalidTime:"Choisissez un début futur et une fin ultérieure, pour une durée maximale de 8 heures.",invalidStaff:"Choisissez un membre actif de l'équipe de vérification.",attendanceRequired:"Enregistrez la présence avant de terminer l'entretien.",notStarted:"L'entretien n'a pas encore commencé.",notFinished:"Attendez la fin du rendez-vous avant de signaler une absence.",closed:"Ce rendez-vous est clos.",forbidden:"Vous n'avez pas l'autorisation nécessaire.",unavailable:"Ce créneau n'est plus disponible. Actualisez pour en choisir un autre."
 },
 de:{
 title:"Verifizierungstermine",intro:"Wählen Sie nach Ihrer Verifizierungsanfrage ein persönliches Gespräch. Das GazaWorks-Team prüft Ihre Unterlagen und das Gespräch, bevor es über die Verifizierung entscheidet.",statusTitle:"Verifizierungsstatus",request:"Verifizierung beantragen",requestSent:"Anfrage gesendet.",requestFailed:"Vervollständigen Sie Ihr Profil und laden Sie die erforderlichen Dokumente vor der Anfrage hoch.",none:"Noch keine Anfrage gesendet.",available:"Verfügbare Gesprächstermine",myBookings:"Meine Termine",emptySlots:"Keine freien Termine. Bitte später erneut prüfen.",emptyHistory:"Noch keine Termine gebucht.",book:"Buchen",booked:"Gespräch gebucht.",cancel:"Termin absagen",confirmCancel:"Diesen Termin absagen? Danach können Sie einen anderen freien Termin wählen.",cancelled:"Termin abgesagt. Sie können einen anderen buchen.",loading:"Wird geladen…",refresh:"Aktualisieren",loadFailed:"Termine konnten nicht geladen werden. Bitte erneut versuchen.",
 save:"Speichern",saved:"Gespeichert.",failed:"Änderung konnte nicht gespeichert werden. Aktualisieren und erneut versuchen.",create:"Zeitfenster erstellen",starts:"Beginn",ends:"Ende",staff:"Zuständiges Teammitglied",unassigned:"Nicht zugewiesen",assign:"Zuweisung speichern",reschedule:"Termin verschieben",internalNotes:"Interne Teamnotizen",instructions:"Für Antragstellende sichtbare Hinweise",saveNotes:"Notizen speichern",block:"Zeitfenster sperren",open:"Zeitfenster freigeben",attend:"Anwesenheit erfassen",complete:"Gespräch abschließen",noShow:"Abwesenheit erfassen",
 all:"Alle Status",next:"Weiter",previous:"Zurück",timeZone:"Zeitzone der Eingabe",gazaTime:"Termine werden in der Zeitzone von Gaza angezeigt (Asia/Gaza).",applicant:"Antragstellende Person",attendanceLabel:"Anwesenheit",manage:"Termin verwalten",decision:"Entscheidung / angeforderte Änderungen",reviewOnly:"Ein abgeschlossenes Gespräch wird zur Prüfung vorgelegt. Die Verifizierung erfordert eine gesonderte menschliche Entscheidung.",
 conflict:"Dieses Teammitglied hat zu dieser Zeit bereits einen Termin.",stale:"Dieser Termin wurde geändert. Vor weiteren Änderungen bitte aktualisieren.",invalidTime:"Wählen Sie einen zukünftigen Beginn und ein späteres Ende, mit höchstens 8 Stunden Dauer.",invalidStaff:"Wählen Sie ein aktives Mitglied des Verifizierungsteams.",attendanceRequired:"Erfassen Sie die Anwesenheit vor Abschluss des Gesprächs.",notStarted:"Das Gespräch hat noch nicht begonnen.",notFinished:"Warten Sie bis zum Terminende, bevor Sie eine Abwesenheit erfassen.",closed:"Dieser Termin ist geschlossen.",forbidden:"Sie haben keine Berechtigung für diese Aktion.",unavailable:"Dieses Zeitfenster ist nicht mehr verfügbar. Aktualisieren Sie die Auswahl."
 }
};

const states:Record<Locale,Record<string,string>>={
 en:{available:"Available",booked:"Booked",blocked:"Blocked",cancelled:"Cancelled",completed:"Completed",no_show:"Absent",attended:"Attended",absent:"Absent",pending:"Pending review",requested:"Requested",under_review:"Under review",interview_required:"Interview required",interview_scheduled:"Interview scheduled",verified:"Verified",changes_requested:"Changes requested",rejected:"Rejected",suspended:"Suspended"},
 ar:{available:"متاح",booked:"محجوز",blocked:"محجوب",cancelled:"ملغى",completed:"مكتمل",no_show:"غياب",attended:"حضر",absent:"غائب",pending:"بانتظار المراجعة",requested:"تم الطلب",under_review:"قيد المراجعة",interview_required:"مقابلة مطلوبة",interview_scheduled:"المقابلة مجدولة",verified:"موثّق",changes_requested:"تعديلات مطلوبة",rejected:"مرفوض",suspended:"موقوف"},
 tr:{available:"Uygun",booked:"Rezerve",blocked:"Kapalı",cancelled:"İptal edildi",completed:"Tamamlandı",no_show:"Gelmedi",attended:"Katıldı",absent:"Katılmadı",pending:"İnceleme bekleniyor",requested:"Talep edildi",under_review:"İnceleniyor",interview_required:"Görüşme gerekli",interview_scheduled:"Görüşme planlandı",verified:"Doğrulandı",changes_requested:"Değişiklik istendi",rejected:"Reddedildi",suspended:"Askıya alındı"},
 es:{available:"Disponible",booked:"Reservada",blocked:"Bloqueada",cancelled:"Cancelada",completed:"Completada",no_show:"Ausente",attended:"Asistió",absent:"Ausente",pending:"Pendiente de revisión",requested:"Solicitada",under_review:"En revisión",interview_required:"Entrevista necesaria",interview_scheduled:"Entrevista programada",verified:"Verificado",changes_requested:"Cambios solicitados",rejected:"Rechazado",suspended:"Suspendido"},
 fr:{available:"Disponible",booked:"Réservé",blocked:"Bloqué",cancelled:"Annulé",completed:"Terminé",no_show:"Absent",attended:"Présent",absent:"Absent",pending:"En attente d'examen",requested:"Demandé",under_review:"En cours d'examen",interview_required:"Entretien requis",interview_scheduled:"Entretien prévu",verified:"Vérifié",changes_requested:"Modifications demandées",rejected:"Refusé",suspended:"Suspendu"},
 de:{available:"Verfügbar",booked:"Gebucht",blocked:"Gesperrt",cancelled:"Abgesagt",completed:"Abgeschlossen",no_show:"Abwesend",attended:"Anwesend",absent:"Abwesend",pending:"Prüfung ausstehend",requested:"Beantragt",under_review:"In Prüfung",interview_required:"Gespräch erforderlich",interview_scheduled:"Gespräch geplant",verified:"Verifiziert",changes_requested:"Änderungen erforderlich",rejected:"Abgelehnt",suspended:"Gesperrt"}
};
export function appointmentCopy(locale:string){return copy[isLocale(locale)?locale:"en"];}
export function appointmentState(locale:string,state:string){return states[isLocale(locale)?locale:"en"][state]??state.replaceAll("_"," ");}
export function appointmentError(locale:string,error:unknown){
 const c=appointmentCopy(locale);
 const errors:Record<string,string>={staff_time_conflict:c.conflict,stale_appointment:c.stale,invalid_slot_time:c.invalidTime,invalid_staff:c.invalidStaff,assigned_staff_required:c.invalidStaff,attendance_required:c.attendanceRequired,interview_not_started:c.notStarted,interview_not_finished:c.notFinished,appointment_closed:c.closed,forbidden:c.forbidden,self_interview_forbidden:c.forbidden,inactive_account:c.forbidden,slot_unavailable:c.unavailable,verification_not_bookable:c.unavailable,complete_profile_first:c.requestFailed,document_required:c.requestFailed};
 return typeof error==="string"?errors[error]??c.failed:c.failed;
}
export function appointmentTime(locale:string,value:string){return new Intl.DateTimeFormat(isLocale(locale)?locale:"en",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Gaza"}).format(new Date(value));}
