import {isLocale,type Locale} from "./i18n";
import {cvFieldKeys} from "@/domain/cv";
const en={title:"CV builder",intro:"Build your CV step by step. Review any AI suggestion before using it. Your saved CV stays private.",previous:"Previous",next:"Next",classic:"Clean classic",modern:"Modern",template:"Template",language:"CV language",improve:"Improve and translate with AI",print:"Save / Print PDF",printHint:"Choose Save as PDF in the print dialog.",save:"Save private CV",saved:"CV saved privately.",busy:"Working…",error:"The request could not be completed. Your current draft is still here.",unavailable:"AI is unavailable. You can edit your CV manually and save or print it.",review:"Review this suggestion. You can edit every field after applying it.",apply:"Use this suggestion",discard:"Keep my current wording",empty:"Fill in the interview fields to build your CV.",loadError:"Could not load your saved CV. Reload the page to try again."};
type Copy=typeof en;
const copy:Record<Locale,Copy>={en,
 ar:{title:"منشئ السيرة الذاتية",intro:"أنشئ سيرتك خطوة بخطوة. راجع اقتراح الذكاء الاصطناعي قبل استخدامه. تبقى السيرة المحفوظة خاصة بك.",previous:"السابق",next:"التالي",classic:"كلاسيكي بسيط",modern:"حديث",template:"القالب",language:"لغة السيرة",improve:"تحسين وترجمة بالذكاء الاصطناعي",print:"حفظ / طباعة PDF",printHint:"اختر «حفظ كملف PDF» في نافذة الطباعة.",save:"حفظ السيرة بشكل خاص",saved:"حُفظت السيرة بشكل خاص.",busy:"جارٍ العمل…",error:"تعذّر إكمال الطلب. مسودتك الحالية ما زالت هنا.",unavailable:"الذكاء الاصطناعي غير متاح. يمكنك تعديل السيرة يدويًا وحفظها أو طباعتها.",review:"راجع الاقتراح. تستطيع تعديل كل حقل بعد تطبيقه.",apply:"استخدام هذا الاقتراح",discard:"الاحتفاظ بصياغتي الحالية",empty:"أجب عن أسئلة المقابلة لبناء سيرتك الذاتية.",loadError:"تعذّر تحميل سيرتك المحفوظة. أعد تحميل الصفحة للمحاولة مجددًا."},
 tr:{title:"Özgeçmiş oluşturucu",intro:"Özgeçmişinizi adım adım oluşturun. Yapay zekâ önerisini kullanmadan önce inceleyin. Kaydedilen özgeçmişiniz gizli kalır.",previous:"Önceki",next:"Sonraki",classic:"Sade klasik",modern:"Modern",template:"Şablon",language:"Özgeçmiş dili",improve:"Yapay zekâ ile iyileştir ve çevir",print:"PDF kaydet / yazdır",printHint:"Yazdırma penceresinde PDF olarak kaydet seçeneğini kullanın.",save:"Özel özgeçmişi kaydet",saved:"Özgeçmiş gizli olarak kaydedildi.",busy:"İşleniyor…",error:"İşlem tamamlanamadı. Taslağınız burada duruyor.",unavailable:"Yapay zekâ kullanılamıyor. Özgeçmişinizi elle düzenleyebilir, kaydedebilir veya yazdırabilirsiniz.",review:"Bu öneriyi inceleyin. Uyguladıktan sonra her alanı düzenleyebilirsiniz.",apply:"Bu öneriyi kullan",discard:"Mevcut ifadelerimi koru",empty:"Özgeçmişinizi oluşturmak için alanları doldurun.",loadError:"Kayıtlı özgeçmiş yüklenemedi. Yeniden denemek için sayfayı yenileyin."},
 es:{title:"Creador de CV",intro:"Crea tu CV paso a paso. Revisa las sugerencias de IA antes de usarlas. Tu CV guardado permanece privado.",previous:"Anterior",next:"Siguiente",classic:"Clásico sencillo",modern:"Moderno",template:"Plantilla",language:"Idioma del CV",improve:"Mejorar y traducir con IA",print:"Guardar / imprimir PDF",printHint:"Elige Guardar como PDF en la ventana de impresión.",save:"Guardar CV privado",saved:"CV guardado de forma privada.",busy:"Procesando…",error:"No se pudo completar la solicitud. Tu borrador sigue aquí.",unavailable:"La IA no está disponible. Puedes editar, guardar o imprimir tu CV manualmente.",review:"Revisa esta sugerencia. Puedes editar cada campo después de aplicarla.",apply:"Usar esta sugerencia",discard:"Conservar mi redacción",empty:"Completa los campos para crear tu CV.",loadError:"No se pudo cargar tu CV guardado. Recarga la página para volver a intentarlo."},
 fr:{title:"Créateur de CV",intro:"Créez votre CV étape par étape. Vérifiez toute suggestion de l’IA avant de l’utiliser. Votre CV enregistré reste privé.",previous:"Précédent",next:"Suivant",classic:"Classique épuré",modern:"Moderne",template:"Modèle",language:"Langue du CV",improve:"Améliorer et traduire avec l’IA",print:"Enregistrer / imprimer en PDF",printHint:"Choisissez Enregistrer au format PDF dans la fenêtre d’impression.",save:"Enregistrer le CV privé",saved:"CV enregistré en privé.",busy:"Traitement…",error:"La demande n’a pas pu être traitée. Votre brouillon est toujours ici.",unavailable:"L’IA est indisponible. Vous pouvez modifier, enregistrer ou imprimer votre CV manuellement.",review:"Vérifiez cette suggestion. Chaque champ reste modifiable après son application.",apply:"Utiliser cette suggestion",discard:"Conserver ma formulation",empty:"Remplissez les champs pour créer votre CV.",loadError:"Impossible de charger votre CV enregistré. Actualisez la page pour réessayer."},
 de:{title:"Lebenslauf erstellen",intro:"Erstellen Sie Ihren Lebenslauf Schritt für Schritt. Prüfen Sie KI-Vorschläge vor der Verwendung. Ihr gespeicherter Lebenslauf bleibt privat.",previous:"Zurück",next:"Weiter",classic:"Schlicht klassisch",modern:"Modern",template:"Vorlage",language:"Sprache des Lebenslaufs",improve:"Mit KI verbessern und übersetzen",print:"PDF speichern / drucken",printHint:"Wählen Sie im Druckdialog Als PDF speichern.",save:"Privaten Lebenslauf speichern",saved:"Lebenslauf privat gespeichert.",busy:"Wird bearbeitet…",error:"Die Anfrage konnte nicht abgeschlossen werden. Ihr Entwurf bleibt erhalten.",unavailable:"KI ist nicht verfügbar. Sie können Ihren Lebenslauf manuell bearbeiten, speichern oder drucken.",review:"Prüfen Sie diesen Vorschlag. Alle Felder können nach der Übernahme bearbeitet werden.",apply:"Diesen Vorschlag verwenden",discard:"Meine Formulierung behalten",empty:"Füllen Sie die Felder aus, um Ihren Lebenslauf zu erstellen.",loadError:"Ihr gespeicherter Lebenslauf konnte nicht geladen werden. Laden Sie die Seite erneut."}};
const fields:Record<Locale,string[]>={
 en:["Full name","Professional title","Summary","Experience: roles, organizations, dates and results","Education","Projects","Skills","Software and tools","Languages and proficiency","Training","Certifications","Achievements","Career goals"],
 ar:["الاسم الكامل","المسمى المهني","نبذة مهنية","الخبرة: الأدوار والجهات والتواريخ والنتائج","التعليم","المشاريع","المهارات","البرامج والأدوات","اللغات ومستوياتها","التدريب","الشهادات المهنية","الإنجازات","الأهداف المهنية"],
 tr:["Tam ad","Mesleki unvan","Özet","Deneyim: roller, kuruluşlar, tarihler ve sonuçlar","Eğitim","Projeler","Beceriler","Yazılım ve araçlar","Diller ve yeterlilik","Eğitim programları","Sertifikalar","Başarılar","Kariyer hedefleri"],
 es:["Nombre completo","Título profesional","Resumen","Experiencia: cargos, organizaciones, fechas y resultados","Educación","Proyectos","Habilidades","Programas y herramientas","Idiomas y nivel","Formación","Certificaciones","Logros","Objetivos profesionales"],
 fr:["Nom complet","Titre professionnel","Résumé","Expérience : fonctions, organisations, dates et résultats","Formation","Projets","Compétences","Logiciels et outils","Langues et niveaux","Formations complémentaires","Certifications","Réalisations","Objectifs professionnels"],
 de:["Vollständiger Name","Berufsbezeichnung","Profil","Erfahrung: Rollen, Unternehmen, Zeiträume und Ergebnisse","Ausbildung","Projekte","Fähigkeiten","Software und Werkzeuge","Sprachen und Kenntnisse","Weiterbildung","Zertifikate","Erfolge","Berufliche Ziele"]};
export function cvCopy(locale:string){const l=isLocale(locale)?locale:"en";return{...copy[l],fields:Object.fromEntries(cvFieldKeys.map((key,i)=>[key,fields[l][i]]))}}
