import {isLocale,type Locale} from "@/lib/i18n";

export type DashboardPageKey="directHire"|"disputes"|"favorites"|"messages"|"notifications"|"offers"|"portfolio"|"profile"|"projects"|"reviews"|"security"|"team"|"workRequests";
type PageCopy={title:string;description:string;badge?:string};

const copy:Record<Locale,Record<DashboardPageKey,PageCopy>>={
 en:{
  directHire:{title:"Direct work requests",description:"Manage private direct-hire requests sent or received inside GazaWorks."},
  disputes:{title:"Disputes & appeals",description:"Submit evidence and track human administrative decisions. AI never decides disputes."},
  favorites:{title:"Saved talent",description:"Keep a shortlist of verified professionals and teams for quick access."},
  messages:{title:"Messages",description:"Keep text, files and voice messages inside GazaWorks for protection and accountability."},
  notifications:{title:"Notifications",description:"Track account, project, payment and verification notices in one organized feed."},
  offers:{title:"Offers",description:"Offers are private; professionals cannot see competitors’ prices or proposals."},
  portfolio:{title:"Portfolio",description:"Host your work inside GazaWorks with project details, images, videos and skills."},
  profile:{badge:"Account setup",title:"Professional profile",description:"Build the profile GazaWorks clients and verification staff will use. Private contact and legal information remain hidden from the public marketplace."},
  projects:{title:"Projects",description:"Manage agreements, funding, files, delivery and review from one place."},
  reviews:{title:"Reviews",description:"Mutual reviews unlock after project completion and finalized dispute handling."},
  security:{title:"Security & login history",description:"Review recent sign-ins and security signals for your account."},
  team:{badge:"Team account",title:"Team members",description:"Add team members, roles, skills and control how each person appears to authenticated clients."},
  workRequests:{badge:"Clients",title:"Work requests",description:"Create a professional engagement for verified GazaWorks talent or keep it private to invited professionals."},
 },
 ar:{
  directHire:{title:"طلبات العمل المباشرة",description:"تابع طلبات التوظيف الخاصة المرسلة أو المستلمة، واقبلها أو ارفضها من داخل GazaWorks."},
  disputes:{title:"النزاعات والاستئناف",description:"قدّم الأدلة وتابع قرارات الإدارة البشرية. الذكاء الاصطناعي لا يقرر النزاعات."},
  favorites:{title:"المواهب المحفوظة",description:"احتفظ بقائمة مختصرة من المحترفين والفرق الموثقة للعودة إليها سريعًا."},
  messages:{title:"الرسائل",description:"أبقِ التواصل والملفات والرسائل الصوتية داخل GazaWorks للحماية والمساءلة."},
  notifications:{title:"الإشعارات",description:"تابع إشعارات الحساب والمشاريع والمدفوعات والتحقق في مكان منظم."},
  offers:{title:"العروض",description:"العروض خاصة؛ لا يرى المحترفون أسعار المنافسين أو تفاصيل عروضهم."},
  portfolio:{title:"معرض الأعمال",description:"اعرض مشاريعك داخل GazaWorks وأضف الصور والفيديوهات والمهارات المستخدمة."},
  profile:{badge:"إعداد الحساب",title:"الملف المهني",description:"أنشئ الملف الذي سيعتمد عليه عملاء GazaWorks وفريق التحقق. تبقى بيانات الاتصال والمعلومات القانونية الخاصة مخفية عن السوق العام."},
  projects:{title:"المشاريع",description:"أدر الاتفاقيات والتمويل والملفات والتسليم والمراجعات من مكان واحد."},
  reviews:{title:"التقييمات",description:"التقييمات المتبادلة متاحة بعد اكتمال المشروع وتسوية أي نزاع."},
  security:{title:"الأمان وسجل الدخول",description:"راجع أحدث عمليات الدخول والتنبيهات الأمنية المرتبطة بحسابك."},
  team:{badge:"حساب فريق",title:"أعضاء الفريق",description:"أضف أعضاء الفريق وحدد دور كل شخص ومهاراته وطريقة ظهوره للعملاء المسجلين."},
  workRequests:{badge:"للعملاء",title:"طلبات العمل",description:"أنشئ طلبًا احترافيًا للمواهب الموثقة أو اجعله للدعوات الخاصة فقط."},
 },
 tr:{
  directHire:{title:"Doğrudan iş talepleri",description:"GazaWorks içinde gönderilen veya alınan özel işe alım taleplerini yönetin."},
  disputes:{title:"Uyuşmazlıklar ve itirazlar",description:"Kanıt sunun ve insan yöneticilerin kararlarını takip edin. Yapay zekâ uyuşmazlıkları karara bağlamaz."},
  favorites:{title:"Kaydedilen yetenekler",description:"Hızlı erişim için doğrulanmış profesyonel ve ekiplerden oluşan kısa bir liste tutun."},
  messages:{title:"Mesajlar",description:"Koruma ve hesap verebilirlik için metinleri, dosyaları ve sesli mesajları GazaWorks içinde tutun."},
  notifications:{title:"Bildirimler",description:"Hesap, proje, ödeme ve doğrulama bildirimlerini düzenli bir akışta takip edin."},
  offers:{title:"Teklifler",description:"Teklifler özeldir; profesyoneller rakiplerin fiyatlarını veya teklif ayrıntılarını göremez."},
  portfolio:{title:"Portföy",description:"Proje ayrıntıları, görseller, videolar ve becerilerle çalışmalarınızı GazaWorks içinde sergileyin."},
  profile:{badge:"Hesap kurulumu",title:"Profesyonel profil",description:"GazaWorks müşterilerinin ve doğrulama ekibinin kullanacağı profili oluşturun. Özel iletişim ve yasal bilgiler herkese açık pazaryerinde gizli kalır."},
  projects:{title:"Projeler",description:"Sözleşmeleri, finansmanı, dosyaları, teslimatı ve incelemeyi tek bir yerden yönetin."},
  reviews:{title:"Değerlendirmeler",description:"Karşılıklı değerlendirmeler proje tamamlandıktan ve tüm uyuşmazlıklar sonuçlandıktan sonra açılır."},
  security:{title:"Güvenlik ve giriş geçmişi",description:"Hesabınızdaki son girişleri ve güvenlik sinyallerini inceleyin."},
  team:{badge:"Ekip hesabı",title:"Ekip üyeleri",description:"Ekip üyeleri, roller ve beceriler ekleyin; her kişinin doğrulanmış müşterilere nasıl görüneceğini belirleyin."},
  workRequests:{badge:"Müşteriler",title:"İş talepleri",description:"Doğrulanmış GazaWorks yetenekleri için profesyonel bir iş talebi oluşturun veya yalnızca davet edilenlere açık tutun."},
 },
 es:{
  directHire:{title:"Solicitudes directas de trabajo",description:"Gestiona las solicitudes privadas de contratación directa enviadas o recibidas dentro de GazaWorks."},
  disputes:{title:"Disputas y apelaciones",description:"Presenta pruebas y sigue las decisiones administrativas humanas. La IA nunca decide disputas."},
  favorites:{title:"Talento guardado",description:"Mantén una lista breve de profesionales y equipos verificados para acceder rápidamente."},
  messages:{title:"Mensajes",description:"Mantén textos, archivos y mensajes de voz dentro de GazaWorks para proteger a ambas partes."},
  notifications:{title:"Notificaciones",description:"Sigue los avisos de cuenta, proyectos, pagos y verificación en un solo lugar."},
  offers:{title:"Ofertas",description:"Las ofertas son privadas; los profesionales no pueden ver los precios ni las propuestas de sus competidores."},
  portfolio:{title:"Portafolio",description:"Muestra tu trabajo dentro de GazaWorks con detalles, imágenes, vídeos y habilidades utilizadas."},
  profile:{badge:"Configuración de la cuenta",title:"Perfil profesional",description:"Crea el perfil que usarán los clientes y el equipo de verificación de GazaWorks. Los datos privados de contacto y la información legal permanecen ocultos en el mercado público."},
  projects:{title:"Proyectos",description:"Gestiona acuerdos, financiación, archivos, entregas y revisiones desde un solo lugar."},
  reviews:{title:"Valoraciones",description:"Las valoraciones mutuas se habilitan al completar el proyecto y cerrar cualquier disputa."},
  security:{title:"Seguridad e historial de acceso",description:"Revisa los accesos recientes y las señales de seguridad de tu cuenta."},
  team:{badge:"Cuenta de equipo",title:"Miembros del equipo",description:"Añade miembros, roles y habilidades, y controla cómo aparece cada persona ante los clientes autenticados."},
  workRequests:{badge:"Clientes",title:"Solicitudes de trabajo",description:"Crea una solicitud profesional para talento verificado de GazaWorks o mantenla privada para personas invitadas."},
 },
 fr:{
  directHire:{title:"Demandes de travail directes",description:"Gérez les demandes privées d’embauche directe envoyées ou reçues dans GazaWorks."},
  disputes:{title:"Litiges et appels",description:"Présentez des preuves et suivez les décisions prises par l’administration. L’IA ne tranche jamais les litiges."},
  favorites:{title:"Talents enregistrés",description:"Conservez une liste de professionnels et d’équipes vérifiés pour y accéder rapidement."},
  messages:{title:"Messages",description:"Gardez les textes, fichiers et messages vocaux dans GazaWorks pour protéger les deux parties."},
  notifications:{title:"Notifications",description:"Suivez les avis liés au compte, aux projets, aux paiements et à la vérification dans un flux organisé."},
  offers:{title:"Offres",description:"Les offres sont privées ; les professionnels ne voient ni les prix ni les propositions de leurs concurrents."},
  portfolio:{title:"Portfolio",description:"Présentez vos travaux dans GazaWorks avec les détails, images, vidéos et compétences utilisées."},
  profile:{badge:"Configuration du compte",title:"Profil professionnel",description:"Créez le profil utilisé par les clients et l’équipe de vérification de GazaWorks. Les coordonnées privées et les informations juridiques restent masquées sur la place de marché publique."},
  projects:{title:"Projets",description:"Gérez les accords, le financement, les fichiers, la livraison et la validation depuis un seul endroit."},
  reviews:{title:"Évaluations",description:"Les évaluations mutuelles sont accessibles après la fin du projet et le règlement définitif de tout litige."},
  security:{title:"Sécurité et historique de connexion",description:"Consultez les connexions récentes et les signaux de sécurité associés à votre compte."},
  team:{badge:"Compte d’équipe",title:"Membres de l’équipe",description:"Ajoutez des membres, des rôles et des compétences, puis contrôlez leur affichage auprès des clients connectés."},
  workRequests:{badge:"Clients",title:"Demandes de travail",description:"Créez une demande professionnelle pour les talents vérifiés de GazaWorks ou réservez-la aux personnes invitées."},
 },
 de:{
  directHire:{title:"Direkte Arbeitsanfragen",description:"Verwalten Sie private Direktanfragen, die innerhalb von GazaWorks gesendet oder empfangen wurden."},
  disputes:{title:"Streitfälle und Einsprüche",description:"Reichen Sie Nachweise ein und verfolgen Sie menschliche Verwaltungsentscheidungen. KI entscheidet niemals über Streitfälle."},
  favorites:{title:"Gespeicherte Talente",description:"Speichern Sie eine Auswahlliste verifizierter Fachkräfte und Teams für den schnellen Zugriff."},
  messages:{title:"Nachrichten",description:"Bewahren Sie Texte, Dateien und Sprachnachrichten zum Schutz beider Seiten innerhalb von GazaWorks auf."},
  notifications:{title:"Benachrichtigungen",description:"Verfolgen Sie Konto-, Projekt-, Zahlungs- und Verifizierungsmitteilungen in einer geordneten Übersicht."},
  offers:{title:"Angebote",description:"Angebote sind privat; Fachkräfte können weder Preise noch Vorschläge ihrer Mitbewerber sehen."},
  portfolio:{title:"Portfolio",description:"Präsentieren Sie Ihre Arbeit in GazaWorks mit Projektdetails, Bildern, Videos und eingesetzten Fähigkeiten."},
  profile:{badge:"Kontoeinrichtung",title:"Berufliches Profil",description:"Erstellen Sie das Profil, das GazaWorks-Kunden und das Verifizierungsteam verwenden. Private Kontakt- und Rechtsangaben bleiben auf dem öffentlichen Marktplatz verborgen."},
  projects:{title:"Projekte",description:"Verwalten Sie Vereinbarungen, Finanzierung, Dateien, Lieferung und Prüfung an einem Ort."},
  reviews:{title:"Bewertungen",description:"Gegenseitige Bewertungen werden nach Projektabschluss und endgültiger Klärung aller Streitfälle freigeschaltet."},
  security:{title:"Sicherheit und Anmeldeverlauf",description:"Prüfen Sie die letzten Anmeldungen und Sicherheitssignale Ihres Kontos."},
  team:{badge:"Teamkonto",title:"Teammitglieder",description:"Fügen Sie Mitglieder, Rollen und Fähigkeiten hinzu und steuern Sie, wie jede Person angemeldeten Kunden angezeigt wird."},
  workRequests:{badge:"Kunden",title:"Arbeitsanfragen",description:"Erstellen Sie eine professionelle Anfrage für verifizierte GazaWorks-Talente oder beschränken Sie sie auf eingeladene Fachkräfte."},
 },
};

export function dashboardPageCopy(locale:string,key:DashboardPageKey):PageCopy{
 return copy[isLocale(locale)?locale:"en"][key];
}
