import {isLocale,type Locale} from "@/lib/i18n";

type Copy={accepted:string;declined:string;withdrawn:string;failed:string;client:string;talent:string;delivery:string;workRequest:string;accept:string;decline:string;withdraw:string;empty:string;statuses:Record<string,string>};
const copy:Record<Locale,Copy>={
 en:{accepted:"Request accepted and converted to a private work request.",declined:"Request declined.",withdrawn:"Request withdrawn.",failed:"Action failed.",client:"Client",talent:"Professional / team",delivery:"Desired delivery",workRequest:"Work request",accept:"Accept & prepare offer",decline:"Decline",withdraw:"Withdraw request",empty:"No direct work requests yet.",statuses:{sent:"Sent",accepted:"Accepted",declined:"Declined",withdrawn:"Withdrawn",converted:"Converted to work request"}},
 ar:{accepted:"تم قبول الطلب وتحويله إلى طلب عمل خاص.",declined:"تم رفض الطلب.",withdrawn:"تم سحب الطلب.",failed:"تعذّر تنفيذ الإجراء.",client:"العميل",talent:"المحترف / الفريق",delivery:"موعد التسليم المطلوب",workRequest:"طلب العمل",accept:"قبول وتجهيز العرض",decline:"رفض",withdraw:"سحب الطلب",empty:"لا توجد طلبات عمل مباشرة حاليًا.",statuses:{sent:"مُرسل",accepted:"مقبول",declined:"مرفوض",withdrawn:"مسحوب",converted:"تم التحويل إلى طلب عمل"}},
 tr:{accepted:"Talep kabul edildi ve özel bir iş talebine dönüştürüldü.",declined:"Talep reddedildi.",withdrawn:"Talep geri çekildi.",failed:"İşlem gerçekleştirilemedi.",client:"Müşteri",talent:"Profesyonel / ekip",delivery:"İstenen teslim tarihi",workRequest:"İş talebi",accept:"Kabul et ve teklif hazırla",decline:"Reddet",withdraw:"Talebi geri çek",empty:"Henüz doğrudan iş talebi yok.",statuses:{sent:"Gönderildi",accepted:"Kabul edildi",declined:"Reddedildi",withdrawn:"Geri çekildi",converted:"İş talebine dönüştürüldü"}},
 es:{accepted:"La solicitud se aceptó y se convirtió en una solicitud de trabajo privada.",declined:"Solicitud rechazada.",withdrawn:"Solicitud retirada.",failed:"No se pudo completar la acción.",client:"Cliente",talent:"Profesional / equipo",delivery:"Entrega deseada",workRequest:"Solicitud de trabajo",accept:"Aceptar y preparar oferta",decline:"Rechazar",withdraw:"Retirar solicitud",empty:"Aún no hay solicitudes directas de trabajo.",statuses:{sent:"Enviada",accepted:"Aceptada",declined:"Rechazada",withdrawn:"Retirada",converted:"Convertida en solicitud de trabajo"}},
 fr:{accepted:"La demande a été acceptée et convertie en demande de travail privée.",declined:"Demande refusée.",withdrawn:"Demande retirée.",failed:"Impossible d’effectuer cette action.",client:"Client",talent:"Professionnel / équipe",delivery:"Livraison souhaitée",workRequest:"Demande de travail",accept:"Accepter et préparer l’offre",decline:"Refuser",withdraw:"Retirer la demande",empty:"Aucune demande de travail directe pour le moment.",statuses:{sent:"Envoyée",accepted:"Acceptée",declined:"Refusée",withdrawn:"Retirée",converted:"Convertie en demande de travail"}},
 de:{accepted:"Die Anfrage wurde angenommen und in eine private Arbeitsanfrage umgewandelt.",declined:"Anfrage abgelehnt.",withdrawn:"Anfrage zurückgezogen.",failed:"Die Aktion konnte nicht ausgeführt werden.",client:"Kunde",talent:"Fachkraft / Team",delivery:"Gewünschte Lieferung",workRequest:"Arbeitsanfrage",accept:"Annehmen und Angebot vorbereiten",decline:"Ablehnen",withdraw:"Anfrage zurückziehen",empty:"Noch keine direkten Arbeitsanfragen vorhanden.",statuses:{sent:"Gesendet",accepted:"Angenommen",declined:"Abgelehnt",withdrawn:"Zurückgezogen",converted:"In Arbeitsanfrage umgewandelt"}},
};

export function directHireCopy(locale:string):Copy&{language:Locale}{
 const language=isLocale(locale)?locale:"en";
 return {...copy[language],language};
}
