import {isLocale,type Locale} from "./i18n";
const en={title:"Import a professional profile",description:"Upload a PDF or DOCX (up to 4 MB). Review the source and edit the extracted fields before saving.",choose:"Choose document",upload:"Extract document",busy:"Working…",original:"Keep original wording",improved:"Improve wording with AI",save:"Confirm and save to my profile",source:"Original document text",unavailable:"AI is unavailable. Your source is saved privately; fill in the fields manually or retry later.",review:"Only filled fields replace your current profile. Check every fact before confirming. Nothing is published automatically.",skills:"Detected skills — select the matching skills in your profile",missing:"Missing information",error:"The request could not be completed. Check the document and try again.",saved:"Profile saved",private:"Private",onePerLine:"One item per line"};
type Copy=typeof en;
const copy:Record<Locale,Copy>={en,
 ar:{title:"استيراد الملف المهني",description:"ارفع PDF أو DOCX بحجم أقصى 4 ميغابايت. راجع المصدر وعدّل الحقول المستخرجة قبل الحفظ.",choose:"اختر المستند",upload:"استخراج المستند",busy:"جارٍ العمل…",original:"الاحتفاظ بالصياغة الأصلية",improved:"تحسين الصياغة بالذكاء الاصطناعي",save:"تأكيد وحفظ الحقول في ملفي",source:"نص المستند الأصلي",unavailable:"الذكاء الاصطناعي غير متاح حاليًا. حُفظ المصدر بشكل خاص؛ يمكنك تعبئة الحقول يدويًا أو إعادة المحاولة لاحقًا.",review:"الحقول المعبّأة فقط تستبدل بيانات ملفك الحالية. راجع كل معلومة قبل التأكيد. لا يُنشر شيء تلقائيًا.",skills:"المهارات المكتشفة — اختر المهارات المطابقة في ملفك",missing:"معلومات ناقصة",error:"تعذّر إكمال الطلب. تحقق من المستند وحاول مجددًا.",saved:"تم حفظ الملف",private:"خاص",onePerLine:"عنصر واحد في كل سطر"},
 tr:{title:"Profesyonel profil içe aktar",description:"En fazla 4 MB PDF veya DOCX yükleyin. Kaynağı inceleyin ve kaydetmeden önce alanları düzenleyin.",choose:"Belge seç",upload:"Belgeyi işle",busy:"İşleniyor…",original:"Özgün ifadeleri koru",improved:"İfadeleri yapay zekâ ile iyileştir",save:"Onayla ve profilime kaydet",source:"Özgün belge metni",unavailable:"Yapay zekâ kullanılamıyor. Kaynak özel olarak kaydedildi; alanları elle doldurun veya daha sonra tekrar deneyin.",review:"Yalnızca doldurulan alanlar profilinizi değiştirir. Onaylamadan önce tüm bilgileri kontrol edin. Hiçbir şey otomatik yayımlanmaz.",skills:"Algılanan beceriler — profilinizde eşleşen becerileri seçin",missing:"Eksik bilgiler",error:"İşlem tamamlanamadı. Belgeyi kontrol edip tekrar deneyin.",saved:"Profil kaydedildi",private:"Özel",onePerLine:"Her satıra bir öğe"},
 es:{title:"Importar perfil profesional",description:"Sube un PDF o DOCX de hasta 4 MB. Revisa el original y edita los campos antes de guardar.",choose:"Elegir documento",upload:"Extraer documento",busy:"Procesando…",original:"Conservar la redacción original",improved:"Mejorar la redacción con IA",save:"Confirmar y guardar en mi perfil",source:"Texto del documento original",unavailable:"La IA no está disponible. El original se guardó de forma privada; completa los campos manualmente o inténtalo después.",review:"Solo los campos completados reemplazan tu perfil. Comprueba cada dato antes de confirmar. Nada se publica automáticamente.",skills:"Habilidades detectadas — selecciona las correspondientes en tu perfil",missing:"Información faltante",error:"No se pudo completar la solicitud. Revisa el documento e inténtalo de nuevo.",saved:"Perfil guardado",private:"Privado",onePerLine:"Un elemento por línea"},
 fr:{title:"Importer un profil professionnel",description:"Importez un PDF ou DOCX de 4 Mo maximum. Vérifiez le document et modifiez les champs avant de les enregistrer.",choose:"Choisir un document",upload:"Extraire le document",busy:"Traitement…",original:"Conserver la formulation originale",improved:"Améliorer la formulation avec l’IA",save:"Confirmer et enregistrer dans mon profil",source:"Texte du document original",unavailable:"L’IA est indisponible. Le document est enregistré en privé ; remplissez les champs manuellement ou réessayez plus tard.",review:"Seuls les champs remplis remplacent votre profil. Vérifiez chaque information avant de confirmer. Rien n’est publié automatiquement.",skills:"Compétences détectées — sélectionnez les correspondances dans votre profil",missing:"Informations manquantes",error:"La demande n’a pas pu être traitée. Vérifiez le document et réessayez.",saved:"Profil enregistré",private:"Privé",onePerLine:"Un élément par ligne"},
 de:{title:"Berufsprofil importieren",description:"PDF oder DOCX bis 4 MB hochladen. Prüfen Sie die Quelle und bearbeiten Sie die Felder vor dem Speichern.",choose:"Dokument wählen",upload:"Dokument auslesen",busy:"Wird bearbeitet…",original:"Originalformulierung beibehalten",improved:"Formulierung mit KI verbessern",save:"Bestätigen und im Profil speichern",source:"Originaler Dokumenttext",unavailable:"KI ist derzeit nicht verfügbar. Die Quelle wurde privat gespeichert; füllen Sie die Felder aus oder versuchen Sie es später erneut.",review:"Nur ausgefüllte Felder ersetzen Ihr Profil. Prüfen Sie alle Angaben vor der Bestätigung. Nichts wird automatisch veröffentlicht.",skills:"Erkannte Fähigkeiten — wählen Sie passende Fähigkeiten in Ihrem Profil",missing:"Fehlende Angaben",error:"Die Anfrage konnte nicht abgeschlossen werden. Prüfen Sie das Dokument und versuchen Sie es erneut.",saved:"Profil gespeichert",private:"Privat",onePerLine:"Ein Eintrag pro Zeile"}};
const fieldKeys=["displayName","professionalTitle","bio","location","legalName","phonePrivate","emailPrivate","languages","tools","education","experience","services","expertise","achievements","history","representativePrivate","contactPrivate","teamSize"] as const;
const labels:Record<Locale,string[]>={
 en:["Display name","Professional title","Professional summary","Gaza location","Legal name","Phone","Email","Languages","Software and tools","Education","Experience","Services","Expertise","Achievements","Team history","Representative","Contact details","Team size"],
 ar:["الاسم المهني","المسمى المهني","النبذة المهنية","الموقع في غزة","الاسم القانوني","الهاتف","البريد الإلكتروني","اللغات","البرامج والأدوات","التعليم","الخبرة","الخدمات","مجالات الخبرة","الإنجازات","تاريخ الفريق","ممثل الفريق","بيانات الاتصال","عدد أعضاء الفريق"],
 tr:["Görünen ad","Mesleki unvan","Mesleki özet","Gazze konumu","Yasal ad","Telefon","E-posta","Diller","Yazılım ve araçlar","Eğitim","Deneyim","Hizmetler","Uzmanlık","Başarılar","Ekip geçmişi","Temsilci","İletişim bilgileri","Ekip büyüklüğü"],
 es:["Nombre público","Título profesional","Resumen profesional","Ubicación en Gaza","Nombre legal","Teléfono","Correo electrónico","Idiomas","Programas y herramientas","Educación","Experiencia","Servicios","Especialidades","Logros","Historia del equipo","Representante","Datos de contacto","Tamaño del equipo"],
 fr:["Nom public","Titre professionnel","Résumé professionnel","Localisation à Gaza","Nom légal","Téléphone","Adresse e-mail","Langues","Logiciels et outils","Formation","Expérience","Services","Expertise","Réalisations","Historique de l’équipe","Représentant","Coordonnées","Taille de l’équipe"],
 de:["Anzeigename","Berufsbezeichnung","Berufliches Profil","Standort in Gaza","Rechtlicher Name","Telefon","E-Mail","Sprachen","Software und Werkzeuge","Ausbildung","Erfahrung","Dienstleistungen","Fachgebiete","Erfolge","Teamgeschichte","Vertreter","Kontaktdaten","Teamgröße"]};
export function draftCopy(locale:string){const l=isLocale(locale)?locale:"en";return{...copy[l],fields:Object.fromEntries(fieldKeys.map((key,i)=>[key,labels[l][i]]))}}
