import {isLocale,type Locale} from "@/lib/i18n";

type FinanceCopy={title:string;description:string;developmentSimulation:string;transaction:string;gross:string;deduction:string;providerCost:string;revenue:string;workerEntitlement:string;provider:string;dispute:string;payout:string;notCreated:string;refundDue:string;simulationWarning:string;payoutReference:string;empty:string;states:Record<string,string>;providers:Record<string,string>};
type ReviewCopy={submitted:string;unavailable:string;leave:string;completedProject:string;chooseProject:string;communication:string;professionalism:string;overall:string;quality:string;delivery:string;clarity:string;clarityFull:string;cooperation:string;feedback:string;submit:string;reviews:string;writtenByYou:string;received:string;empty:string};
type Copy={finance:FinanceCopy;reviews:ReviewCopy};

const copy:Record<Locale,Copy>={
 en:{
  finance:{title:"Transaction ledger",description:"Financial values are deterministic, not AI-generated. The normal total transaction deduction target is 7%, including the actual payment-provider cost.",developmentSimulation:"Development simulation",transaction:"Transaction",gross:"Gross project amount",deduction:"Total GazaWorks deduction",providerCost:"Provider cost",revenue:"Platform operating revenue",workerEntitlement:"Worker entitlement",provider:"Provider",dispute:"Dispute",payout:"Payout",notCreated:"Not created",refundDue:"Refund obligation — no completed refund recorded",simulationWarning:"This record is a development simulation and not a real bank or card charge.",payoutReference:"Payout reference",empty:"No transactions yet.",states:{pending:"Pending",created:"Created",processing:"Processing",succeeded:"Succeeded",paid:"Paid",failed:"Failed",refunded:"Refunded",cancelled:"Cancelled",none:"None",open:"Open",under_review:"Under review",decided:"Decided",appeal:"Appeal",final:"Final",payout_pending:"Payout pending",approved:"Approved"},providers:{mock:"Development simulator",bank_of_palestine:"Bank of Palestine",manual_bank_transfer:"Manual bank transfer"}},
  reviews:{submitted:"Review submitted.",unavailable:"Reviews are available only after project completion, with one review per party and project.",leave:"Leave a review",completedProject:"Completed project",chooseProject:"Choose project",communication:"Communication",professionalism:"Professionalism",overall:"Overall",quality:"Quality",delivery:"Delivery",clarity:"Clarity",clarityFull:"Requirements clarity",cooperation:"Cooperation",feedback:"Written feedback",submit:"Submit review",reviews:"Reviews",writtenByYou:"Written by you",received:"Received",empty:"No reviews yet."},
 },
 ar:{
  finance:{title:"السجل المالي",description:"القيم المالية محسوبة برمجيًا وليست من صنع الذكاء الاصطناعي. إجمالي الخصم الطبيعي المستهدف 7% ويشمل التكلفة الفعلية لمزوّد الدفع.",developmentSimulation:"محاكاة تطوير",transaction:"معاملة",gross:"إجمالي قيمة المشروع",deduction:"إجمالي خصم GazaWorks",providerCost:"تكلفة مزوّد الدفع",revenue:"إيراد تشغيل المنصة",workerEntitlement:"استحقاق المحترف",provider:"المزوّد",dispute:"النزاع",payout:"صرف المستحقات",notCreated:"لم يُنشأ",refundDue:"مبلغ مستحق للاسترداد — لم يُسجل ردّه بعد",simulationWarning:"هذا سجل محاكاة تطوير فقط وليس دفعة بنكية أو خصمًا حقيقيًا من بطاقة.",payoutReference:"مرجع التحويل",empty:"لا توجد معاملات حتى الآن.",states:{pending:"قيد الانتظار",created:"تم الإنشاء",processing:"قيد المعالجة",succeeded:"ناجحة",paid:"مدفوع",failed:"فشلت",refunded:"مسترد",cancelled:"ملغى",none:"لا يوجد",open:"مفتوح",under_review:"قيد المراجعة",decided:"صدر القرار",appeal:"استئناف",final:"نهائي",payout_pending:"بانتظار التحويل",approved:"موافق عليه"},providers:{mock:"محاكي التطوير",bank_of_palestine:"بنك فلسطين",manual_bank_transfer:"تحويل بنكي يدوي"}},
  reviews:{submitted:"تم إرسال التقييم.",unavailable:"التقييم متاح بعد اكتمال المشروع فقط، ولكل طرف تقييم واحد لكل مشروع.",leave:"اكتب تقييمًا",completedProject:"المشروع المكتمل",chooseProject:"اختر مشروعًا",communication:"التواصل",professionalism:"الاحترافية",overall:"التقييم العام",quality:"الجودة",delivery:"التسليم",clarity:"الوضوح",clarityFull:"وضوح المتطلبات",cooperation:"التعاون",feedback:"ملاحظات مكتوبة",submit:"إرسال التقييم",reviews:"التقييمات",writtenByYou:"كتبته أنت",received:"استلمته",empty:"لا توجد تقييمات بعد."},
 },
 tr:{
  finance:{title:"İşlem defteri",description:"Finansal değerler yapay zekâ tarafından değil, kesin kurallarla hesaplanır. Normal toplam işlem kesintisi hedefi, gerçek ödeme sağlayıcısı maliyeti dâhil %7’dir.",developmentSimulation:"Geliştirme simülasyonu",transaction:"İşlem",gross:"Brüt proje tutarı",deduction:"Toplam GazaWorks kesintisi",providerCost:"Sağlayıcı maliyeti",revenue:"Platform işletme geliri",workerEntitlement:"Profesyonelin hak edişi",provider:"Sağlayıcı",dispute:"Uyuşmazlık",payout:"Ödeme",notCreated:"Oluşturulmadı",refundDue:"İade yükümlülüğü — tamamlanmış iade kaydı yok",simulationWarning:"Bu kayıt yalnızca geliştirme simülasyonudur; gerçek banka veya kart tahsilatı değildir.",payoutReference:"Ödeme referansı",empty:"Henüz işlem yok.",states:{pending:"Bekliyor",created:"Oluşturuldu",processing:"İşleniyor",succeeded:"Başarılı",paid:"Ödendi",failed:"Başarısız",refunded:"İade edildi",cancelled:"İptal edildi",none:"Yok",open:"Açık",under_review:"İnceleniyor",decided:"Karar verildi",appeal:"İtiraz",final:"Kesin",payout_pending:"Ödeme bekliyor",approved:"Onaylandı"},providers:{mock:"Geliştirme simülatörü",bank_of_palestine:"Bank of Palestine",manual_bank_transfer:"Manuel banka havalesi"}},
  reviews:{submitted:"Değerlendirme gönderildi.",unavailable:"Değerlendirme yalnızca proje tamamlandıktan sonra, taraf ve proje başına bir kez yapılabilir.",leave:"Değerlendirme yaz",completedProject:"Tamamlanan proje",chooseProject:"Proje seçin",communication:"İletişim",professionalism:"Profesyonellik",overall:"Genel",quality:"Kalite",delivery:"Teslim",clarity:"Netlik",clarityFull:"Gereksinimlerin netliği",cooperation:"İş birliği",feedback:"Yazılı görüş",submit:"Değerlendirmeyi gönder",reviews:"Değerlendirmeler",writtenByYou:"Sizin yazdığınız",received:"Alındı",empty:"Henüz değerlendirme yok."},
 },
 es:{
  finance:{title:"Libro de transacciones",description:"Los valores financieros se calculan mediante reglas deterministas, no con IA. El objetivo normal de deducción total es del 7%, incluido el coste real del proveedor de pago.",developmentSimulation:"Simulación de desarrollo",transaction:"Transacción",gross:"Importe bruto del proyecto",deduction:"Deducción total de GazaWorks",providerCost:"Coste del proveedor",revenue:"Ingreso operativo de la plataforma",workerEntitlement:"Importe del profesional",provider:"Proveedor",dispute:"Disputa",payout:"Abono",notCreated:"No creado",refundDue:"Obligación de reembolso — no hay un reembolso completado",simulationWarning:"Este registro es una simulación de desarrollo, no un cargo bancario ni de tarjeta real.",payoutReference:"Referencia del abono",empty:"Aún no hay transacciones.",states:{pending:"Pendiente",created:"Creada",processing:"Procesando",succeeded:"Correcta",paid:"Pagada",failed:"Fallida",refunded:"Reembolsada",cancelled:"Cancelada",none:"Ninguna",open:"Abierta",under_review:"En revisión",decided:"Resuelta",appeal:"Apelación",final:"Final",payout_pending:"Abono pendiente",approved:"Aprobada"},providers:{mock:"Simulador de desarrollo",bank_of_palestine:"Bank of Palestine",manual_bank_transfer:"Transferencia bancaria manual"}},
  reviews:{submitted:"Valoración enviada.",unavailable:"Las valoraciones solo están disponibles tras completar el proyecto, una por parte y proyecto.",leave:"Dejar una valoración",completedProject:"Proyecto completado",chooseProject:"Elegir proyecto",communication:"Comunicación",professionalism:"Profesionalidad",overall:"General",quality:"Calidad",delivery:"Entrega",clarity:"Claridad",clarityFull:"Claridad de requisitos",cooperation:"Cooperación",feedback:"Comentario escrito",submit:"Enviar valoración",reviews:"Valoraciones",writtenByYou:"Escrita por ti",received:"Recibida",empty:"Aún no hay valoraciones."},
 },
 fr:{
  finance:{title:"Grand livre des transactions",description:"Les valeurs financières sont calculées par des règles déterministes, et non par l’IA. La retenue totale normale visée est de 7 %, coût réel du prestataire de paiement compris.",developmentSimulation:"Simulation de développement",transaction:"Transaction",gross:"Montant brut du projet",deduction:"Retenue totale GazaWorks",providerCost:"Coût du prestataire",revenue:"Revenu d’exploitation de la plateforme",workerEntitlement:"Somme due au professionnel",provider:"Prestataire",dispute:"Litige",payout:"Versement",notCreated:"Non créé",refundDue:"Remboursement dû — aucun remboursement finalisé enregistré",simulationWarning:"Cet enregistrement est une simulation de développement, pas un débit bancaire ou par carte réel.",payoutReference:"Référence du versement",empty:"Aucune transaction pour le moment.",states:{pending:"En attente",created:"Créée",processing:"En cours",succeeded:"Réussie",paid:"Payée",failed:"Échec",refunded:"Remboursée",cancelled:"Annulée",none:"Aucun",open:"Ouvert",under_review:"En cours d’examen",decided:"Décidé",appeal:"Recours",final:"Définitif",payout_pending:"Versement en attente",approved:"Approuvé"},providers:{mock:"Simulateur de développement",bank_of_palestine:"Bank of Palestine",manual_bank_transfer:"Virement bancaire manuel"}},
  reviews:{submitted:"Évaluation envoyée.",unavailable:"Les évaluations sont disponibles uniquement après la fin du projet, à raison d’une par partie et par projet.",leave:"Laisser une évaluation",completedProject:"Projet terminé",chooseProject:"Choisir un projet",communication:"Communication",professionalism:"Professionnalisme",overall:"Note globale",quality:"Qualité",delivery:"Livraison",clarity:"Clarté",clarityFull:"Clarté des exigences",cooperation:"Coopération",feedback:"Commentaire écrit",submit:"Envoyer l’évaluation",reviews:"Évaluations",writtenByYou:"Rédigée par vous",received:"Reçue",empty:"Aucune évaluation pour le moment."},
 },
 de:{
  finance:{title:"Transaktionsjournal",description:"Finanzwerte werden regelbasiert und nicht durch KI berechnet. Der reguläre Zielwert für den Gesamtabzug beträgt 7 %, einschließlich der tatsächlichen Kosten des Zahlungsanbieters.",developmentSimulation:"Entwicklungssimulation",transaction:"Transaktion",gross:"Bruttobetrag des Projekts",deduction:"Gesamtabzug von GazaWorks",providerCost:"Anbieterkosten",revenue:"Betriebsertrag der Plattform",workerEntitlement:"Anspruch der Fachkraft",provider:"Anbieter",dispute:"Streitfall",payout:"Auszahlung",notCreated:"Nicht erstellt",refundDue:"Rückerstattungspflicht — keine abgeschlossene Rückerstattung erfasst",simulationWarning:"Dieser Eintrag ist nur eine Entwicklungssimulation und keine echte Bank- oder Kartenbelastung.",payoutReference:"Auszahlungsreferenz",empty:"Noch keine Transaktionen vorhanden.",states:{pending:"Ausstehend",created:"Erstellt",processing:"In Bearbeitung",succeeded:"Erfolgreich",paid:"Bezahlt",failed:"Fehlgeschlagen",refunded:"Erstattet",cancelled:"Abgebrochen",none:"Keiner",open:"Offen",under_review:"In Prüfung",decided:"Entschieden",appeal:"Einspruch",final:"Endgültig",payout_pending:"Auszahlung ausstehend",approved:"Genehmigt"},providers:{mock:"Entwicklungssimulator",bank_of_palestine:"Bank of Palestine",manual_bank_transfer:"Manuelle Banküberweisung"}},
  reviews:{submitted:"Bewertung gesendet.",unavailable:"Bewertungen sind erst nach Projektabschluss möglich, einmal pro Partei und Projekt.",leave:"Bewertung abgeben",completedProject:"Abgeschlossenes Projekt",chooseProject:"Projekt auswählen",communication:"Kommunikation",professionalism:"Professionalität",overall:"Gesamt",quality:"Qualität",delivery:"Lieferung",clarity:"Klarheit",clarityFull:"Klarheit der Anforderungen",cooperation:"Zusammenarbeit",feedback:"Schriftliche Rückmeldung",submit:"Bewertung senden",reviews:"Bewertungen",writtenByYou:"Von Ihnen verfasst",received:"Erhalten",empty:"Noch keine Bewertungen vorhanden."},
 },
};

const localeTags:Record<Locale,string>={en:"en",ar:"ar-PS",tr:"tr-TR",es:"es-ES",fr:"fr-FR",de:"de-DE"};
export function financeReviewCopy(locale:string):Copy&{language:Locale;localeTag:string}{const language=isLocale(locale)?locale:"en";return {...copy[language],language,localeTag:localeTags[language]}}
