export const locales=["ar","en","tr","es","fr","de"] as const;
export type Locale=(typeof locales)[number];
export const isLocale=(value:string):value is Locale=>locales.includes(value as Locale);

type PageCopy={title:string;description:string;features:{title:string;body:string}[];cta:string};
type Copy={
 nav:{talent:string;work:string;trust:string;login:string;join:string};
 hero:{eyebrow:string;title:string;body:string;primary:string;secondary:string};
 stats:string[];
 sections:{services:string;talent:string;cta:string};
 footer:string;
 pages:{hire:PageCopy;joinTalent:PageCopy;joinTeam:PageCopy;why:PageCopy;verification:PageCopy;contact:PageCopy};
};
const copy:Record<Locale,Copy>={
 en:{
  nav:{talent:"Find talent",work:"How it works",trust:"Trust",login:"Sign in",join:"Join GazaWorks"},
  hero:{eyebrow:"Verified professional marketplace",title:"Hire verified talent from Gaza",body:"Work with skilled professionals and teams through clear agreements, private offers, and accountable delivery. Project payments are not active yet.",primary:"Explore talent",secondary:"Post a work request"},
  stats:["Verified through in-person review","Private, accountable collaboration","Project workflow; payments pending"],
  sections:{services:"Built for serious work",talent:"Specialists ready for global teams",cta:"Build exceptional work with Gaza"},
  footer:"Professional opportunity, built on trust.",
  pages:{
   hire:{title:"Hire verified talent from Gaza",description:"Post a work request or invite a professional directly. Every profile is reviewed in person before it goes live, so you know exactly who you're working with.",features:[{title:"Compare offers privately",body:"See price, timeline, and portfolio side by side. Professionals never see competing bids, so pricing stays fair."},{title:"Project payments pending",body:"GazaWorks is not accepting project payments yet. Funding and payouts will open only after an approved provider is connected."},{title:"Resolve issues fairly",body:"If something goes wrong, our team reviews the full record — chat, files, and agreement — before deciding."}],cta:"Post your first work request"},
   joinTalent:{title:"Turn your skills into steady work",description:"Build a verified profile, showcase your portfolio, and get discovered by clients who are ready to pay for real work.",features:[{title:"Verification, not guesswork",body:"A short in-person review confirms who you are — so clients trust your profile from day one."},{title:"Build your CV with AI",body:"No CV yet? Answer a few questions and get a professional draft you can edit and keep."},{title:"Payouts not yet enabled",body:"Build your profile and discuss projects now. Platform funding and payouts are currently unavailable."}],cta:"Create your profile"},
   joinTeam:{title:"Represent your team, not just yourself",description:"List your team's services, portfolio, and members — with privacy controls for anyone who prefers not to use their real name publicly.",features:[{title:"One profile, whole team",body:"Showcase collective experience, past projects, and every member's role."},{title:"Flexible member privacy",body:"Members choose how they appear: full name, alias, or anonymous avatar — GazaWorks always knows who's who internally."},{title:"Win larger projects",body:"Clients can hire your team directly or invite you to bid on multi-skill work requests."}],cta:"Register your team"},
   why:{title:"Built for real work, not charity",description:"GazaWorks exists to connect Gaza's professionals with clients who need real skills — verified, accountable, and protected by design.",features:[{title:"Verified, not just claimed",body:"Every professional and team completes an in-person review before earning a verified badge."},{title:"Structured, not informal",body:"Projects can record agreements and delivery history. Payment records will be enabled after an approved provider is connected."},{title:"Accountable on both sides",body:"Clients and professionals rate each other. Disputes go through a documented, time-bound process — not guesswork."}],cta:"See how it works"},
   verification:{title:"How we verify every profile",description:"A verified badge means a real person reviewed this profile — not an automated check. Here's exactly how it works.",features:[{title:"Submit your documents",body:"Upload your ID and complete your profile before requesting verification."},{title:"Meet our verification team",body:"Book a short appointment. We confirm your identity, location, and professional conduct."},{title:"Get your verified badge",body:"Once approved, your badge appears on your public profile — visible to every client who searches GazaWorks."}],cta:"Start verification"},
   contact:{title:"Get in touch with GazaWorks",description:"Most requests are handled fastest inside your account, where our team can see your profile, project, or verification status.",features:[{title:"Account and verification questions",body:"Sign in and use the notifications panel in your dashboard — our team responds from there."},{title:"Payment or dispute concerns",body:"Open the relevant project and use \"Report an issue\" so our team has the full record."},{title:"Something else",body:"Sign in first if you can — it lets us confirm your identity and respond faster."}],cta:"Sign in to contact us"}
  }
 },
 ar:{
  nav:{talent:"اكتشف المواهب",work:"كيف نعمل",trust:"الثقة والتحقق",login:"تسجيل الدخول",join:"انضم إلى غزة ووركس"},
  hero:{eyebrow:"سوق مهني موثّق",title:"وظّف مواهب موثّقة من غزة",body:"تعاون مع محترفين وفرق ماهرة عبر اتفاقيات واضحة وعروض خاصة وتسليم موثّق. المدفوعات غير مفعّلة بعد.",primary:"استكشف المواهب",secondary:"انشر طلب عمل"},
  stats:["تحقق مهني ومقابلة حضورية","تعاون خاص ومسؤول","مسار مشاريع منظم؛ المدفوعات لاحقًا"],
  sections:{services:"مصمم للعمل الاحترافي",talent:"خبرات جاهزة للفرق العالمية",cta:"أنجز عملاً استثنائياً مع غزة"},
  footer:"فرص مهنية مبنية على الثقة.",
  pages:{
   hire:{title:"وظّف مواهب موثّقة من غزة",description:"انشر طلب عمل أو ادعُ محترفاً مباشرة. كل بروفايل يخضع لمراجعة حضورية قبل نشره، فتعرف بالضبط مع من تتعامل.",features:[{title:"قارن العروض بخصوصية",body:"شوف السعر والمدة والبورتفوليو لكل عرض جنب بعض. المحترفون ما بيشوفوا عروض بعض، فتضل المنافسة عادلة."},{title:"مدفوعات المشاريع قيد التجهيز",body:"لا تستقبل غزة ووركس مدفوعات المشاريع حاليًا. سيُفعّل التمويل والصرف بعد ربط مزوّد دفع معتمد."},{title:"حل النزاعات بعدالة",body:"لو صار أي إشكال، فريقنا يراجع كل السجل — المحادثة والملفات والاتفاقية — قبل ما ياخذ قرار."}],cta:"انشر أول طلب عمل"},
   joinTalent:{title:"حوّل مهاراتك لعمل مستقر",description:"ابنِ بروفايل موثّق، اعرض أعمالك السابقة، وخلّي عملاء جاهزين يدفعوا مقابل شغلك الحقيقي يكتشفوك.",features:[{title:"توثيق حقيقي، مش مجرد ادعاء",body:"مراجعة حضورية قصيرة تأكد هويتك — فيثق فيك العميل من أول لحظة."},{title:"اِبنِ سيرتك الذاتية بالذكاء الاصطناعي",body:"ما عندك CV؟ جاوب على كم سؤال واحصل على مسودة احترافية تقدر تعدّلها وتحتفظ فيها."},{title:"الصرف غير مفعّل بعد",body:"يمكنك بناء ملفك ومناقشة المشاريع الآن؛ تمويل المشاريع وصرف المستحقات غير متاحين حاليًا."}],cta:"أنشئ بروفايلك"},
   joinTeam:{title:"مثّل فريقك، مش بس حالك",description:"اعرض خدمات فريقك وأعماله وأعضاءه — مع خيارات خصوصية لكل عضو ما بيحب يظهر باسمه الحقيقي علناً.",features:[{title:"بروفايل واحد، فريق كامل",body:"اعرض الخبرة الجماعية والمشاريع السابقة ودور كل عضو."},{title:"خصوصية مرنة للأعضاء",body:"كل عضو يختار كيف يظهر: اسمه الكامل، اسم مستعار، أو صورة رمزية — وغزة ووركس دايماً عارفة الهوية الحقيقية داخلياً."},{title:"افز بمشاريع أكبر",body:"العملاء يقدروا يوظفوا فريقك مباشرة أو يدعوكم للمنافسة على طلبات عمل متعددة المهارات."}],cta:"سجّل فريقك"},
   why:{title:"مبني للعمل الحقيقي، مش للإحسان",description:"غزة ووركس موجودة لربط محترفي غزة بعملاء محتاجين مهارات حقيقية — موثّقة ومسؤولة ومحمية بالتصميم.",features:[{title:"موثّق، مش مجرد مُدّعى",body:"كل محترف وفريق يمر بمراجعة حضورية قبل ما ياخذ شارة التوثيق."},{title:"منظّم، مش عشوائي",body:"يمكن توثيق اتفاقية المشروع ومسار تسليمه. سيُفعّل سجل المدفوعات بعد ربط مزوّد معتمد."},{title:"مسؤولية من الطرفين",body:"العميل والمحترف بيقيّموا بعض. النزاعات تمر بمسار موثّق ومحدد بوقت — مش تخمين."}],cta:"شوف كيف نعمل"},
   verification:{title:"كيف نوثّق كل بروفايل",description:"شارة التوثيق تعني إنه شخص حقيقي راجع هالبروفايل — مش فحص آلي. هاي بالضبط كيف بتصير.",features:[{title:"قدّم مستنداتك",body:"ارفع هويتك واستكمل بروفايلك قبل ما تطلب التوثيق."},{title:"قابل فريق التوثيق",body:"احجز موعد قصير. نتأكد من هويتك وموقعك وسلوكك المهني."},{title:"احصل على شارتك الموثّقة",body:"بعد الموافقة، شارتك تظهر على بروفايلك العام — يشوفها كل عميل يدور على غزة ووركس."}],cta:"ابدأ التوثيق"},
   contact:{title:"تواصل مع غزة ووركس",description:"أغلب الطلبات بتنحل أسرع من داخل حسابك، لأنه فريقنا يقدر يشوف بروفايلك أو مشروعك أو حالة توثيقك مباشرة.",features:[{title:"أسئلة عن الحساب أو التوثيق",body:"سجّل دخولك واستخدم لوحة الإشعارات بالداشبورد — فريقنا بيرد من هناك."},{title:"مشكلة بدفعة أو نزاع",body:"افتح المشروع المعني واستخدم \"الإبلاغ عن مشكلة\" حتى يكون عند فريقنا السجل الكامل."},{title:"شي تاني",body:"سجّل دخولك أول إذا قدرت — بيساعدنا نتأكد من هويتك ونرد أسرع."}],cta:"سجّل الدخول للتواصل معنا"}
  }
 },
 tr:{
  nav:{talent:"Yetenek bul",work:"Nasıl çalışır",trust:"Güven",login:"Giriş yap",join:"GazaWorks'e katıl"},
  hero:{eyebrow:"Doğrulanmış profesyonel pazar",title:"Gazze'den doğrulanmış yeteneklerle çalışın",body:"Net anlaşmalar, özel teklifler ve kayıtlı teslim süreçleriyle profesyoneller ve ekiplerle çalışın. Ödeme henüz etkin değil.",primary:"Yetenekleri keşfet",secondary:"İş talebi yayınla"},
  stats:["Yüz yüze inceleme ile doğrulama","Özel ve hesap verebilir işbirliği","Proje akışı; ödemeler beklemede"],
  sections:{services:"Ciddi işler için tasarlandı",talent:"Küresel ekipler için uzmanlar",cta:"Gazze ile nitelikli işler üretin"},
  footer:"Güven üzerine kurulu profesyonel fırsatlar.",
  pages:{
   hire:{title:"Gazze'den doğrulanmış yeteneklerle çalışın",description:"Bir iş talebi yayınlayın veya bir profesyoneli doğrudan davet edin. Her profil yayınlanmadan önce yüz yüze incelenir, böylece kiminle çalıştığınızı tam olarak bilirsiniz.",features:[{title:"Teklifleri gizlice karşılaştırın",body:"Fiyatı, süreyi ve portföyü yan yana görün. Profesyoneller birbirinin teklifini göremez, böylece fiyatlandırma adil kalır."},{title:"Proje ödemeleri beklemede",body:"GazaWorks henüz proje ödemesi kabul etmiyor. Finansman ve ödemeler yalnızca onaylı bir sağlayıcı bağlandıktan sonra açılacak."},{title:"Anlaşmazlıkları adil çözün",body:"Bir sorun olursa, ekibimiz tam kaydı — sohbet, dosyalar ve anlaşma — incelemeden karar vermez."}],cta:"İlk iş talebinizi yayınlayın"},
   joinTalent:{title:"Becerilerinizi düzenli işe dönüştürün",description:"Doğrulanmış bir profil oluşturun, portföyünüzü sergileyin ve gerçek iş için ödeme yapmaya hazır müşteriler tarafından keşfedilin.",features:[{title:"Tahmin değil, gerçek doğrulama",body:"Kısa bir yüz yüze inceleme kimliğinizi doğrular — böylece müşteriler ilk günden profilinize güvenir."},{title:"CV'nizi yapay zekayla oluşturun",body:"Henüz CV'niz yok mu? Birkaç soruyu yanıtlayın, düzenleyip saklayabileceğiniz profesyonel bir taslak alın."},{title:"Ödemeler henüz etkin değil",body:"Şimdi profilinizi oluşturup projeleri görüşebilirsiniz; platform üzerinden fonlama ve ödeme şu anda kullanılamıyor."}],cta:"Profilinizi oluşturun"},
   joinTeam:{title:"Sadece kendinizi değil, ekibinizi temsil edin",description:"Ekibinizin hizmetlerini, portföyünü ve üyelerini listeleyin — gerçek adını herkese açık kullanmak istemeyenler için gizlilik seçenekleriyle.",features:[{title:"Tek profil, tüm ekip",body:"Ortak deneyimi, geçmiş projeleri ve her üyenin rolünü sergileyin."},{title:"Esnek üye gizliliği",body:"Her üye nasıl görüneceğini seçer: tam ad, takma ad veya anonim avatar — GazaWorks dahili olarak her zaman kimin kim olduğunu bilir."},{title:"Daha büyük projeler kazanın",body:"Müşteriler ekibinizi doğrudan işe alabilir veya çok becerili iş taleplerine teklif vermeye davet edebilir."}],cta:"Ekibinizi kaydedin"},
   why:{title:"Yardım için değil, gerçek iş için kuruldu",description:"GazaWorks, Gazze'nin profesyonellerini gerçek beceriye ihtiyaç duyan müşterilerle buluşturmak için var — tasarım gereği doğrulanmış, hesap verebilir ve korumalı.",features:[{title:"Sadece iddia değil, doğrulanmış",body:"Her profesyonel ve ekip, doğrulama rozeti kazanmadan önce yüz yüze bir incelemeden geçer."},{title:"Gayri resmi değil, yapılandırılmış",body:"Projelerin yazılı anlaşması ve teslimat geçmişi kaydedilebilir; ödeme kayıtları onaylı sağlayıcı bağlandığında açılacak."},{title:"İki tarafta da hesap verebilirlik",body:"Müşteriler ve profesyoneller birbirini değerlendirir. Anlaşmazlıklar, tahmine değil, belgelenmiş ve süreli bir sürece tabidir."}],cta:"Nasıl çalıştığını görün"},
   verification:{title:"Her profili nasıl doğruluyoruz",description:"Doğrulama rozeti, bu profili gerçek bir kişinin incelediği anlamına gelir — otomatik bir kontrol değil. İşte tam olarak nasıl çalıştığı.",features:[{title:"Belgelerinizi gönderin",body:"Doğrulama talep etmeden önce kimliğinizi yükleyin ve profilinizi tamamlayın."},{title:"Doğrulama ekibimizle görüşün",body:"Kısa bir randevu alın. Kimliğinizi, konumunuzu ve profesyonel davranışınızı doğrularız."},{title:"Doğrulama rozetinizi alın",body:"Onaylandıktan sonra, rozetiniz herkese açık profilinizde görünür — GazaWorks'te arama yapan her müşteri tarafından görülür."}],cta:"Doğrulamaya başlayın"},
   contact:{title:"GazaWorks ile iletişime geçin",description:"Çoğu talep, ekibimizin profilinizi, projenizi veya doğrulama durumunuzu görebildiği hesabınız içinden en hızlı şekilde çözülür.",features:[{title:"Hesap ve doğrulama soruları",body:"Giriş yapın ve panonuzdaki bildirimler bölümünü kullanın — ekibimiz oradan yanıtlar."},{title:"Ödeme veya anlaşmazlık sorunları",body:"İlgili projeyi açın ve \"Sorun bildir\"i kullanın, böylece ekibimizde tam kayıt olur."},{title:"Başka bir konu",body:"Mümkünse önce giriş yapın — kimliğinizi doğrulamamıza ve daha hızlı yanıt vermemize yardımcı olur."}],cta:"İletişim için giriş yapın"}
  }
 },
 es:{
  nav:{talent:"Buscar talento",work:"Cómo funciona",trust:"Confianza",login:"Iniciar sesión",join:"Únete a GazaWorks"},
  hero:{eyebrow:"Mercado profesional verificado",title:"Contrata talento verificado de Gaza",body:"Trabaja con profesionales y equipos mediante acuerdos claros, ofertas privadas y entregas registradas. Los pagos aún no están disponibles.",primary:"Explorar talento",secondary:"Publicar un proyecto"},
  stats:["Verificación mediante entrevista presencial","Colaboración privada y responsable","Flujo de proyecto con pago asegurado"],
  sections:{services:"Diseñado para trabajo profesional",talent:"Especialistas para equipos globales",cta:"Crea trabajo excepcional con Gaza"},
  footer:"Oportunidades profesionales basadas en la confianza.",
  pages:{
   hire:{title:"Contrata talento verificado de Gaza",description:"Publica una solicitud de trabajo o invita directamente a un profesional. Cada perfil se revisa en persona antes de publicarse, para que sepas exactamente con quién trabajas.",features:[{title:"Compara ofertas en privado",body:"Ve el precio, el plazo y el portafolio uno junto al otro. Los profesionales no ven las ofertas de otros, así los precios se mantienen justos."},{title:"Pagos de proyectos pendientes",body:"GazaWorks aún no acepta pagos de proyectos. La financiación y los retiros se habilitarán tras conectar un proveedor aprobado."},{title:"Resuelve disputas con justicia",body:"Si algo sale mal, nuestro equipo revisa todo el historial — chat, archivos y acuerdo — antes de decidir."}],cta:"Publica tu primera solicitud de trabajo"},
   joinTalent:{title:"Convierte tus habilidades en trabajo estable",description:"Crea un perfil verificado, muestra tu portafolio y deja que te descubran clientes listos para pagar por trabajo real.",features:[{title:"Verificación real, no promesas",body:"Una breve revisión presencial confirma quién eres, así los clientes confían en tu perfil desde el primer día."},{title:"Crea tu CV con IA",body:"¿Aún no tienes CV? Responde algunas preguntas y obtén un borrador profesional que puedes editar y conservar."},{title:"Pagos aún no disponibles",body:"Puedes crear tu perfil y hablar de proyectos; la financiación y los pagos de la plataforma aún no están disponibles."}],cta:"Crea tu perfil"},
   joinTeam:{title:"Representa a tu equipo, no solo a ti",description:"Muestra los servicios, el portafolio y los miembros de tu equipo, con opciones de privacidad para quienes prefieran no usar su nombre real públicamente.",features:[{title:"Un perfil, todo el equipo",body:"Muestra la experiencia colectiva, proyectos anteriores y el rol de cada miembro."},{title:"Privacidad flexible por miembro",body:"Cada miembro elige cómo aparecer: nombre completo, alias o avatar anónimo — GazaWorks siempre sabe quién es quién internamente."},{title:"Gana proyectos más grandes",body:"Los clientes pueden contratar a tu equipo directamente o invitarlos a ofertar en solicitudes multihabilidad."}],cta:"Registra tu equipo"},
   why:{title:"Creado para trabajo real, no caridad",description:"GazaWorks existe para conectar a los profesionales de Gaza con clientes que necesitan habilidades reales — verificado, responsable y protegido por diseño.",features:[{title:"Verificado, no solo declarado",body:"Cada profesional y equipo completa una revisión presencial antes de obtener la insignia verificada."},{title:"Estructurado, no informal",body:"Los acuerdos y las entregas pueden quedar registrados; el seguimiento de pagos se habilitará con un proveedor aprobado."},{title:"Responsabilidad de ambas partes",body:"Clientes y profesionales se califican mutuamente. Las disputas siguen un proceso documentado y con plazos, no conjeturas."}],cta:"Ve cómo funciona"},
   verification:{title:"Cómo verificamos cada perfil",description:"Una insignia verificada significa que una persona real revisó este perfil, no una comprobación automática. Así es exactamente cómo funciona.",features:[{title:"Envía tus documentos",body:"Sube tu identificación y completa tu perfil antes de solicitar la verificación."},{title:"Reúnete con nuestro equipo de verificación",body:"Reserva una cita breve. Confirmamos tu identidad, ubicación y conducta profesional."},{title:"Obtén tu insignia verificada",body:"Una vez aprobada, tu insignia aparece en tu perfil público, visible para cada cliente que busque en GazaWorks."}],cta:"Comienza la verificación"},
   contact:{title:"Ponte en contacto con GazaWorks",description:"La mayoría de las solicitudes se resuelven más rápido desde tu cuenta, donde nuestro equipo puede ver tu perfil, proyecto o estado de verificación.",features:[{title:"Preguntas sobre la cuenta o la verificación",body:"Inicia sesión y usa el panel de notificaciones de tu panel de control — nuestro equipo responde desde ahí."},{title:"Problemas de pago o disputas",body:"Abre el proyecto correspondiente y usa \"Reportar un problema\" para que nuestro equipo tenga el registro completo."},{title:"Otro asunto",body:"Inicia sesión primero si puedes — nos ayuda a confirmar tu identidad y responder más rápido."}],cta:"Inicia sesión para contactarnos"}
  }
 },
 fr:{
  nav:{talent:"Trouver des talents",work:"Comment ça marche",trust:"Confiance",login:"Se connecter",join:"Rejoindre GazaWorks"},
  hero:{eyebrow:"Place de marché professionnelle vérifiée",title:"Recrutez des talents vérifiés de Gaza",body:"Travaillez avec des professionnels et des équipes grâce à des accords clairs, des paiements protégés et des livraisons traçables.",primary:"Explorer les talents",secondary:"Publier une mission"},
  stats:["Vérification avec entretien en personne","Collaboration privée et responsable","Flux de projet avec paiement sécurisé"],
  sections:{services:"Conçu pour le travail professionnel",talent:"Des spécialistes pour les équipes internationales",cta:"Créez un travail exceptionnel avec Gaza"},
  footer:"Des opportunités professionnelles fondées sur la confiance.",
  pages:{
   hire:{title:"Recrutez des talents vérifiés de Gaza",description:"Publiez une demande de mission ou invitez directement un professionnel. Chaque profil est examiné en personne avant sa publication, afin que vous sachiez exactement avec qui vous travaillez.",features:[{title:"Comparez les offres en privé",body:"Visualisez le prix, le délai et le portfolio côte à côte. Les professionnels ne voient pas les offres concurrentes, ce qui garde les prix justes."},{title:"Paiements en attente",body:"GazaWorks n’accepte pas encore les paiements de projets. Le financement et les versements ouvriront avec un prestataire approuvé."},{title:"Résolvez les litiges équitablement",body:"En cas de problème, notre équipe examine l'historique complet — messages, fichiers et accord — avant de trancher."}],cta:"Publiez votre première demande de mission"},
   joinTalent:{title:"Transformez vos compétences en travail stable",description:"Créez un profil vérifié, présentez votre portfolio et faites-vous repérer par des clients prêts à payer pour un vrai travail.",features:[{title:"Une vérification réelle, pas une supposition",body:"Un court entretien en personne confirme votre identité, pour que les clients fassent confiance à votre profil dès le premier jour."},{title:"Créez votre CV avec l'IA",body:"Pas encore de CV ? Répondez à quelques questions et obtenez un brouillon professionnel que vous pouvez modifier et conserver."},{title:"Versements non disponibles",body:"Créez votre profil et discutez des projets ; le financement et les versements via la plateforme ne sont pas encore disponibles."}],cta:"Créez votre profil"},
   joinTeam:{title:"Représentez votre équipe, pas seulement vous-même",description:"Présentez les services, le portfolio et les membres de votre équipe, avec des options de confidentialité pour ceux qui préfèrent ne pas utiliser leur vrai nom publiquement.",features:[{title:"Un seul profil, toute l'équipe",body:"Montrez l'expérience collective, les projets passés et le rôle de chaque membre."},{title:"Confidentialité flexible par membre",body:"Chaque membre choisit comment apparaître : nom complet, pseudonyme ou avatar anonyme — GazaWorks sait toujours qui est qui en interne."},{title:"Décrochez des projets plus importants",body:"Les clients peuvent recruter votre équipe directement ou l'inviter à soumissionner sur des demandes multi-compétences."}],cta:"Enregistrez votre équipe"},
   why:{title:"Conçu pour du vrai travail, pas de la charité",description:"GazaWorks existe pour connecter les professionnels de Gaza à des clients ayant besoin de compétences réelles — vérifié, responsable et protégé par conception.",features:[{title:"Vérifié, pas seulement déclaré",body:"Chaque professionnel et équipe passe un examen en personne avant d'obtenir le badge vérifié."},{title:"Structuré, pas informel",body:"Les accords et les livraisons peuvent être consignés ; les paiements seront suivis après connexion d’un prestataire approuvé."},{title:"Responsabilité des deux côtés",body:"Clients et professionnels s'évaluent mutuellement. Les litiges suivent un processus documenté et limité dans le temps, pas des suppositions."}],cta:"Découvrez comment ça marche"},
   verification:{title:"Comment nous vérifions chaque profil",description:"Un badge vérifié signifie qu'une personne réelle a examiné ce profil — pas un contrôle automatisé. Voici exactement comment cela fonctionne.",features:[{title:"Soumettez vos documents",body:"Téléversez votre pièce d'identité et complétez votre profil avant de demander la vérification."},{title:"Rencontrez notre équipe de vérification",body:"Réservez un court rendez-vous. Nous confirmons votre identité, votre localisation et votre conduite professionnelle."},{title:"Obtenez votre badge vérifié",body:"Une fois approuvé, votre badge apparaît sur votre profil public, visible par tout client effectuant une recherche sur GazaWorks."}],cta:"Commencez la vérification"},
   contact:{title:"Contactez GazaWorks",description:"La plupart des demandes sont traitées plus rapidement depuis votre compte, où notre équipe peut voir votre profil, votre projet ou votre statut de vérification.",features:[{title:"Questions sur le compte ou la vérification",body:"Connectez-vous et utilisez le panneau de notifications de votre tableau de bord — notre équipe y répond."},{title:"Problème de paiement ou litige",body:"Ouvrez le projet concerné et utilisez « Signaler un problème » afin que notre équipe dispose de l'historique complet."},{title:"Autre chose",body:"Connectez-vous d'abord si possible — cela nous aide à confirmer votre identité et à répondre plus vite."}],cta:"Connectez-vous pour nous contacter"}
  }
 },
 de:{
  nav:{talent:"Talente finden",work:"So funktioniert es",trust:"Vertrauen",login:"Anmelden",join:"GazaWorks beitreten"},
  hero:{eyebrow:"Verifizierter professioneller Marktplatz",title:"Verifizierte Talente aus Gaza beauftragen",body:"Arbeiten Sie mit Fachkräften und Teams über klare Vereinbarungen, geschützte Zahlungen und nachvollziehbare Lieferprozesse.",primary:"Talente entdecken",secondary:"Auftrag veröffentlichen"},
  stats:["Verifizierung durch persönliches Gespräch","Private und verantwortliche Zusammenarbeit","Projektablauf mit gesicherter Zahlung"],
  sections:{services:"Für professionelle Arbeit entwickelt",talent:"Spezialisten für internationale Teams",cta:"Hervorragende Arbeit mit Gaza schaffen"},
  footer:"Berufliche Chancen, aufgebaut auf Vertrauen.",
  pages:{
   hire:{title:"Verifizierte Talente aus Gaza beauftragen",description:"Veröffentlichen Sie eine Auftragsanfrage oder laden Sie direkt eine Fachkraft ein. Jedes Profil wird vor der Veröffentlichung persönlich geprüft, damit Sie genau wissen, mit wem Sie arbeiten.",features:[{title:"Angebote privat vergleichen",body:"Preis, Zeitrahmen und Portfolio nebeneinander sehen. Fachkräfte sehen die Angebote der anderen nicht, sodass die Preise fair bleiben."},{title:"Projektzahlungen in Vorbereitung",body:"GazaWorks nimmt derzeit keine Projektzahlungen an. Finanzierung und Auszahlungen beginnen erst mit einem zugelassenen Anbieter."},{title:"Streitfälle fair lösen",body:"Bei Problemen prüft unser Team die vollständige Historie — Chat, Dateien und Vereinbarung — bevor eine Entscheidung fällt."}],cta:"Veröffentlichen Sie Ihre erste Auftragsanfrage"},
   joinTalent:{title:"Machen Sie aus Ihren Fähigkeiten stabile Arbeit",description:"Erstellen Sie ein verifiziertes Profil, präsentieren Sie Ihr Portfolio und werden Sie von Kunden entdeckt, die für echte Arbeit bezahlen möchten.",features:[{title:"Echte Verifizierung, keine Vermutung",body:"Ein kurzes persönliches Gespräch bestätigt Ihre Identität — so vertrauen Kunden Ihrem Profil vom ersten Tag an."},{title:"Erstellen Sie Ihren Lebenslauf mit KI",body:"Noch kein Lebenslauf? Beantworten Sie ein paar Fragen und erhalten Sie einen professionellen Entwurf zum Bearbeiten und Behalten."},{title:"Auszahlungen noch nicht verfügbar",body:"Sie können Ihr Profil erstellen und Projekte besprechen; Finanzierung und Auszahlungen über die Plattform sind derzeit nicht verfügbar."}],cta:"Erstellen Sie Ihr Profil"},
   joinTeam:{title:"Vertreten Sie Ihr Team, nicht nur sich selbst",description:"Listen Sie die Dienstleistungen, das Portfolio und die Mitglieder Ihres Teams auf — mit Datenschutzoptionen für alle, die ihren echten Namen nicht öffentlich verwenden möchten.",features:[{title:"Ein Profil, ganzes Team",body:"Zeigen Sie gemeinsame Erfahrung, vergangene Projekte und die Rolle jedes Mitglieds."},{title:"Flexibler Datenschutz pro Mitglied",body:"Jedes Mitglied wählt, wie es erscheint: voller Name, Pseudonym oder anonymer Avatar — GazaWorks weiß intern immer, wer wer ist."},{title:"Größere Projekte gewinnen",body:"Kunden können Ihr Team direkt beauftragen oder zur Angebotsabgabe bei Multi-Skill-Anfragen einladen."}],cta:"Registrieren Sie Ihr Team"},
   why:{title:"Für echte Arbeit gebaut, nicht für Wohltätigkeit",description:"GazaWorks verbindet Fachkräfte aus Gaza mit Kunden, die echte Fähigkeiten benötigen — verifiziert, verantwortlich und von Grund auf geschützt.",features:[{title:"Verifiziert, nicht nur behauptet",body:"Jede Fachkraft und jedes Team durchläuft eine persönliche Prüfung, bevor das verifizierte Abzeichen vergeben wird."},{title:"Strukturiert, nicht informell",body:"Vereinbarungen und Lieferungen können dokumentiert werden; Zahlungsdaten folgen erst mit einem zugelassenen Anbieter."},{title:"Verantwortung auf beiden Seiten",body:"Kunden und Fachkräfte bewerten sich gegenseitig. Streitfälle durchlaufen einen dokumentierten, zeitlich begrenzten Prozess — keine Vermutungen."}],cta:"Sehen Sie, wie es funktioniert"},
   verification:{title:"Wie wir jedes Profil verifizieren",description:"Ein verifiziertes Abzeichen bedeutet, dass eine echte Person dieses Profil geprüft hat — keine automatische Kontrolle. So funktioniert es genau.",features:[{title:"Reichen Sie Ihre Dokumente ein",body:"Laden Sie Ihren Ausweis hoch und vervollständigen Sie Ihr Profil, bevor Sie die Verifizierung beantragen."},{title:"Treffen Sie unser Verifizierungsteam",body:"Vereinbaren Sie einen kurzen Termin. Wir bestätigen Ihre Identität, Ihren Standort und Ihr professionelles Verhalten."},{title:"Erhalten Sie Ihr verifiziertes Abzeichen",body:"Nach der Genehmigung erscheint Ihr Abzeichen auf Ihrem öffentlichen Profil — sichtbar für jeden Kunden, der auf GazaWorks sucht."}],cta:"Verifizierung starten"},
   contact:{title:"Kontaktieren Sie GazaWorks",description:"Die meisten Anfragen werden am schnellsten über Ihr Konto bearbeitet, wo unser Team Ihr Profil, Projekt oder Ihren Verifizierungsstatus einsehen kann.",features:[{title:"Fragen zu Konto oder Verifizierung",body:"Melden Sie sich an und nutzen Sie den Benachrichtigungsbereich in Ihrem Dashboard — unser Team antwortet von dort."},{title:"Zahlungs- oder Streitfragen",body:"Öffnen Sie das betreffende Projekt und nutzen Sie \"Problem melden\", damit unser Team die vollständige Historie hat."},{title:"Etwas anderes",body:"Melden Sie sich wenn möglich zuerst an — das hilft uns, Ihre Identität zu bestätigen und schneller zu antworten."}],cta:"Zum Kontaktieren anmelden"}
  }
 }
};
export function messages(locale:Locale){return copy[locale]??copy.en}
export function direction(locale:Locale){return locale==="ar"?"rtl":"ltr"}
