import {isLocale} from './i18n';
const copy={
 ar:{liveTitle:'اتصال صوتي مباشر',liveHint:'تحدث بطبيعتك، ويمكنك مقاطعتي أثناء الرد.',mute:'كتم الميكروفون',unmute:'تشغيل الميكروفون',muted:'الميكروفون مكتوم',endCall:'إنهاء الاتصال',liveUnavailable:'المحادثة المباشرة غير متاحة من المزوّد الآن. يمكنك الكتابة أو إرسال رسالة صوتية.',liveQuota:'وصلت إلى حد المحادثة الصوتية المتاح. حاول لاحقًا أو استخدم الرسائل.',liveDisconnected:'انقطع الاتصال الصوتي. اضغط اتصال لإعادة المحاولة.',liveEnded:'انتهت الجلسة الصوتية. يمكنك بدء اتصال جديد.',voiceHint:'عند بدء الاتصال يُرسل صوتك مباشرة إلى مزوّد الذكاء الاصطناعي ويرد بصوت طبيعي. يمكنك مقاطعته أو كتم الميكروفون أو إنهاء الاتصال. التسجيلات لا تُحفظ في المنصة.'},
 en:{liveTitle:'Live voice call',liveHint:'Speak naturally. You can interrupt my reply.',mute:'Mute microphone',unmute:'Unmute microphone',muted:'Microphone muted',endCall:'End call',liveUnavailable:'Live conversation is unavailable from the provider. Type or send a voice message.',liveQuota:'Voice conversation limit reached. Try later or use messages.',liveDisconnected:'Voice connection interrupted. Start a new call to retry.',liveEnded:'Voice session ended. You can start a new call.',voiceHint:'Starting a call streams your voice directly to the AI provider for natural spoken replies. Interrupt, mute or end the call at any time. Recordings are not stored on the platform.'},
 tr:{liveTitle:'Canlı sesli görüşme',liveHint:'Doğal konuşun. Yanıtımı bölebilirsiniz.',mute:'Mikrofonu kapat',unmute:'Mikrofonu aç',muted:'Mikrofon kapalı',endCall:'Görüşmeyi bitir',liveUnavailable:'Canlı görüşme sağlayıcıda kullanılamıyor. Yazın veya sesli mesaj gönderin.',liveQuota:'Sesli görüşme sınırına ulaşıldı. Daha sonra deneyin.',liveDisconnected:'Ses bağlantısı kesildi. Yeniden arayın.',liveEnded:'Görüşme sona erdi. Yeniden arayabilirsiniz.',voiceHint:'Arama başlayınca sesiniz doğal yanıtlar için doğrudan yapay zekâ sağlayıcısına iletilir. Sözü kesebilir, mikrofonu kapatabilir veya bitirebilirsiniz. Kayıtlar saklanmaz.'},
 es:{liveTitle:'Llamada de voz en directo',liveHint:'Habla con naturalidad. Puedes interrumpirme.',mute:'Silenciar micrófono',unmute:'Activar micrófono',muted:'Micrófono silenciado',endCall:'Finalizar llamada',liveUnavailable:'La conversación en directo no está disponible. Escribe o envía un mensaje de voz.',liveQuota:'Límite de voz alcanzado. Reintenta más tarde.',liveDisconnected:'Conexión de voz interrumpida. Vuelve a llamar.',liveEnded:'La sesión terminó. Puedes iniciar otra llamada.',voiceHint:'Al llamar, tu voz se transmite directamente al proveedor de IA para respuestas naturales. Puedes interrumpir, silenciar o terminar. No se guardan grabaciones.'},
 fr:{liveTitle:'Appel vocal en direct',liveHint:'Parlez naturellement. Vous pouvez m’interrompre.',mute:'Couper le microphone',unmute:'Activer le microphone',muted:'Microphone coupé',endCall:'Terminer l’appel',liveUnavailable:'Conversation en direct indisponible. Écrivez ou envoyez un message vocal.',liveQuota:'Limite vocale atteinte. Réessayez plus tard.',liveDisconnected:'Connexion vocale interrompue. Relancez l’appel.',liveEnded:'Session terminée. Vous pouvez rappeler.',voiceHint:'Pendant l’appel, votre voix est transmise directement au fournisseur IA pour des réponses naturelles. Interrompez, coupez le micro ou terminez à tout moment. Les enregistrements ne sont pas conservés.'},
 de:{liveTitle:'Live-Sprachgespräch',liveHint:'Sprechen Sie natürlich. Sie können mich unterbrechen.',mute:'Mikrofon stummschalten',unmute:'Mikrofon einschalten',muted:'Mikrofon stumm',endCall:'Gespräch beenden',liveUnavailable:'Live-Gespräch beim Anbieter nicht verfügbar. Schreiben oder Sprachnachricht senden.',liveQuota:'Sprachlimit erreicht. Später erneut versuchen.',liveDisconnected:'Sprachverbindung unterbrochen. Erneut anrufen.',liveEnded:'Sitzung beendet. Sie können erneut anrufen.',voiceHint:'Im Gespräch wird Ihre Stimme direkt zum KI-Anbieter übertragen, der natürlich antwortet. Sie können unterbrechen, stummschalten oder beenden. Aufnahmen werden nicht gespeichert.'}};
export function liveVoiceCopy(locale:string){return copy[isLocale(locale)?locale:'en'];}
