import {isLocale,type Locale} from "@/lib/i18n";

type Copy={
 sent:string;failed:string;pendingReview:string;preparing:string;attachmentRejected:string;attachmentSent:string;attachmentRecordFailed:string;
 recordingUnsupported:string;recording:string;microphoneFailed:string;projectConversation:string;talent:string;client:string;conversations:string;
 noConversations:string;you:string;user:string;openAttachment:string;startConversation:string;messagePlaceholder:string;send:string;attach:string;
 stopSend:string;voiceMessage:string;selectConversation:string;projectStates:Record<string,string>;
};
const copy:Record<Locale,Copy>={
 en:{sent:"Sent.",failed:"Could not send.",pendingReview:"This message is awaiting review because it may contain external contact information. Review target: within 24 hours.",preparing:"Preparing attachment…",attachmentRejected:"Attachment rejected or file type unsupported.",attachmentSent:"Attachment sent.",attachmentRecordFailed:"Attachment could not be recorded.",recordingUnsupported:"Voice recording is not supported in this browser.",recording:"Recording…",microphoneFailed:"Microphone access failed.",projectConversation:"Project conversation",talent:"Professional",client:"Client",conversations:"Conversations",noConversations:"No project conversations yet.",you:"You",user:"User",openAttachment:"Open attachment",startConversation:"Start the project conversation inside GazaWorks.",messagePlaceholder:"Write a message…",send:"Send",attach:"Attach",stopSend:"Stop & send",voiceMessage:"Voice message",selectConversation:"Select a conversation.",projectStates:{offer_accepted:"Offer accepted",awaiting_payment:"Awaiting payment",funded:"Funded",in_progress:"In progress",submitted:"Submitted",client_review:"Client review",completed:"Completed",disputed:"Disputed",appeal:"Appeal",cancelled:"Cancelled",refunded:"Refunded",payout_pending:"Payout pending",paid:"Paid out"}},
 ar:{sent:"تم الإرسال.",failed:"تعذّر الإرسال.",pendingReview:"هذه الرسالة بانتظار المراجعة لاحتمال احتوائها على بيانات تواصل خارجية. المهلة المعلنة: خلال 24 ساعة.",preparing:"جارٍ تجهيز المرفق…",attachmentRejected:"رُفض المرفق أو نوع الملف غير مدعوم.",attachmentSent:"تم إرسال المرفق.",attachmentRecordFailed:"تعذّر تسجيل المرفق.",recordingUnsupported:"التسجيل الصوتي غير مدعوم في هذا المتصفح.",recording:"جارٍ التسجيل…",microphoneFailed:"تعذّر الوصول إلى الميكروفون.",projectConversation:"محادثة مشروع",talent:"المحترف",client:"العميل",conversations:"المحادثات",noConversations:"لا توجد محادثات مشاريع بعد.",you:"أنت",user:"المستخدم",openAttachment:"فتح المرفق",startConversation:"ابدأ محادثة المشروع داخل GazaWorks.",messagePlaceholder:"اكتب رسالة…",send:"إرسال",attach:"مرفق",stopSend:"إيقاف وإرسال",voiceMessage:"رسالة صوتية",selectConversation:"اختر محادثة.",projectStates:{offer_accepted:"تم قبول العرض",awaiting_payment:"بانتظار الدفع",funded:"مموّل",in_progress:"قيد التنفيذ",submitted:"تم التسليم",client_review:"مراجعة العميل",completed:"مكتمل",disputed:"نزاع",appeal:"استئناف",cancelled:"ملغى",refunded:"مسترد",payout_pending:"بانتظار التحويل",paid:"تم الصرف"}},
 tr:{sent:"Gönderildi.",failed:"Gönderilemedi.",pendingReview:"Bu mesaj harici iletişim bilgileri içerebileceği için inceleme bekliyor. Hedef inceleme süresi: 24 saat içinde.",preparing:"Ek hazırlanıyor…",attachmentRejected:"Ek reddedildi veya dosya türü desteklenmiyor.",attachmentSent:"Ek gönderildi.",attachmentRecordFailed:"Ek kaydedilemedi.",recordingUnsupported:"Bu tarayıcı ses kaydını desteklemiyor.",recording:"Kaydediliyor…",microphoneFailed:"Mikrofona erişilemedi.",projectConversation:"Proje görüşmesi",talent:"Profesyonel",client:"Müşteri",conversations:"Görüşmeler",noConversations:"Henüz proje görüşmesi yok.",you:"Siz",user:"Kullanıcı",openAttachment:"Eki aç",startConversation:"Proje görüşmesini GazaWorks içinde başlatın.",messagePlaceholder:"Mesaj yazın…",send:"Gönder",attach:"Ekle",stopSend:"Durdur ve gönder",voiceMessage:"Sesli mesaj",selectConversation:"Bir görüşme seçin.",projectStates:{offer_accepted:"Teklif kabul edildi",awaiting_payment:"Ödeme bekleniyor",funded:"Fonlandı",in_progress:"Devam ediyor",submitted:"Teslim edildi",client_review:"Müşteri incelemesi",completed:"Tamamlandı",disputed:"Uyuşmazlık",appeal:"İtiraz",cancelled:"İptal edildi",refunded:"İade edildi",payout_pending:"Ödeme bekliyor",paid:"Ödendi"}},
 es:{sent:"Enviado.",failed:"No se pudo enviar.",pendingReview:"Este mensaje está pendiente de revisión porque podría contener datos de contacto externos. Objetivo de revisión: en un plazo de 24 horas.",preparing:"Preparando archivo…",attachmentRejected:"Archivo rechazado o tipo no admitido.",attachmentSent:"Archivo enviado.",attachmentRecordFailed:"No se pudo registrar el archivo.",recordingUnsupported:"Este navegador no admite grabación de voz.",recording:"Grabando…",microphoneFailed:"No se pudo acceder al micrófono.",projectConversation:"Conversación del proyecto",talent:"Profesional",client:"Cliente",conversations:"Conversaciones",noConversations:"Aún no hay conversaciones de proyectos.",you:"Tú",user:"Usuario",openAttachment:"Abrir archivo",startConversation:"Inicia la conversación del proyecto dentro de GazaWorks.",messagePlaceholder:"Escribe un mensaje…",send:"Enviar",attach:"Adjuntar",stopSend:"Detener y enviar",voiceMessage:"Mensaje de voz",selectConversation:"Selecciona una conversación.",projectStates:{offer_accepted:"Oferta aceptada",awaiting_payment:"Pendiente de pago",funded:"Financiado",in_progress:"En curso",submitted:"Entregado",client_review:"Revisión del cliente",completed:"Completado",disputed:"En disputa",appeal:"Apelación",cancelled:"Cancelado",refunded:"Reembolsado",payout_pending:"Abono pendiente",paid:"Pagado"}},
 fr:{sent:"Envoyé.",failed:"Envoi impossible.",pendingReview:"Ce message attend une vérification, car il peut contenir des coordonnées externes. Objectif de traitement : sous 24 heures.",preparing:"Préparation de la pièce jointe…",attachmentRejected:"Pièce jointe refusée ou type de fichier non pris en charge.",attachmentSent:"Pièce jointe envoyée.",attachmentRecordFailed:"Impossible d’enregistrer la pièce jointe.",recordingUnsupported:"L’enregistrement vocal n’est pas pris en charge par ce navigateur.",recording:"Enregistrement…",microphoneFailed:"Accès au micro impossible.",projectConversation:"Conversation du projet",talent:"Professionnel",client:"Client",conversations:"Conversations",noConversations:"Aucune conversation de projet pour le moment.",you:"Vous",user:"Utilisateur",openAttachment:"Ouvrir la pièce jointe",startConversation:"Commencez la conversation du projet sur GazaWorks.",messagePlaceholder:"Écrivez un message…",send:"Envoyer",attach:"Joindre",stopSend:"Arrêter et envoyer",voiceMessage:"Message vocal",selectConversation:"Choisissez une conversation.",projectStates:{offer_accepted:"Offre acceptée",awaiting_payment:"Paiement en attente",funded:"Financé",in_progress:"En cours",submitted:"Livré",client_review:"Examen du client",completed:"Terminé",disputed:"En litige",appeal:"Recours",cancelled:"Annulé",refunded:"Remboursé",payout_pending:"Versement en attente",paid:"Payé"}},
 de:{sent:"Gesendet.",failed:"Senden fehlgeschlagen.",pendingReview:"Diese Nachricht wartet auf Prüfung, da sie externe Kontaktdaten enthalten könnte. Ziel für die Prüfung: innerhalb von 24 Stunden.",preparing:"Anhang wird vorbereitet…",attachmentRejected:"Anhang abgelehnt oder Dateityp nicht unterstützt.",attachmentSent:"Anhang gesendet.",attachmentRecordFailed:"Anhang konnte nicht erfasst werden.",recordingUnsupported:"Sprachaufzeichnung wird von diesem Browser nicht unterstützt.",recording:"Aufnahme läuft…",microphoneFailed:"Zugriff auf das Mikrofon fehlgeschlagen.",projectConversation:"Projektgespräch",talent:"Fachkraft",client:"Kunde",conversations:"Unterhaltungen",noConversations:"Noch keine Projektunterhaltungen vorhanden.",you:"Sie",user:"Benutzer",openAttachment:"Anhang öffnen",startConversation:"Beginnen Sie das Projektgespräch innerhalb von GazaWorks.",messagePlaceholder:"Nachricht schreiben…",send:"Senden",attach:"Anhängen",stopSend:"Stoppen und senden",voiceMessage:"Sprachnachricht",selectConversation:"Wählen Sie eine Unterhaltung.",projectStates:{offer_accepted:"Angebot angenommen",awaiting_payment:"Zahlung ausstehend",funded:"Finanziert",in_progress:"In Arbeit",submitted:"Eingereicht",client_review:"Kundenprüfung",completed:"Abgeschlossen",disputed:"Streitfall",appeal:"Einspruch",cancelled:"Abgebrochen",refunded:"Erstattet",payout_pending:"Auszahlung ausstehend",paid:"Ausgezahlt"}},
};
const localeTags:Record<Locale,string>={en:"en",ar:"ar-PS",tr:"tr-TR",es:"es-ES",fr:"fr-FR",de:"de-DE"};
export function messagesPanelCopy(locale:string):Copy&{language:Locale;localeTag:string}{const language=isLocale(locale)?locale:"en";return {...copy[language],language,localeTag:localeTags[language]}}
