import {isLocale,type Locale} from "@/lib/i18n";

type TeamMemberCopy={
 teamOnly:string;uploading:string;uploadFailed:string;uploaded:string;added:string;addFailed:string;removeConfirm:string;
 addTitle:string;addBody:string;realName:string;private:string;publicName:string;professionalTitle:string;teamRole:string;
 skills:string;commaSeparated:string;skillsPlaceholder:string;biography:string;privacy:string;photo:string;choosePhoto:string;
 addMember:string;currentTeam:string;remove:string;empty:string;
 privacyModes:Record<"name_image"|"name_only"|"alias"|"anonymous",string>;
};

type WorkRequestCopy={
 publishingMessage:string;publishFailed:string;published:string;attachmentFailed:string;statusFailed:string;
 createTitle:string;createBody:string;title:string;titlePlaceholder:string;description:string;category:string;chooseCategory:string;
 requiredSkills:string;minimumBudget:string;maximumBudget:string;currency:string;deliveryExpectations:string;deliveryPlaceholder:string;
 additionalNotes:string;visibility:string;publicVisibility:string;privateVisibility:string;attachments:string;sizeHint:string;
 publishing:string;publish:string;yourRequests:string;created:string;delivery:string;reference:string;close:string;cancel:string;empty:string;
 statuses:Record<"draft"|"published"|"closed"|"cancelled",string>;
 visibilityModes:Record<"public"|"invite_only",string>;
};

type WorkspaceFormCopy={teamMembers:TeamMemberCopy;workRequests:WorkRequestCopy};

const copy:Record<Locale,WorkspaceFormCopy>={
 en:{
  teamMembers:{teamOnly:"This page is available to team accounts only.",uploading:"Uploading member image…",uploadFailed:"Image upload failed. Use a JPG, PNG or WebP image under 10 MB.",uploaded:"Image uploaded and will be linked when you save the member.",added:"Team member added.",addFailed:"Unable to add member.",removeConfirm:"Remove this team member from the team profile?",addTitle:"Add a team member",addBody:"Control how every member appears to clients. GazaWorks can retain the real identity privately when verification requires it.",realName:"Real name",private:"Private",publicName:"Public name or alias",professionalTitle:"Professional title",teamRole:"Team role",skills:"Skills",commaSeparated:"comma separated",skillsPlaceholder:"Design, React, video editing",biography:"Biography",privacy:"Privacy",photo:"Photo",choosePhoto:"Choose member image",addMember:"Add member",currentTeam:"Current team",remove:"Remove",empty:"No team members added yet.",privacyModes:{name_image:"Real name and image",name_only:"Real name without image",alias:"Professional alias",anonymous:"Anonymous avatar"}},
  workRequests:{publishingMessage:"Publishing work request…",publishFailed:"Could not publish. Sign in as a client and check the fields.",published:"Work request published.",attachmentFailed:"The work request was created, but an attachment could not be uploaded. You can reopen the request and add the file later.",statusFailed:"Could not update the request status.",createTitle:"Create a work request",createBody:"Describe the engagement clearly so verified professionals can submit relevant offers.",title:"Title",titlePlaceholder:"e.g. Edit 10 short-form videos",description:"Description",category:"Category",chooseCategory:"Choose category",requiredSkills:"Required skills",minimumBudget:"Minimum budget",maximumBudget:"Maximum budget",currency:"Currency",deliveryExpectations:"Delivery expectations",deliveryPlaceholder:"Target date, milestones, revisions…",additionalNotes:"Additional notes",visibility:"Visibility",publicVisibility:"Relevant verified talent",privateVisibility:"Private invitations only",attachments:"Attachments",sizeHint:"up to 50 MB each",publishing:"Publishing…",publish:"Publish work request",yourRequests:"Your work requests",created:"Created",delivery:"Delivery",reference:"Reference ID",close:"Close request",cancel:"Cancel",empty:"You have not published any work requests yet.",statuses:{draft:"Draft",published:"Published",closed:"Closed",cancelled:"Cancelled"},visibilityModes:{public:"Relevant verified talent",invite_only:"Private invitations only"}},
 },
 ar:{
  teamMembers:{teamOnly:"هذه الصفحة متاحة لحسابات الفرق فقط.",uploading:"جارٍ رفع صورة العضو…",uploadFailed:"تعذّر رفع الصورة. استخدم صورة JPG أو PNG أو WebP بحجم أقل من 10 ميغابايت.",uploaded:"تم رفع الصورة وستُربط بالعضو عند الحفظ.",added:"تمت إضافة عضو الفريق.",addFailed:"تعذّر إضافة العضو.",removeConfirm:"إزالة هذا العضو من ملف الفريق؟",addTitle:"إضافة عضو فريق",addBody:"يمكنك التحكم في طريقة ظهور كل عضو للعملاء. يحتفظ فريق GazaWorks بالهوية الحقيقية داخليًا عند الحاجة للتحقق.",realName:"الاسم الحقيقي",private:"خاص",publicName:"الاسم العام أو المستعار",professionalTitle:"المسمى المهني",teamRole:"الدور في الفريق",skills:"المهارات",commaSeparated:"افصل بينها بفاصلة",skillsPlaceholder:"تصميم، React، مونتاج",biography:"نبذة",privacy:"خصوصية الظهور",photo:"صورة",choosePhoto:"اختيار صورة العضو",addMember:"إضافة العضو",currentTeam:"الفريق الحالي",remove:"إزالة",empty:"لم تتم إضافة أعضاء بعد.",privacyModes:{name_image:"الاسم الحقيقي والصورة",name_only:"الاسم الحقيقي بدون صورة",alias:"اسم مهني مستعار",anonymous:"صورة رمزية مجهولة"}},
  workRequests:{publishingMessage:"جارٍ نشر طلب العمل…",publishFailed:"تعذّر النشر. تأكد أنك داخل حساب عميل وأن الحقول صحيحة.",published:"تم نشر طلب العمل بنجاح.",attachmentFailed:"تم إنشاء طلب العمل، لكن تعذّر رفع أحد المرفقات. يمكنك فتح الطلب وإضافة الملف لاحقًا.",statusFailed:"تعذّر تحديث حالة الطلب.",createTitle:"إنشاء طلب عمل",createBody:"اشرح المهمة بوضوح حتى يتمكن المحترفون الموثقون من تقديم عروض مناسبة.",title:"العنوان",titlePlaceholder:"مثال: مونتاج 10 فيديوهات قصيرة",description:"الوصف",category:"التصنيف",chooseCategory:"اختر التصنيف",requiredSkills:"المهارات المطلوبة",minimumBudget:"الحد الأدنى للميزانية",maximumBudget:"الحد الأعلى للميزانية",currency:"العملة",deliveryExpectations:"توقعات التسليم",deliveryPlaceholder:"الموعد المتوقع، مراحل التسليم، عدد المراجعات…",additionalNotes:"ملاحظات إضافية",visibility:"الظهور",publicVisibility:"للمواهب الموثقة ذات الصلة",privateVisibility:"دعوات خاصة فقط",attachments:"المرفقات",sizeHint:"حتى 50 ميغابايت للملف الواحد",publishing:"جارٍ النشر…",publish:"نشر طلب العمل",yourRequests:"طلبات العمل الخاصة بك",created:"تاريخ الإنشاء",delivery:"التسليم",reference:"الرقم المرجعي",close:"إغلاق الطلب",cancel:"إلغاء",empty:"لم تنشر أي طلب عمل بعد.",statuses:{draft:"مسودة",published:"منشور",closed:"مغلق",cancelled:"ملغى"},visibilityModes:{public:"للمواهب الموثقة ذات الصلة",invite_only:"دعوات خاصة فقط"}},
 },
 tr:{
  teamMembers:{teamOnly:"Bu sayfa yalnızca ekip hesapları tarafından kullanılabilir.",uploading:"Üye görseli yükleniyor…",uploadFailed:"Görsel yüklenemedi. 10 MB altındaki JPG, PNG veya WebP dosyalarını kullanın.",uploaded:"Görsel yüklendi ve üyeyi kaydettiğinizde ilişkilendirilecek.",added:"Ekip üyesi eklendi.",addFailed:"Üye eklenemedi.",removeConfirm:"Bu ekip üyesi profilden kaldırılsın mı?",addTitle:"Ekip üyesi ekle",addBody:"Her üyenin müşterilere nasıl görüneceğini belirleyin. Doğrulama gerektiğinde GazaWorks gerçek kimliği gizli tutabilir.",realName:"Gerçek ad",private:"Gizli",publicName:"Görünen ad veya rumuz",professionalTitle:"Mesleki unvan",teamRole:"Ekip rolü",skills:"Beceriler",commaSeparated:"virgülle ayırın",skillsPlaceholder:"Tasarım, React, video düzenleme",biography:"Biyografi",privacy:"Gizlilik",photo:"Fotoğraf",choosePhoto:"Üye görseli seç",addMember:"Üye ekle",currentTeam:"Mevcut ekip",remove:"Kaldır",empty:"Henüz ekip üyesi eklenmedi.",privacyModes:{name_image:"Gerçek ad ve görsel",name_only:"Görselsiz gerçek ad",alias:"Mesleki rumuz",anonymous:"Anonim avatar"}},
  workRequests:{publishingMessage:"İş talebi yayınlanıyor…",publishFailed:"Yayınlanamadı. Müşteri hesabıyla giriş yaptığınızdan ve alanların doğru olduğundan emin olun.",published:"İş talebi yayınlandı.",attachmentFailed:"İş talebi oluşturuldu ancak bir ek yüklenemedi. Talebi açıp dosyayı daha sonra ekleyebilirsiniz.",statusFailed:"Talep durumu güncellenemedi.",createTitle:"İş talebi oluştur",createBody:"Doğrulanmış profesyonellerin uygun teklifler sunabilmesi için işi açıkça anlatın.",title:"Başlık",titlePlaceholder:"Örn. 10 kısa video düzenleme",description:"Açıklama",category:"Kategori",chooseCategory:"Kategori seçin",requiredSkills:"Gerekli beceriler",minimumBudget:"En düşük bütçe",maximumBudget:"En yüksek bütçe",currency:"Para birimi",deliveryExpectations:"Teslim beklentileri",deliveryPlaceholder:"Hedef tarih, aşamalar, revizyonlar…",additionalNotes:"Ek notlar",visibility:"Görünürlük",publicVisibility:"İlgili doğrulanmış yetenekler",privateVisibility:"Yalnızca özel davetler",attachments:"Ekler",sizeHint:"dosya başına en fazla 50 MB",publishing:"Yayınlanıyor…",publish:"İş talebini yayınla",yourRequests:"İş talepleriniz",created:"Oluşturulma",delivery:"Teslim",reference:"Referans kimliği",close:"Talebi kapat",cancel:"İptal et",empty:"Henüz bir iş talebi yayınlamadınız.",statuses:{draft:"Taslak",published:"Yayında",closed:"Kapalı",cancelled:"İptal edildi"},visibilityModes:{public:"İlgili doğrulanmış yetenekler",invite_only:"Yalnızca özel davetler"}},
 },
 es:{
  teamMembers:{teamOnly:"Esta página solo está disponible para cuentas de equipo.",uploading:"Subiendo la imagen del miembro…",uploadFailed:"No se pudo subir la imagen. Usa JPG, PNG o WebP de menos de 10 MB.",uploaded:"La imagen se ha subido y se vinculará al guardar el miembro.",added:"Miembro del equipo añadido.",addFailed:"No se pudo añadir el miembro.",removeConfirm:"¿Eliminar este miembro del perfil del equipo?",addTitle:"Añadir miembro del equipo",addBody:"Controla cómo aparece cada miembro ante los clientes. GazaWorks puede conservar la identidad real de forma privada cuando la verificación lo requiera.",realName:"Nombre real",private:"Privado",publicName:"Nombre público o alias",professionalTitle:"Título profesional",teamRole:"Función en el equipo",skills:"Habilidades",commaSeparated:"separadas por comas",skillsPlaceholder:"Diseño, React, edición de vídeo",biography:"Biografía",privacy:"Privacidad",photo:"Foto",choosePhoto:"Elegir imagen del miembro",addMember:"Añadir miembro",currentTeam:"Equipo actual",remove:"Eliminar",empty:"Aún no se han añadido miembros.",privacyModes:{name_image:"Nombre real e imagen",name_only:"Nombre real sin imagen",alias:"Alias profesional",anonymous:"Avatar anónimo"}},
  workRequests:{publishingMessage:"Publicando solicitud…",publishFailed:"No se pudo publicar. Inicia sesión como cliente y revisa los campos.",published:"Solicitud de trabajo publicada.",attachmentFailed:"La solicitud se creó, pero no se pudo subir un archivo. Puedes abrirla y añadirlo más tarde.",statusFailed:"No se pudo actualizar el estado.",createTitle:"Crear una solicitud de trabajo",createBody:"Describe claramente el encargo para que profesionales verificados puedan presentar ofertas relevantes.",title:"Título",titlePlaceholder:"Ej. Editar 10 vídeos cortos",description:"Descripción",category:"Categoría",chooseCategory:"Elegir categoría",requiredSkills:"Habilidades necesarias",minimumBudget:"Presupuesto mínimo",maximumBudget:"Presupuesto máximo",currency:"Moneda",deliveryExpectations:"Expectativas de entrega",deliveryPlaceholder:"Fecha objetivo, hitos, revisiones…",additionalNotes:"Notas adicionales",visibility:"Visibilidad",publicVisibility:"Talento verificado relevante",privateVisibility:"Solo invitaciones privadas",attachments:"Archivos adjuntos",sizeHint:"hasta 50 MB cada uno",publishing:"Publicando…",publish:"Publicar solicitud",yourRequests:"Tus solicitudes de trabajo",created:"Creada",delivery:"Entrega",reference:"ID de referencia",close:"Cerrar solicitud",cancel:"Cancelar",empty:"Aún no has publicado ninguna solicitud.",statuses:{draft:"Borrador",published:"Publicada",closed:"Cerrada",cancelled:"Cancelada"},visibilityModes:{public:"Talento verificado relevante",invite_only:"Solo invitaciones privadas"}},
 },
 fr:{
  teamMembers:{teamOnly:"Cette page est réservée aux comptes d’équipe.",uploading:"Importation de l’image du membre…",uploadFailed:"Impossible d’importer l’image. Utilisez un fichier JPG, PNG ou WebP de moins de 10 Mo.",uploaded:"L’image a été importée et sera associée lors de l’enregistrement du membre.",added:"Membre de l’équipe ajouté.",addFailed:"Impossible d’ajouter le membre.",removeConfirm:"Retirer ce membre du profil de l’équipe ?",addTitle:"Ajouter un membre",addBody:"Contrôlez la façon dont chaque membre apparaît aux clients. GazaWorks peut conserver son identité réelle de manière confidentielle si la vérification l’exige.",realName:"Nom réel",private:"Confidentiel",publicName:"Nom public ou pseudonyme",professionalTitle:"Titre professionnel",teamRole:"Rôle dans l’équipe",skills:"Compétences",commaSeparated:"séparées par des virgules",skillsPlaceholder:"Design, React, montage vidéo",biography:"Biographie",privacy:"Confidentialité",photo:"Photo",choosePhoto:"Choisir l’image du membre",addMember:"Ajouter le membre",currentTeam:"Équipe actuelle",remove:"Retirer",empty:"Aucun membre ajouté pour le moment.",privacyModes:{name_image:"Nom réel et image",name_only:"Nom réel sans image",alias:"Pseudonyme professionnel",anonymous:"Avatar anonyme"}},
  workRequests:{publishingMessage:"Publication de la demande…",publishFailed:"Publication impossible. Connectez-vous avec un compte client et vérifiez les champs.",published:"Demande de travail publiée.",attachmentFailed:"La demande a été créée, mais une pièce jointe n’a pas pu être importée. Vous pourrez l’ajouter plus tard.",statusFailed:"Impossible de mettre à jour le statut.",createTitle:"Créer une demande de travail",createBody:"Décrivez clairement la mission afin que les professionnels vérifiés puissent proposer des offres pertinentes.",title:"Titre",titlePlaceholder:"Ex. Monter 10 vidéos courtes",description:"Description",category:"Catégorie",chooseCategory:"Choisir une catégorie",requiredSkills:"Compétences requises",minimumBudget:"Budget minimum",maximumBudget:"Budget maximum",currency:"Devise",deliveryExpectations:"Attentes de livraison",deliveryPlaceholder:"Date cible, étapes, révisions…",additionalNotes:"Notes supplémentaires",visibility:"Visibilité",publicVisibility:"Talents vérifiés pertinents",privateVisibility:"Invitations privées uniquement",attachments:"Pièces jointes",sizeHint:"50 Mo maximum par fichier",publishing:"Publication…",publish:"Publier la demande",yourRequests:"Vos demandes de travail",created:"Créée",delivery:"Livraison",reference:"Identifiant de référence",close:"Fermer la demande",cancel:"Annuler",empty:"Vous n’avez encore publié aucune demande.",statuses:{draft:"Brouillon",published:"Publiée",closed:"Fermée",cancelled:"Annulée"},visibilityModes:{public:"Talents vérifiés pertinents",invite_only:"Invitations privées uniquement"}},
 },
 de:{
  teamMembers:{teamOnly:"Diese Seite ist nur für Teamkonten verfügbar.",uploading:"Mitgliedsbild wird hochgeladen…",uploadFailed:"Bild konnte nicht hochgeladen werden. Verwenden Sie JPG, PNG oder WebP unter 10 MB.",uploaded:"Das Bild wurde hochgeladen und beim Speichern mit dem Mitglied verknüpft.",added:"Teammitglied hinzugefügt.",addFailed:"Mitglied konnte nicht hinzugefügt werden.",removeConfirm:"Dieses Mitglied aus dem Teamprofil entfernen?",addTitle:"Teammitglied hinzufügen",addBody:"Legen Sie fest, wie jedes Mitglied Kunden angezeigt wird. GazaWorks kann die echte Identität vertraulich speichern, wenn sie für die Verifizierung benötigt wird.",realName:"Echter Name",private:"Vertraulich",publicName:"Öffentlicher Name oder Alias",professionalTitle:"Berufsbezeichnung",teamRole:"Rolle im Team",skills:"Fähigkeiten",commaSeparated:"durch Kommas getrennt",skillsPlaceholder:"Design, React, Videobearbeitung",biography:"Biografie",privacy:"Datenschutz",photo:"Foto",choosePhoto:"Mitgliedsbild auswählen",addMember:"Mitglied hinzufügen",currentTeam:"Aktuelles Team",remove:"Entfernen",empty:"Noch keine Teammitglieder hinzugefügt.",privacyModes:{name_image:"Echter Name und Bild",name_only:"Echter Name ohne Bild",alias:"Beruflicher Alias",anonymous:"Anonymer Avatar"}},
  workRequests:{publishingMessage:"Arbeitsanfrage wird veröffentlicht…",publishFailed:"Veröffentlichung fehlgeschlagen. Melden Sie sich als Kunde an und prüfen Sie die Felder.",published:"Arbeitsanfrage veröffentlicht.",attachmentFailed:"Die Anfrage wurde erstellt, aber ein Anhang konnte nicht hochgeladen werden. Sie können ihn später ergänzen.",statusFailed:"Status konnte nicht aktualisiert werden.",createTitle:"Arbeitsanfrage erstellen",createBody:"Beschreiben Sie den Auftrag klar, damit verifizierte Fachkräfte passende Angebote abgeben können.",title:"Titel",titlePlaceholder:"z. B. 10 Kurzvideos bearbeiten",description:"Beschreibung",category:"Kategorie",chooseCategory:"Kategorie auswählen",requiredSkills:"Benötigte Fähigkeiten",minimumBudget:"Mindestbudget",maximumBudget:"Höchstbudget",currency:"Währung",deliveryExpectations:"Liefererwartungen",deliveryPlaceholder:"Zieldatum, Meilensteine, Überarbeitungen…",additionalNotes:"Zusätzliche Hinweise",visibility:"Sichtbarkeit",publicVisibility:"Passende verifizierte Talente",privateVisibility:"Nur private Einladungen",attachments:"Anhänge",sizeHint:"bis zu 50 MB pro Datei",publishing:"Wird veröffentlicht…",publish:"Arbeitsanfrage veröffentlichen",yourRequests:"Ihre Arbeitsanfragen",created:"Erstellt",delivery:"Lieferung",reference:"Referenz-ID",close:"Anfrage schließen",cancel:"Abbrechen",empty:"Sie haben noch keine Arbeitsanfrage veröffentlicht.",statuses:{draft:"Entwurf",published:"Veröffentlicht",closed:"Geschlossen",cancelled:"Abgebrochen"},visibilityModes:{public:"Passende verifizierte Talente",invite_only:"Nur private Einladungen"}},
 },
};

const localeTags:Record<Locale,string>={en:"en",ar:"ar-PS",tr:"tr-TR",es:"es-ES",fr:"fr-FR",de:"de-DE"};

export function workspaceFormCopy(locale:string):WorkspaceFormCopy&{language:Locale;localeTag:string}{
 const language=isLocale(locale)?locale:"en";
 return {...copy[language],language,localeTag:localeTags[language]};
}
