import {describe,it,expect,vi,afterEach} from "vitest";import {ACCOUNT_TYPES,calculateTransaction,canAppeal,canStartWork,hasPermission,moderateConversation,shouldAutoAccept} from "@/domain/marketplace";
describe("marketplace invariants",()=>{afterEach(()=>vi.useRealTimers());it("exposes exactly three immutable account type choices",()=>expect(ACCOUNT_TYPES).toEqual(["individual","team","client"]));it("calculates the deterministic 7% deduction",()=>expect(calculateTransaction(100000,2500)).toEqual({grossMinor:100000,platformDeductionMinor:7000,providerFeeMinor:2500,platformRevenueMinor:4500,workerEntitlementMinor:93000}));it("does not permit work before funding",()=>{expect(canStartWork("offer_accepted",true)).toBe(false);expect(canStartWork("funded",true)).toBe(true);expect(canStartWork("funded",false)).toBe(false)});it("auto accepts after 72 hours unless disputed",()=>{const d=new Date("2026-01-01T00:00:00Z"),n=new Date("2026-01-04T00:00:00Z");expect(shouldAutoAccept(d,n,false)).toBe(true);expect(shouldAutoAccept(d,n,true)).toBe(false)});it("allows exactly one appeal in twelve hours",()=>{const d=new Date("2026-01-01T00:00:00Z");expect(canAppeal(d,new Date("2026-01-01T11:59:00Z"),0)).toBe(true);expect(canAppeal(d,new Date("2026-01-01T12:01:00Z"),0)).toBe(false);expect(canAppeal(d,new Date("2026-01-01T01:00:00Z"),1)).toBe(false)});it("holds fragmented contact details using rolling context",()=>{vi.useFakeTimers();vi.setSystemTime(new Date("2026-01-01"));expect(moderateConversation([{body:"059",createdAt:new Date()},{body:"123",createdAt:new Date()}],"4567").status).toBe("pending_moderation")});it("supports granular and wildcard RBAC",()=>{expect(hasPermission(["users.read"],"users.edit")).toBe(false);expect(hasPermission(["*"],"payouts.approve")).toBe(true)})});


describe("moderation and timer boundaries",()=>{
 it("holds Arabic and Persian number fragments",()=>{expect(moderateConversation([],"٠٥٩").status).toBe("pending_moderation");expect(moderateConversation([],"۰۵۹۱۲۳۴۵۶۷").status).toBe("pending_moderation")});
 it("removes invisible separators in contact numbers",()=>expect(moderateConversation([],"٠٥٩\u200b١٢٣٤٥٦٧").status).toBe("pending_moderation"));
 it("does not hold ordinary conversation after a previous contact warning",()=>expect(moderateConversation([{body:"mail@example.com",createdAt:new Date()}],"The revised draft is ready.").status).toBe("delivered"));
 it("closes the appeal window exactly at twelve hours",()=>expect(canAppeal(new Date("2026-01-01T00:00:00Z"),new Date("2026-01-01T12:00:00Z"),0)).toBe(false));
});
