import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
const mocks=vi.hoisted(()=>({fetch:vi.fn(),connect:vi.fn(),send:vi.fn(),toolResponse:vi.fn(),close:vi.fn(),content:vi.fn()}));
vi.mock('@/lib/api-fetch',()=>({apiFetch:mocks.fetch}));
vi.mock('@google/genai',()=>({GoogleGenAI:class{live={connect:mocks.connect}}}));
import {LiveVoiceSession,pcm16,mergeTranscript} from '@/lib/live-voice';
let callbacks:{onmessage:(v:unknown)=>void},track:{stop:ReturnType<typeof vi.fn>;enabled:boolean},nodes:{stop:ReturnType<typeof vi.fn>;onended:null|(()=>void);disconnect:ReturnType<typeof vi.fn>}[];
function fixture(){
 track={stop:vi.fn(),enabled:true};nodes=[];
 const processor={connect:vi.fn(),disconnect:vi.fn(),onaudioprocess:null as null|((event:unknown)=>void)},context={sampleRate:16000,currentTime:0,state:'running',destination:{},createMediaStreamSource:()=>({connect:vi.fn(),disconnect:vi.fn()}),createScriptProcessor:()=>processor,createBuffer:(_channels:number,n:number,rate:number)=>({duration:n/rate,getChannelData:()=>new Float32Array(n)}),createBufferSource:()=>{const node={buffer:null,connect:vi.fn(),disconnect:vi.fn(),start:vi.fn(),stop:vi.fn(),onended:null};nodes.push(node);return node},close:vi.fn().mockResolvedValue(undefined)};
 const events={state:vi.fn(),level:vi.fn(),transcript:vi.fn(),tool:vi.fn().mockResolvedValue({saved:true}),error:vi.fn(),ended:vi.fn()};
 return {events,context,processor,call:new LiveVoiceSession({getTracks:()=>[track],getAudioTracks:()=>[track]} as unknown as MediaStream,context as unknown as AudioContext,events)};
}
beforeEach(()=>{vi.resetAllMocks();vi.useFakeTimers();mocks.fetch.mockResolvedValue({ok:true,json:async()=>({token:'ephemeral',model:'model',apiVersion:'v1alpha',config:{},durationSeconds:300})});mocks.connect.mockImplementation(async(config)=>{callbacks=config.callbacks;return {sendRealtimeInput:mocks.send,sendToolResponse:mocks.toolResponse,sendClientContent:mocks.content,close:mocks.close}})});
afterEach(()=>{vi.useRealTimers()});
describe('native live audio',()=>{
 it('encodes clipped little-endian PCM and merges partial transcripts',()=>{const view=new DataView(pcm16(new Float32Array([-2,0,2])).buffer);expect(view.getInt16(0,true)).toBe(-32768);expect(view.getInt16(4,true)).toBe(32767);expect(mergeTranscript('hello','hello there')).toBe('hello there');expect(mergeTranscript('hello',' there')).toBe('hello there')});
 it('streams microphone frames directly without waiting for transcription',async()=>{const f=fixture();await f.call.start('ar');callbacks.onmessage({setupComplete:{}});f.processor.onaudioprocess!({inputBuffer:{getChannelData:()=>new Float32Array([.1,.2])}} as never);expect(mocks.send).toHaveBeenCalledWith({audio:{data:expect.any(String),mimeType:'audio/pcm;rate=16000'}});f.call.close();expect(track.stop).toHaveBeenCalledOnce();expect(f.context.close).toHaveBeenCalledOnce()});
 it('stops queued audio immediately on interruption and mutes capture',async()=>{const f=fixture();await f.call.start('ar');callbacks.onmessage({setupComplete:{}});callbacks.onmessage({serverContent:{modelTurn:{parts:[{inlineData:{mimeType:'audio/pcm;rate=24000',data:'AAAAAA=='}}]}}});expect(nodes.length).toBe(1);callbacks.onmessage({serverContent:{interrupted:true}});expect(nodes[0].stop).toHaveBeenCalledOnce();f.call.setMuted(true);expect(track.enabled).toBe(false);expect(mocks.send).toHaveBeenCalledWith({audioStreamEnd:true});f.call.close()});
 it('uses the actual transcript rather than model-authored edit arguments',async()=>{const f=fixture();await f.call.start('ar');callbacks.onmessage({setupComplete:{}});callbacks.onmessage({serverContent:{inputTranscription:{text:'Change my experience to five years'}}});callbacks.onmessage({toolCall:{functionCalls:[{id:'tool1',name:'account_request',args:{request:'Delete somebody else'}}]}});await Promise.resolve();expect(f.events.tool).toHaveBeenCalledWith('Change my experience to five years',expect.any(AbortSignal));f.call.close()});
 it('closes a socket that resolves after the user has already stopped',async()=>{let resolve!:(v:unknown)=>void;mocks.connect.mockImplementation(()=>new Promise(r=>{resolve=r}));const f=fixture(),pending=f.call.start('ar');await vi.advanceTimersByTimeAsync(0);f.call.close();resolve({close:mocks.close});await pending;expect(mocks.close).toHaveBeenCalledOnce();expect(f.events.transcript).not.toHaveBeenCalled()});
});
