"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {isLocale,type Locale} from "@/lib/i18n";
type Finances={currency:string;gross_minor:number;platform_revenue_minor:number;payout_obligation_minor:number;refund_obligation_minor:number};
type Analytics={totalUsers:number;verifiedIndividuals:number;verifiedTeams:number;clients:number;activeProjects:number;completedProjects:number;disputes:number;finances:Finances[]|null;clientCountries:{country_code:string;count:number}[];topSkills:{slug:string;count:number}[];topCategories:{slug:string;count:number}[]};
const labels:Record<Locale,string[]>={
 en:["Overview","From","Through","Apply dates","Users registered","Verified professionals","Verified teams","Clients registered","Active projects","Completed projects","Open disputes","Currency","Project value","Net platform revenue","Unpaid worker entitlements","Refund obligations","Client countries","Top skills","Top categories","Could not load analytics","No records in this period","Verified totals reflect current active accounts. Financial obligations include amounts still frozen or awaiting eligibility.","Loading…"],
 ar:["نظرة عامة","من","حتى","تطبيق الفترة","المستخدمون المسجلون","المحترفون الموثّقون","الفرق الموثّقة","العملاء المسجلون","المشاريع النشطة","المشاريع المكتملة","النزاعات المفتوحة","العملة","قيمة المشاريع","صافي إيراد المنصة","مستحقات لم تُصرف","التزامات الاسترداد","دول العملاء","المهارات الأكثر شيوعًا","التصنيفات الأكثر طلبًا","تعذّر تحميل الإحصاءات","لا توجد سجلات في هذه الفترة","أعداد التحقق تخص الحسابات النشطة حاليًا. تشمل الالتزامات المالية المبالغ المجمّدة والتي لم يحن استحقاق صرفها.","جارٍ التحميل…"],
 tr:["Genel bakış","Başlangıç","Bitiş","Tarihleri uygula","Kayıtlı kullanıcılar","Doğrulanmış uzmanlar","Doğrulanmış ekipler","Kayıtlı müşteriler","Aktif projeler","Tamamlanan projeler","Açık anlaşmazlıklar","Para birimi","Proje değeri","Net platform geliri","Ödenmemiş hak edişler","İade yükümlülükleri","Müşteri ülkeleri","En yaygın beceriler","En çok talep edilen kategoriler","İstatistikler yüklenemedi","Bu dönemde kayıt yok","Doğrulama toplamları aktif hesapları gösterir. Yükümlülükler dondurulan veya henüz uygun olmayan tutarları da içerir.","Yükleniyor…"],
 es:["Resumen","Desde","Hasta","Aplicar fechas","Usuarios registrados","Profesionales verificados","Equipos verificados","Clientes registrados","Proyectos activos","Proyectos completados","Disputas abiertas","Moneda","Valor de proyectos","Ingresos netos de la plataforma","Importes pendientes a profesionales","Obligaciones de reembolso","Países de clientes","Habilidades principales","Categorías principales","No se pudieron cargar las estadísticas","Sin registros en este período","Los totales verificados reflejan las cuentas activas. Las obligaciones incluyen importes congelados o aún no habilitados para pago.","Cargando…"],
 fr:["Vue d’ensemble","Du","Au","Appliquer les dates","Utilisateurs inscrits","Professionnels vérifiés","Équipes vérifiées","Clients inscrits","Projets actifs","Projets terminés","Litiges ouverts","Devise","Valeur des projets","Revenu net de la plateforme","Droits des professionnels non versés","Obligations de remboursement","Pays des clients","Compétences principales","Catégories principales","Impossible de charger les statistiques","Aucun résultat pour cette période","Les totaux vérifiés reflètent les comptes actifs. Les obligations incluent les montants gelés ou pas encore admissibles au versement.","Chargement…"],
 de:["Übersicht","Von","Bis","Zeitraum anwenden","Registrierte Nutzer","Verifizierte Fachkräfte","Verifizierte Teams","Registrierte Kunden","Aktive Projekte","Abgeschlossene Projekte","Offene Streitfälle","Währung","Projektwert","Nettoerlös der Plattform","Unbezahlte Vergütungsansprüche","Erstattungspflichten","Kundenländer","Häufigste Fähigkeiten","Häufigste Kategorien","Statistiken konnten nicht geladen werden","Keine Einträge in diesem Zeitraum","Verifizierungszahlen beziehen sich auf aktive Konten. Verpflichtungen enthalten auch eingefrorene oder noch nicht fällige Beträge.","Wird geladen…"]};
export function AnalyticsPanel({locale}:{locale:string}){
 const c=labels[isLocale(locale)?locale:"en"],[data,setData]=useState<Analytics|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async(query="")=>{setBusy(true);setError("");try{const r=await fetch("/api/admin/analytics"+query);if(!r.ok)throw Error();setData(await r.json())}catch{setError(c[19])}finally{setBusy(false)}},[c]);
 useEffect(()=>{void load()},[load]);
 function filter(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),q=new URLSearchParams();if(f.get("from"))q.set("from",new Date(String(f.get("from"))+"T00:00:00Z").toISOString());if(f.get("to")){const end=new Date(String(f.get("to"))+"T00:00:00Z");end.setUTCDate(end.getUTCDate()+1);q.set("to",end.toISOString())}void load("?"+q)}
 const metricKeys=["totalUsers","verifiedIndividuals","verifiedTeams","clients","activeProjects","completedProjects","disputes"] as const;
 return <div className="grid"><h2>{c[0]}</h2><form className="card form-grid three" onSubmit={filter}><label>{c[1]}<input name="from" type="date"/></label><label>{c[2]}<input name="to" type="date"/></label><button className="btn" disabled={busy}>{c[3]}</button></form>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">{c[22]}</p>}{data&&<>
  <div className="dashboard-stats">{metricKeys.map((key,i)=><div className="stat-card" key={key}><span>{c[i+4]}</span><strong>{data[key]}</strong></div>)}</div>
  {data.finances&&<div className="card" style={{overflowX:"auto"}}><table><thead><tr>{c.slice(11,16).map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{data.finances.map(f=><tr key={f.currency}><th>{f.currency}</th>{[f.gross_minor,f.platform_revenue_minor,f.payout_obligation_minor,f.refund_obligation_minor].map((v,i)=><td key={i}>{new Intl.NumberFormat(locale,{style:"currency",currency:f.currency}).format(v/100)}</td>)}</tr>)}</tbody></table>{!data.finances.length&&<p>{c[20]}</p>}</div>}
  <p className="muted">{c[21]}</p><div className="form-grid three">{[data.clientCountries.map(v=>[v.country_code,v.count] as const),data.topSkills.map(v=>[v.slug,v.count] as const),data.topCategories.map(v=>[v.slug,v.count] as const)].map((rows,i)=><div className="card" key={i}><h3>{c[16+i]}</h3>{rows.length?rows.map(([name,count])=><p key={name}>{name}: <strong>{count}</strong></p>):<p>{c[20]}</p>}</div>)}</div>
 </>}</div>;
}
