"use client";
import {FormEvent,useEffect,useState} from "react";

type Profile={id:string;account_type:string};
type Project={id:string;status:string;client_id:string;talent_id:string;profiles?:{display_name?:string}|null;talent?:{display_name?:string}|null};
type Review={id:string;project_id:string;author_id:string;subject_id:string;communication?:number|null;professionalism?:number|null;overall?:number|null;quality?:number|null;delivery?:number|null;clarity?:number|null;cooperation?:number|null;feedback?:string|null;moderation_status:string};

const Rating=({name,label}:{name:string;label:string})=><label>{label}<select name={name} defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} ★</option>)}</select></label>;

export function ReviewsPanel({locale="en"}:{locale?:string}){
  const ar=locale==="ar",[me,setMe]=useState<Profile|null>(null),[projects,setProjects]=useState<Project[]>([]),[items,setItems]=useState<Review[]>([]),[message,setMessage]=useState("");
  async function load(){const [p,pr,r]=await Promise.all([fetch("/api/profile"),fetch("/api/projects"),fetch("/api/reviews")]);if(p.ok)setMe(await p.json());if(pr.ok)setProjects(await pr.json());if(r.ok)setItems(await r.json())}
  useEffect(()=>{void load()},[]);
  const completed=projects.filter(p=>["completed","payout_pending","paid"].includes(p.status));
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),project=completed.find(p=>p.id===String(f.get("projectId")));if(!project||!me)return;const subjectId=project.client_id===me.id?project.talent_id:project.client_id;const isClient=project.client_id===me.id;const val=(k:string)=>Number(f.get(k)||5);const body={projectId:project.id,subjectId,communication:val("communication"),professionalism:val("professionalism"),overall:val("overall"),quality:isClient?val("quality"):undefined,delivery:isClient?val("delivery"):undefined,clarity:!isClient?val("clarity"):undefined,cooperation:!isClient?val("cooperation"):undefined,feedback:f.get("feedback")};const r=await fetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?(ar?"تم إرسال التقييم.":"Review submitted."):(ar?"التقييم متاح فقط بعد اكتمال المشروع، ولكل طرف تقييم واحد لكل مشروع.":"Reviews are available only after completion, one per party per project."));if(r.ok){e.currentTarget.reset();await load()}}
  return <div className="grid">
    <form className="card grid" onSubmit={submit}><h2>{ar?"اكتب تقييمًا":"Leave a review"}</h2><label>{ar?"المشروع المكتمل":"Completed project"}<select name="projectId" required><option value="">{ar?"اختر مشروعًا":"Choose project"}</option>{completed.map(p=><option key={p.id} value={p.id}>{p.client_id===me?.id?(p.talent?.display_name??p.id):(p.profiles?.display_name??p.id)}</option>)}</select></label><div className="form-grid three"><Rating name="communication" label={ar?"التواصل":"Communication"}/><Rating name="professionalism" label={ar?"الاحترافية":"Professionalism"}/><Rating name="overall" label={ar?"التقييم العام":"Overall"}/></div>{me?.account_type==="client"?<div className="form-grid two"><Rating name="quality" label={ar?"الجودة":"Quality"}/><Rating name="delivery" label={ar?"التسليم":"Delivery"}/></div>:<div className="form-grid two"><Rating name="clarity" label={ar?"وضوح المتطلبات":"Clarity"}/><Rating name="cooperation" label={ar?"التعاون":"Cooperation"}/></div>}<label>{ar?"ملاحظات مكتوبة":"Written feedback"}<textarea name="feedback" rows={5}/></label><button className="btn">{ar?"إرسال التقييم":"Submit review"}</button><p role="status">{message}</p></form>
    <div className="grid"><h2>{ar?"التقييمات":"Reviews"}</h2>{items.length?items.map(x=><article className="card review-card" key={x.id}><div className="card-head"><span className="badge">{x.author_id===me?.id?(ar?"كتبتَه":"Written by you"):(ar?"استلمتَه":"Received")}</span><strong>★ {x.overall??"—"}/5</strong></div><div className="rating-grid"><span>{ar?"التواصل":"Communication"} <b>{x.communication??"—"}</b></span><span>{ar?"الاحترافية":"Professionalism"} <b>{x.professionalism??"—"}</b></span>{x.quality&&<span>{ar?"الجودة":"Quality"} <b>{x.quality}</b></span>}{x.delivery&&<span>{ar?"التسليم":"Delivery"} <b>{x.delivery}</b></span>}{x.clarity&&<span>{ar?"الوضوح":"Clarity"} <b>{x.clarity}</b></span>}{x.cooperation&&<span>{ar?"التعاون":"Cooperation"} <b>{x.cooperation}</b></span>}</div>{x.feedback&&<p>{x.feedback}</p>}</article>):<div className="empty">{ar?"لا توجد تقييمات بعد.":"No reviews yet."}</div>}</div>
  </div>
}
