import {emailEnvelopeSchema,type EmailEnvelope,type EmailKind} from "@/domain/email";
import {isLocale,type Locale} from "@/lib/i18n";
type EmailCopy={subjects:Record<EmailKind,string>;general:string;urgent:string;security:string;cta:string};
const copy:Record<Locale,EmailCopy>={
 en:{subjects:{verification_status:"Verification update",payment_confirmation:"Payment update",payout_status:"Payout update",dispute_update:"Dispute update",appeal_update:"Appeal update",security_alert:"Security alert",account_notice:"Account notice"},general:"There is an important update on your GazaWorks account. Sign in to review the details.",urgent:"There is an important dispute or appeal update. Sign in promptly to review its status and any action deadline.",security:"An important security event was recorded on your GazaWorks account. Sign in to review your recent account activity.",cta:"Open GazaWorks"},
 ar:{subjects:{verification_status:"تحديث التحقق",payment_confirmation:"تحديث الدفع",payout_status:"تحديث صرف المستحقات",dispute_update:"تحديث النزاع",appeal_update:"تحديث الاستئناف",security_alert:"تنبيه أمني",account_notice:"إشعار الحساب"},general:"يوجد تحديث مهم في حسابك على GazaWorks. سجّل الدخول لمراجعة التفاصيل.",urgent:"يوجد تحديث مهم على نزاع أو استئناف. سجّل الدخول في أقرب وقت لمراجعة الحالة وأي مهلة لاتخاذ إجراء.",security:"تم تسجيل حدث أمني مهم في حسابك على GazaWorks. سجّل الدخول لمراجعة النشاط الأخير لحسابك.",cta:"فتح GazaWorks"},
 tr:{subjects:{verification_status:"Doğrulama güncellemesi",payment_confirmation:"Ödeme güncellemesi",payout_status:"Kazanç ödemesi güncellemesi",dispute_update:"Uyuşmazlık güncellemesi",appeal_update:"İtiraz güncellemesi",security_alert:"Güvenlik uyarısı",account_notice:"Hesap bildirimi"},general:"GazaWorks hesabınızda önemli bir güncelleme var. Ayrıntıları incelemek için giriş yapın.",urgent:"Bir uyuşmazlık veya itiraz hakkında önemli bir güncelleme var. Durumu ve varsa işlem süresini incelemek için kısa sürede giriş yapın.",security:"GazaWorks hesabınızda önemli bir güvenlik olayı kaydedildi. Son hesap etkinliğinizi incelemek için giriş yapın.",cta:"GazaWorks'ü aç"},
 es:{subjects:{verification_status:"Actualización de verificación",payment_confirmation:"Actualización de pago",payout_status:"Actualización de abono",dispute_update:"Actualización de disputa",appeal_update:"Actualización de apelación",security_alert:"Alerta de seguridad",account_notice:"Aviso de cuenta"},general:"Hay una actualización importante en tu cuenta de GazaWorks. Inicia sesión para consultar los detalles.",urgent:"Hay una actualización importante sobre una disputa o apelación. Inicia sesión pronto para consultar su estado y cualquier plazo de actuación.",security:"Se ha registrado un evento de seguridad importante en tu cuenta de GazaWorks. Inicia sesión para revisar la actividad reciente.",cta:"Abrir GazaWorks"},
 fr:{subjects:{verification_status:"Mise à jour de la vérification",payment_confirmation:"Mise à jour du paiement",payout_status:"Mise à jour du versement",dispute_update:"Mise à jour du litige",appeal_update:"Mise à jour du recours",security_alert:"Alerte de sécurité",account_notice:"Avis concernant le compte"},general:"Une mise à jour importante concerne votre compte GazaWorks. Connectez-vous pour consulter les détails.",urgent:"Une mise à jour importante concerne un litige ou un recours. Connectez-vous rapidement pour consulter son statut et les éventuelles échéances.",security:"Un événement de sécurité important a été enregistré sur votre compte GazaWorks. Connectez-vous pour examiner votre activité récente.",cta:"Ouvrir GazaWorks"},
 de:{subjects:{verification_status:"Aktualisierung der Verifizierung",payment_confirmation:"Zahlungsaktualisierung",payout_status:"Auszahlungsaktualisierung",dispute_update:"Aktualisierung zum Streitfall",appeal_update:"Aktualisierung zum Einspruch",security_alert:"Sicherheitswarnung",account_notice:"Kontobenachrichtigung"},general:"Es gibt eine wichtige Aktualisierung zu Ihrem GazaWorks-Konto. Melden Sie sich an, um die Details zu prüfen.",urgent:"Es gibt eine wichtige Aktualisierung zu einem Streitfall oder Einspruch. Melden Sie sich zeitnah an, um den Status und mögliche Fristen zu prüfen.",security:"Ein wichtiges Sicherheitsereignis wurde in Ihrem GazaWorks-Konto erfasst. Melden Sie sich an, um die letzten Kontoaktivitäten zu prüfen.",cta:"GazaWorks öffnen"}
};
export type StoredEmailTemplate={subject:string;body_html:string;body_text:string|null;enabled:boolean};
export function escapeEmailHtml(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]??char));}
export function renderEmail(input:{kind:EmailKind;locale:string;recipient:string;from:string;origin:string;template?:StoredEmailTemplate}):EmailEnvelope|null{
 if(input.template?.enabled===false)return null;
 const locale=isLocale(input.locale)?input.locale:"en",c=copy[locale];
 const path=input.kind==="security_alert"?"security":input.kind==="verification_status"?"verification":input.kind==="dispute_update"||input.kind==="appeal_update"?"disputes":input.kind==="payout_status"||input.kind==="payment_confirmation"?"payments":"notifications";
 const url=new URL(`/${locale}/dashboard/${path}`,input.origin).toString();
 const message=input.kind==="security_alert"?c.security:input.kind==="dispute_update"||input.kind==="appeal_update"?c.urgent:c.general;
 const values:Record<string,string>={dashboard_url:url,message,subject:c.subjects[input.kind],platform_name:"GazaWorks"};
 function interpolate(template:string,html:boolean){return template.replace(/{{\s*([a-z_]+)\s*}}/g,(_,key:string)=>{if(!(key in values))throw new Error("unknown_template_placeholder");return html?escapeEmailHtml(values[key]):values[key];});}
 const subject=input.template?interpolate(input.template.subject,false):`GazaWorks — ${c.subjects[input.kind]}`;
 const body=input.template?interpolate(input.template.body_html,true):`<h1>${escapeEmailHtml(c.subjects[input.kind])}</h1><p>${escapeEmailHtml(message)}</p>`;
 const html=`<!doctype html><html lang="${locale}" dir="${locale==="ar"?"rtl":"ltr"}"><head><meta charset="utf-8"></head><body style="font-family:Arial,sans-serif;line-height:1.7"><main style="max-width:560px;margin:24px auto;padding:24px">${body}<p><a href="${escapeEmailHtml(url)}">${escapeEmailHtml(c.cta)}</a></p></main></body></html>`;
 const text=(input.template?.body_text?interpolate(input.template.body_text,false):message)+"\n\n"+c.cta+": "+url;
 return emailEnvelopeSchema.parse({from:input.from,to:input.recipient,subject,html,text});
}
