import type { Locale } from "@/lib/i18n";

export const aiConsentCopy: Record<Locale, string> = {
  ar: "أوافق على إرسال نصي أو ملفي أو تسجيلي الصوتي إلى مزوّد ذكاء اصطناعي خارجي لإنشاء مسودة. عند استخدام Gemini المجاني، قد تستخدم Google البيانات لتحسين منتجاتها؛ لا ترسل أسرارًا أو وثائق هوية أو معلومات حساسة. تبقى مسودات الملفات للمراجعة؛ ويمكن للمساعد تنفيذ أوامري الصريحة لتعديل ملفي مع إمكانية التراجع.",
  en: "I agree to send my text, file or voice recording to an external AI provider for a draft. On Gemini's free tier, Google may use data to improve its products; do not send secrets, identity documents or sensitive information. File drafts remain reviewable; the assistant can execute my explicit profile-edit requests with an undo option.",
  tr: "Metnimi, dosyamı veya ses kaydımı taslak için harici bir yapay zekâ sağlayıcısına göndermeyi kabul ediyorum. Gemini'nin ücretsiz sürümünde Google verileri ürünlerini geliştirmek için kullanabilir; sır, kimlik belgesi veya hassas bilgi göndermeyin. Dosya taslakları incelemeye açık kalır; açık profil düzenleme isteklerim geri alma seçeneğiyle uygulanabilir.",
  es: "Acepto enviar mi texto, archivo o grabación de voz a un proveedor externo de IA para crear un borrador. En el nivel gratuito de Gemini, Google puede usar los datos para mejorar sus productos; no envíes secretos, documentos de identidad ni información sensible. Los borradores se revisan; mis solicitudes explícitas de edición del perfil pueden ejecutarse con opción de deshacer.",
  fr: "J'accepte l'envoi de mon texte, fichier ou enregistrement vocal à un fournisseur d'IA externe pour créer un brouillon. Avec l'offre gratuite de Gemini, Google peut utiliser les données pour améliorer ses produits ; n'envoyez aucun secret, document d'identité ou renseignement sensible. Les brouillons restent à valider ; mes demandes explicites de modification du profil peuvent être exécutées et annulées.",
  de: "Ich stimme zu, meinen Text, meine Datei oder meine Sprachaufnahme für einen Entwurf an einen externen KI-Anbieter zu senden. Bei Gemini im kostenlosen Tarif kann Google Daten zur Produktverbesserung verwenden; senden Sie keine Geheimnisse, Ausweisdokumente oder sensiblen Informationen. Dateientwürfe bleiben prüfbar; ausdrückliche Profiländerungen können mit Rückgängig-Option ausgeführt werden.",
};

export const aiLoginNotice:Record<Locale,string>={
 ar:"بمتابعتك التسجيل أو الدخول توافق على معالجة رسائلك والتسجيلات الصوتية والملفات التي تختار إرسالها للذكاء الاصطناعي لدى مزود خارجي. قد تستخدم Google البيانات لتحسين منتجاتها عند استخدام Gemini المجاني. تُحفظ موافقتك مرة واحدة، ويمكنك تعطيل المشاركة من إعدادات المساعد.",
 en:"By continuing to sign in or register, you agree that messages, voice recordings and files you choose to send to AI are processed by an external provider. Google may use data to improve products on Gemini's free tier. Your preference is saved once and can be disabled in assistant settings.",
 tr:"Girişe veya kayda devam ederek yapay zekâya gönderdiğiniz mesajların, ses kayıtlarının ve dosyaların harici bir sağlayıcıda işlenmesini kabul edersiniz. Google ücretsiz Gemini verilerini ürün geliştirmede kullanabilir. Tercih bir kez kaydedilir ve asistan ayarlarından kapatılabilir.",
 es:"Al continuar con el acceso o registro, aceptas que un proveedor externo procese los mensajes, grabaciones de voz y archivos que envíes a la IA. Google puede usar datos de Gemini gratuito para mejorar productos. La preferencia se guarda una vez y puede desactivarse en los ajustes del asistente.",
 fr:"En poursuivant la connexion ou l’inscription, vous acceptez le traitement des messages, enregistrements vocaux et fichiers envoyés à l’IA par un fournisseur externe. Google peut utiliser les données de Gemini gratuit pour améliorer ses produits. Le choix est enregistré une fois et peut être désactivé dans les paramètres de l’assistant.",
 de:"Mit Anmeldung oder Registrierung stimmen Sie der Verarbeitung der an KI gesendeten Nachrichten, Sprachaufnahmen und Dateien durch einen externen Anbieter zu. Google kann Daten des kostenlosen Gemini zur Produktverbesserung nutzen. Die Einstellung wird einmal gespeichert und kann im Assistenten deaktiviert werden."
};
