-- Filename generated by Supabase CLI 2.117.0 (migration-tools workflow).
-- Queue only new important events; no backfill or network calls from PostgreSQL.
create table private.email_outbox(
 id uuid primary key default gen_random_uuid(),
 notification_id uuid unique not null references public.notifications(id),
 profile_id uuid not null references public.profiles(id),
 recipient text not null, locale text not null,
 kind text not null check(kind in('verification_status','payment_confirmation','payout_status','dispute_update','appeal_update','security_alert','account_notice')),
 status text not null default 'queued' check(status in('queued','processing','sent','failed','suppressed','review_required')),
 attempts integer not null default 0 check(attempts between 0 and 10),
 max_attempts integer not null default 5 check(max_attempts between 1 and 10),
 next_attempt_at timestamptz not null default now(), first_attempt_at timestamptz,
 claim_token uuid, claimed_until timestamptz, envelope jsonb,
 provider_id text unique, delivery_status text, last_error_code text,
 sent_at timestamptz, created_at timestamptz not null default now()
);
create index email_outbox_pending on private.email_outbox(next_attempt_at,created_at) where status='queued';
create index email_outbox_lease on private.email_outbox(claimed_until) where status='processing';
create index email_outbox_profile on private.email_outbox(profile_id);
create table private.email_delivery_events(
 id text primary key, provider_id text not null, event_type text not null,
 occurred_at timestamptz not null, received_at timestamptz not null default now()
);
create index email_delivery_provider on private.email_delivery_events(provider_id,occurred_at desc);
create table private.email_suppressions(recipient text primary key,reason text not null,created_at timestamptz not null default now());
alter table private.email_outbox enable row level security;
alter table private.email_delivery_events enable row level security;
alter table private.email_suppressions enable row level security;
revoke all on private.email_outbox,private.email_delivery_events,private.email_suppressions from public,anon,authenticated;
grant select,insert,update on private.email_outbox,private.email_delivery_events,private.email_suppressions to service_role;
revoke insert,update,delete on public.notifications from authenticated,anon;
grant update(read_at) on public.notifications to authenticated;

-- A narrow helper avoids granting the worker access to the full Auth user table.
create function private.confirmed_email(user_id uuid) returns text language sql stable security definer set search_path='' as $$
 select lower(email) from auth.users where id=user_id and email_confirmed_at is not null and email is not null and email<>''
$$;
create function private.enqueue_important_email() returns trigger language plpgsql set search_path='' as $$
declare email_kind text; address text; language text; begin
 if new.data->>'simulated'='true' then return new; end if;
 if new.category in('payments','payouts','disputes','appeals') and exists(
   select 1 from public.transactions t join public.payments p on p.transaction_id=t.id
   where t.project_id::text=new.data->>'projectId' and p.simulated
 ) then return new; end if;
 email_kind:=case new.category when 'security' then 'security_alert' when 'payments' then 'payment_confirmation'
   when 'payouts' then 'payout_status' when 'disputes' then 'dispute_update' when 'appeals' then 'appeal_update'
   when 'account' then 'account_notice' when 'verification' then 'verification_status' end;
 if email_kind is null then return new; end if;
 if new.category='verification' and coalesce(new.data->>'status','') not in('verified','rejected','changes_requested','suspended') then return new; end if;
 address:=private.confirmed_email(new.profile_id);
 select case when locale in('ar','en','tr','es','fr','de') then locale else 'en' end into language from public.profiles where id=new.profile_id;
 insert into private.email_outbox(notification_id,profile_id,recipient,locale,kind,status,last_error_code)
 values(new.id,new.profile_id,coalesce(address,''),language,email_kind,case when address is null then 'suppressed' else 'queued' end,case when address is null then 'address_unconfirmed' end)
 on conflict(notification_id) do nothing;
 return new;
end$$;
create trigger important_email after insert on public.notifications for each row execute function private.enqueue_important_email();

-- Notices are in the same transaction as the underlying state change.
create function private.publish_important_notice() returns trigger language plpgsql set search_path='' as $$
declare p public.projects; category text; entity uuid; state text; simulated boolean; begin
 if tg_table_name='profiles' then
   if new.account_status is distinct from old.account_status then
     insert into public.notifications(profile_id,category,title,body,data) values(new.id,'account','Account status updated','Review the latest account notice in GazaWorks.',jsonb_build_object('status',new.account_status));
   end if;
   return new;
 end if;
 if tg_op='UPDATE' and new.status is not distinct from old.status then return new; end if;
 entity:=new.id; state:=new.status::text;
 if tg_table_name='payouts' then
   select j.* into p from public.projects j join public.transactions t on t.project_id=j.id where t.id=new.transaction_id;
   category:='payouts';
 elsif tg_table_name='disputes' then
   select * into p from public.projects where id=new.project_id; category:='disputes';
 else
   select j.* into p from public.projects j join public.disputes d on d.project_id=j.id where d.id=new.dispute_id; category:='appeals';
 end if;
 select exists(select 1 from public.transactions t join public.payments m on m.transaction_id=t.id where t.project_id=p.id and m.simulated) into simulated;
 insert into public.notifications(profile_id,category,title,body,data)
 values(p.talent_id,category,'Important project update','Review the current status and any action deadline in GazaWorks.',jsonb_build_object('projectId',p.id,'entityId',entity,'status',state,'simulated',simulated));
 if category<>'payouts' then
   insert into public.notifications(profile_id,category,title,body,data)
   values(p.client_id,category,'Important project update','Review the current status and any action deadline in GazaWorks.',jsonb_build_object('projectId',p.id,'entityId',entity,'status',state,'simulated',simulated));
 end if;
 return new;
end$$;
create trigger payout_notice after insert or update on public.payouts for each row execute function private.publish_important_notice();
create trigger dispute_notice after insert or update on public.disputes for each row execute function private.publish_important_notice();
create trigger appeal_notice after insert or update on public.appeals for each row execute function private.publish_important_notice();
create trigger account_notice after update of account_status on public.profiles for each row execute function private.publish_important_notice();

create function public.gw_claim_emails(batch_size integer default 3) returns jsonb language plpgsql set search_path='' as $$
declare jobs jsonb; begin
 if batch_size is null or batch_size not between 1 and 10 then raise exception 'invalid_batch_size'; end if;
 -- Resend guarantees idempotency for 24 hours. Leave one hour of safety margin.
 update private.email_outbox set status='review_required',last_error_code='idempotency_window_expired',claim_token=null,claimed_until=null
 where first_attempt_at<=now()-interval '23 hours' and (status='queued' or status='processing' and claimed_until<now());
 update private.email_outbox set status=case when attempts<max_attempts then 'queued' else 'failed' end,
   last_error_code='worker_lease_expired',claim_token=null,claimed_until=null
 where status='processing' and claimed_until<now();
 update private.email_outbox q set status='suppressed',last_error_code='recipient_unavailable'
 where q.status='queued' and (q.recipient is distinct from private.confirmed_email(q.profile_id) or exists(select 1 from private.email_suppressions s where s.recipient=q.recipient));
 with candidates as(
   select id from private.email_outbox where status='queued' and next_attempt_at<=now() and attempts<max_attempts
   order by created_at,id for update skip locked limit batch_size
 ), claimed as(
   update private.email_outbox q set status='processing',attempts=attempts+1,first_attempt_at=coalesce(first_attempt_at,now()),
     claim_token=gen_random_uuid(),claimed_until=now()+interval '2 minutes'
   from candidates c where q.id=c.id returning q.id,q.claim_token,q.kind,q.locale,q.recipient,q.envelope
 ) select coalesce(jsonb_agg(to_jsonb(claimed)),'[]') into jobs from claimed;
 return jobs;
end$$;

create function public.gw_prepare_email(outbox_id uuid,token uuid,payload jsonb) returns jsonb language plpgsql set search_path='' as $$
declare q private.email_outbox; begin
 select * into q from private.email_outbox where id=outbox_id for update;
 if q.id is null or q.status<>'processing' or q.claim_token is distinct from token or q.claimed_until<=now() then raise exception 'invalid_email_claim'; end if;
 if q.recipient is distinct from private.confirmed_email(q.profile_id) or exists(select 1 from private.email_suppressions where recipient=q.recipient) then raise exception 'recipient_unavailable'; end if;
 if q.envelope is not null then return q.envelope; end if;
 if payload is null or jsonb_typeof(payload)<>'object' or octet_length(payload::text)>210000
   or (select count(*) from jsonb_object_keys(payload))<>5
   or not payload ?& array['from','to','subject','html','text']
   or exists(select 1 from jsonb_each(payload) x where jsonb_typeof(x.value)<>'string')
   or payload->>'to' is distinct from q.recipient
   or length(payload->>'subject') not between 1 and 250 or payload->>'subject' ~ E'[\r\n]'
   or length(payload->>'from') not between 3 and 320 or payload->>'from' ~ E'[\r\n]'
   or length(payload->>'html') not between 1 and 100000 or length(payload->>'text') not between 1 and 100000 then raise exception 'invalid_email_envelope'; end if;
 update private.email_outbox set envelope=payload where id=outbox_id;
 return payload;
end$$;

create function private.apply_email_delivery(message_id text) returns void language plpgsql set search_path='' as $$
declare q private.email_outbox; event text; begin
 select * into q from private.email_outbox where provider_id=message_id for update;
 if q.id is null then return; end if;
 select event_type into event from private.email_delivery_events where provider_id=message_id
 order by case event_type when 'complained' then 5 when 'bounced' then 4 when 'suppressed' then 3 when 'failed' then 2 else 1 end desc,occurred_at desc limit 1;
 if event is null then return; end if;
 update private.email_outbox set delivery_status=event where id=q.id;
 if event in('complained','bounced','suppressed') then
   insert into private.email_suppressions(recipient,reason) values(q.recipient,event)
   on conflict(recipient) do update set reason=excluded.reason;
 end if;
end$$;

create function public.gw_finish_email(outbox_id uuid,token uuid,outcome text,message_id text default null,error_code text default null) returns jsonb language plpgsql set search_path='' as $$
declare q private.email_outbox; state text; begin
 if outcome is null or outcome not in('accepted','retry','failed','suppressed') then raise exception 'invalid_email_outcome'; end if;
 if error_code is not null and error_code !~ '^[a-z0-9_]{1,80}$' then raise exception 'invalid_error_code'; end if;
 if outcome='accepted' then
   if message_id is null or message_id !~ '^[a-zA-Z0-9_-]{1,200}$' then raise exception 'provider_confirmation_required'; end if;
   -- Same lock ordering as callbacks, including callbacks arriving before send returns.
   perform pg_advisory_xact_lock(hashtextextended('email-delivery:'||message_id,0));
 end if;
 select * into q from private.email_outbox where id=outbox_id for update;
 if q.id is null or q.status<>'processing' or q.claim_token is distinct from token or q.claimed_until<=now() then raise exception 'invalid_email_claim'; end if;
 if outcome='accepted' and q.envelope is null then raise exception 'prepared_envelope_required'; end if;
 state:=case outcome when 'accepted' then 'sent' when 'retry' then case when q.attempts<q.max_attempts then 'queued' else 'failed' end else outcome end;
 update private.email_outbox set status=state,claim_token=null,claimed_until=null,last_error_code=case when outcome='accepted' then null else error_code end,
   provider_id=case when outcome='accepted' then message_id else provider_id end,sent_at=case when outcome='accepted' then now() else sent_at end,
   next_attempt_at=now()+make_interval(secs=>least(21600,60*power(2,q.attempts))::integer) where id=q.id;
 if outcome='accepted' then perform private.apply_email_delivery(message_id); end if;
 return jsonb_build_object('status',state);
end$$;

create function public.gw_email_delivery(event_id text,message_id text,event_type text,event_time timestamptz) returns jsonb language plpgsql set search_path='' as $$
begin
 if event_id is null or length(event_id) not between 1 and 200 or message_id is null or message_id !~ '^[a-zA-Z0-9_-]{1,200}$'
   or event_type is null or event_type not in('delivered','bounced','complained','suppressed','failed') or event_time is null then raise exception 'invalid_email_event'; end if;
 perform pg_advisory_xact_lock(hashtextextended('email-delivery:'||message_id,0));
 insert into private.email_delivery_events(id,provider_id,event_type,occurred_at) values(event_id,message_id,event_type,event_time) on conflict(id) do nothing;
 perform private.apply_email_delivery(message_id);
 return '{"ok":true}';
end$$;

create function public.gw_email_queue(actor uuid,page integer default 0,filter_status text default null) returns jsonb language plpgsql set search_path='' as $$
declare records jsonb; counts jsonb; total bigint; begin
 perform private.require_actor(actor,'email.manage');
 if page is null or page not between 0 and 10000 or filter_status is not null and filter_status not in('queued','processing','sent','failed','suppressed','review_required') then raise exception 'invalid_request'; end if;
 select count(*) into total from private.email_outbox where filter_status is null or status=filter_status;
 select coalesce(jsonb_object_agg(status,n),'{}') into counts from(select status,count(*) n from private.email_outbox group by status)c;
 select coalesce(jsonb_agg(to_jsonb(r)),'[]') into records from(
   select q.id,p.display_name,q.kind,q.locale,q.status,q.attempts,q.max_attempts,q.next_attempt_at,q.created_at,q.sent_at,q.provider_id,q.delivery_status,q.last_error_code,
     (q.status='failed' and q.attempts<10 and q.first_attempt_at>now()-interval '23 hours' and q.recipient=private.confirmed_email(q.profile_id) and not exists(select 1 from private.email_suppressions s where s.recipient=q.recipient)) can_retry
   from private.email_outbox q join public.profiles p on p.id=q.profile_id
   where filter_status is null or q.status=filter_status order by q.created_at desc,q.id desc offset page*25 limit 25
 )r;
 return jsonb_build_object('records',records,'counts',counts,'total',total,'page',page);
end$$;

create function public.gw_retry_email(actor uuid,outbox_id uuid) returns jsonb language plpgsql set search_path='' as $$
declare q private.email_outbox; begin
 perform private.require_actor(actor,'email.manage');
 select * into q from private.email_outbox where id=outbox_id for update;
 if q.id is null or q.status<>'failed' or q.attempts>=10 or q.first_attempt_at is null or q.first_attempt_at<=now()-interval '23 hours' then raise exception 'email_retry_not_allowed'; end if;
 if q.recipient is distinct from private.confirmed_email(q.profile_id) or exists(select 1 from private.email_suppressions where recipient=q.recipient) then raise exception 'recipient_unavailable'; end if;
 update private.email_outbox set status='queued',max_attempts=least(10,greatest(max_attempts,q.attempts+1)),next_attempt_at=now() where id=q.id;
 insert into public.audit_logs(actor_id,action,entity_type,entity_id,new_data) values(actor,'email.retry','email_outbox',q.id::text,jsonb_build_object('previous_status',q.status,'attempts',q.attempts));
 return '{"ok":true}';
end$$;

revoke all on function private.confirmed_email(uuid),private.enqueue_important_email(),private.publish_important_notice(),private.apply_email_delivery(text) from public,anon,authenticated;
grant execute on function private.confirmed_email(uuid),private.enqueue_important_email(),private.publish_important_notice(),private.apply_email_delivery(text) to service_role;
revoke all on function public.gw_claim_emails(integer),public.gw_prepare_email(uuid,uuid,jsonb),public.gw_finish_email(uuid,uuid,text,text,text),public.gw_email_delivery(text,text,text,timestamptz),public.gw_email_queue(uuid,integer,text),public.gw_retry_email(uuid,uuid) from public,anon,authenticated;
grant execute on function public.gw_claim_emails(integer),public.gw_prepare_email(uuid,uuid,jsonb),public.gw_finish_email(uuid,uuid,text,text,text),public.gw_email_delivery(text,text,text,timestamptz),public.gw_email_queue(uuid,integer,text),public.gw_retry_email(uuid,uuid) to service_role;
