'use client';
import {useState} from 'react';
import {roles,sectors,orderedTools,languageNames,proficiency,findRole,westernDigits,emailPattern,localPhonePattern,languageLabel,proficiencyLabel} from '@/domain/professional-data';
import {professionalCopy} from '@/lib/professional-copy';
import {nearestGazaTown} from '@/domain/gaza-location';
export function RoleSelect({locale,name='professionalTitle',value,onChange,required=true}:{locale:string;name?:string;value:string;onChange:(v:string)=>void;required?:boolean}){
 const c=professionalCopy(locale),[query,setQuery]=useState('');
 const current=findRole(value);const options=roles.filter(r=>`${r.ar} ${r.en} ${r.aliases}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="grid professional-control"><label>{c.search}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} autoComplete="off"/></label><select aria-label={c.chooseRole} name={name} required={required} value={current?.en??value} onChange={e=>onChange(e.target.value)}><option value="">{c.chooseRole}</option>{value&&!current&&<option value={value}>{value}</option>}{sectors.map(s=><optgroup key={s[0]} label={`${s[1]} / ${s[2]}`}>{options.filter(r=>r.sector===s[0]||r.id===current?.id).map(r=><option key={r.id} value={r.en}>{r.ar} / {r.en}</option>)}</optgroup>)}</select></div>
}
export function TagSelect({locale,name,value,onChange,title,options,display}:{locale:string;name:string;value:string[];onChange:(v:string[])=>void;title:string;options:readonly string[];display?:(v:string)=>string}){
 const [query,setQuery]=useState(''),c=professionalCopy(locale),visible=[...new Set([...value,...options])].filter(t=>(t+' '+(display?.(t)??'')).toLowerCase().includes(query.toLowerCase()));
 return <fieldset className="tag-select"><legend>{title}</legend><input name={name} type="hidden" value={value.join(', ')}/><input type="search" aria-label={c.search} placeholder={c.search} value={query} onChange={e=>setQuery(e.target.value)}/><div className="tag-options">{visible.map(t=><button type="button" className={value.includes(t)?'tag-button selected':'tag-button'} aria-pressed={value.includes(t)} key={t} onClick={()=>onChange(value.includes(t)?value.filter(x=>x!==t):[...value,t])}>{display?.(t)??t}</button>)}</div></fieldset>
}
export function ToolsSelect({locale,title,value,onChange,name='tools'}:{locale:string;title:string;value:string[];onChange:(v:string[])=>void;name?:string}){return <TagSelect locale={locale} name={name} title={professionalCopy(locale).tools} options={orderedTools(title)} value={value} onChange={onChange}/>}
export function FieldSelect({locale,value,onChange,name='preferredFields'}:{locale:string;value:string[];onChange:(v:string[])=>void;name?:string}){return <TagSelect locale={locale} name={name} title={professionalCopy(locale).fields} options={sectors.map(s=>s[2])} display={v=>{const sector=sectors.find(s=>s[2]===v);return locale==='ar'&&sector?sector[1]:v}} value={value.map(v=>sectors.find(s=>s[1]===v||s[2]===v)?.[2]??v)} onChange={onChange}/>}
function languageRows(values:string[]){return values.map(v=>{const [code,level]=v.split(':');const known=languageNames.find(l=>l[0]===code||[l[1],l[2]].some(t=>v.toLowerCase().includes(t.toLowerCase())));return known?{code:known[0] as string,level:proficiency.some(p=>p[0]===level)?level:'good'}:{code:v,level:'good'}})}
export function LanguagesSelect({locale,value,onChange,name='languages'}:{locale:string;value:string[];onChange:(v:string[])=>void;name?:string}){
 const c=professionalCopy(locale),rows=languageRows(value);
 function update(index:number,code:string,level:string){onChange(rows.map((r,i)=>i===index?`${code}:${level}`:`${r.code}:${r.level}`))}
 return <fieldset className="tag-select"><legend>{c.languages}</legend><input type="hidden" name={name} value={rows.map(r=>`${r.code}:${r.level}`).join(', ')}/>{rows.map((r,i)=><div className="language-row" key={i}><select aria-label={c.chooseLanguage} value={r.code} onChange={e=>update(i,e.target.value,r.level)}>{!languageNames.some(l=>l[0]===r.code)&&<option value={r.code}>{r.code}</option>}{languageNames.map(l=><option key={l[0]} value={l[0]} disabled={rows.some((x,j)=>j!==i&&x.code===l[0])}>{languageLabel(l[0],locale)}</option>)}</select><select aria-label={c.level} value={r.level} onChange={e=>update(i,r.code,e.target.value)}>{proficiency.map(p=><option key={p[0]} value={p[0]}>{proficiencyLabel(p[0],locale)}</option>)}</select><button className="btn secondary" type="button" onClick={()=>onChange(value.filter((_,j)=>j!==i))}>{c.remove}</button></div>)}<button className="btn secondary" type="button" disabled={rows.length>=10} onClick={()=>{const l=languageNames.find(l=>!rows.some(r=>r.code===l[0]));if(l)onChange([...value,`${l[0]}:good`])}}>{c.addLanguage}</button></fieldset>
}
export function ContactInput({locale,kind,value,onChange,name,localPhone=true,required=true}:{locale:string;kind:'phone'|'email';value:string;onChange:(v:string)=>void;name:string;localPhone?:boolean;required?:boolean}){
 const c=professionalCopy(locale),[touched,setTouched]=useState(false),valid=kind==='email'?emailPattern.test(value):localPhone?localPhonePattern.test(value):Boolean(value.trim());
 const error=kind==='phone'?c.phoneError:!value?c.emailRequired:c.emailError;
 return <label>{kind==='phone'?c.phone:c.email}{required?' *':''}<input name={name} type={kind==='phone'?'tel':'email'} inputMode={kind==='phone'?'tel':'email'} autoComplete={kind==='phone'?'tel':'email'} required={required} dir="ltr" value={value} pattern={kind==='phone'&&localPhone?'05[0-9]{8}':kind==='email'?'[^\\s@]+@[^\\s@.]+(\\.[^\\s@.]+)+':undefined} maxLength={kind==='phone'?localPhone?10:40:180} aria-invalid={touched&&!valid} onBlur={()=>setTouched(true)} onChange={e=>{const v=westernDigits(e.target.value);onChange(v);setTouched(true)}} onInput={e=>{const el=e.currentTarget;const v=westernDigits(el.value);const ok=kind==='email'?emailPattern.test(v):localPhone?localPhonePattern.test(v):Boolean(v.trim());el.setCustomValidity((required&&!v)||v&&!ok?error:'')}} onInvalid={e=>e.currentTarget.setCustomValidity(error)}/>{touched&&!valid&&(required||value)&&<small className="error" role="alert">{error}</small>}</label>
}
export function LocationInput({locale,value,onChange}:{locale:string;value:string;onChange:(v:string)=>void}){
 const c=professionalCopy(locale),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function locate(){if(!navigator.geolocation){setError(c.locationError);return}setBusy(true);setError('');navigator.geolocation.getCurrentPosition(p=>{const name=nearestGazaTown(p.coords.latitude,p.coords.longitude,locale);if(name)onChange(name);else setError(c.noArea);setBusy(false)},()=>{setBusy(false);setError(c.locationError)},{timeout:12000,maximumAge:60000,enableHighAccuracy:false})}
 return <div className="grid professional-control"><input aria-label={locale==='ar'?'الموقع':'Location'} name="location" required maxLength={120} value={value} onChange={e=>onChange(e.target.value)}/><button type="button" className="btn secondary" disabled={busy} onClick={locate}>{busy?c.locating:c.locate}</button><small className="muted">{c.locationHint} · GeoNames (CC BY 4.0)</small>{error&&<small role="alert" className="error">{error}</small>}</div>
}
