'use client';
import {useEffect,useRef,useState} from 'react';
import {apiFetch} from '@/lib/api-fetch';
import {type CV} from '@/domain/cv';
import {professionalCopy} from '@/lib/professional-copy';
import {westernDigits} from '@/domain/professional-data';
type Recognition={lang:string;continuous:boolean;interimResults:boolean;start:()=>void;stop:()=>void;abort:()=>void;onresult:((e:{results:{[index:number]:{[index:number]:{transcript:string}};length:number};resultIndex:number})=>void)|null;onend:(()=>void)|null;onerror:((e:{error:string})=>void)|null};
type SpeechWindow=Window&{SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};
export function VoiceInterview({locale,cv,consent,onDraft}:{locale:string;cv:CV;consent:boolean;onDraft:(cv:CV)=>void}){
 const c=professionalCopy(locale),recognition=useRef<Recognition|null>(null),[active,setActive]=useState(false),[listening,setListening]=useState(false),[supported,setSupported]=useState(false),[question,setQuestion]=useState(c.firstQuestion),[answer,setAnswer]=useState(''),[transcript,setTranscript]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setSupported(Boolean((window as SpeechWindow).SpeechRecognition||(window as SpeechWindow).webkitSpeechRecognition));return()=>{recognition.current?.abort();window.speechSynthesis?.cancel()}},[]);
 function speak(){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(question);u.lang=locale==='ar'?'ar-SA':locale;window.speechSynthesis.speak(u)}
 function listen(){window.speechSynthesis?.cancel();if(listening){recognition.current?.stop();return}const Constructor=(window as SpeechWindow).SpeechRecognition||(window as SpeechWindow).webkitSpeechRecognition;if(!Constructor)return;const r=new Constructor();recognition.current=r;r.lang=locale==='ar'?'ar-PS':locale;r.continuous=false;r.interimResults=false;r.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';setAnswer(v=>(v+' '+westernDigits(text)).trim())};r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setError(c.voiceUnsupported)};try{r.start();setListening(true);setError('')}catch{setError(c.voiceUnsupported)}}
 async function send(){if(!answer.trim()||busy||!consent)return;recognition.current?.stop();setBusy(true);setError('');const next=transcript+`\nQuestion: ${question}\nAnswer: ${answer}`;try{const r=await apiFetch('/api/cv',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cv,locale,mode:'voice',transcript:next,consentToExternalAI:true})});if(!r.ok)throw Error();const d=await r.json();setTranscript(next);setAnswer('');onDraft(d.cv);setQuestion(d.nextQuestion||c.review)}catch{setError(locale==='ar'?'تعذّر معالجة الإجابة. النص محفوظ ويمكنك المحاولة مجددًا.':'Could not process your answer. Your text is retained; try again.')}finally{setBusy(false)}}
 return <section className="card grid voice-interview"><h2>{c.voiceStart}</h2><p className="muted">{c.voicePrivacy}</p>{!active?<button type="button" className="btn secondary" disabled={!consent} onClick={()=>setActive(true)}>{c.voiceStart}</button>:<><p className="voice-question" role="status">{question}</p><div className="form-actions"><button type="button" className="btn secondary" onClick={speak}>{c.listen}</button>{supported&&<button type="button" className="btn" disabled={busy} onClick={listen}>{listening?c.stop:'🎙 '+c.answer}</button>}</div>{!supported&&<p>{c.voiceUnsupported}</p>}<textarea aria-label={c.answer} rows={4} maxLength={5000} value={answer} disabled={busy} onChange={e=>setAnswer(westernDigits(e.target.value))}/><button type="button" className="btn" disabled={!consent||busy||!answer.trim()} onClick={()=>void send()}>{busy?'…':c.send}</button>{transcript&&<details><summary>{c.review}</summary><pre className="source-text">{transcript}</pre></details>}{error&&<p role="alert" className="error">{error}</p>}</>}</section>
}
