"use client";
import { FormEvent, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase/client";
import { ACCOUNT_TYPES, type AccountType } from "@/domain/marketplace";
export function AuthForm({locale}:{locale:string}) {
 const [mode,setMode]=useState<"signin"|"register">("signin"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget),email=String(fd.get("email")),password=String(fd.get("password"));try{const db=supabaseBrowser();if(mode==="signin"){const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;location.assign(`/${locale}/dashboard`)}else{const accountType=String(fd.get("accountType")) as AccountType;if(!ACCOUNT_TYPES.includes(accountType))throw new Error("Choose an account type");const {error}=await db.auth.signUp({email,password,options:{data:{account_type:accountType,display_name:String(fd.get("name"))},emailRedirectTo:`${location.origin}/auth/callback?next=/${locale}/dashboard`}});if(error)throw error;setError("Check your email to confirm your account.")}}catch(e){setError(e instanceof Error?e.message:"Authentication failed")}finally{setBusy(false)}}
 async function google(){const {error}=await supabaseBrowser().auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback?next=/${locale}/dashboard`}});if(error)setError(error.message)}
 return <div className="card"><div className="tabs"><button type="button" className={mode==="signin"?"btn":"btn secondary"} onClick={()=>setMode("signin")}>Sign in</button><button type="button" className={mode==="register"?"btn":"btn secondary"} onClick={()=>setMode("register")}>Create account</button></div><h1>{mode==="signin"?"Welcome back":"Join GazaWorks"}</h1><form className="grid" onSubmit={submit}>{mode==="register"&&<><label>Full or professional name<input name="name" minLength={2} maxLength={100} required/></label><label>Permanent account type<select name="accountType" required defaultValue=""><option value="" disabled>Select one</option><option value="individual">Individual professional from Gaza</option><option value="team">Team / startup / agency from Gaza</option><option value="client">International client / organization</option></select></label></>}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" minLength={10} required autoComplete={mode==="signin"?"current-password":"new-password"}/></label><button className="btn" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Sign in":"Create secure account"}</button></form><button className="btn secondary" style={{width:"100%",marginTop:12}} onClick={google}>Continue with Google</button>{error&&<p role="status" className={error.startsWith("Check")?"success":"error"}>{error}</p>}<a href={`/${locale}/auth/reset`} className="muted">Forgot password?</a></div>
}
